const countriesData = [
    // ============ AFRICA (54 Countries) ============
    {
        "country_name": "Algeria",
        "flag_emoji": "🇩🇿",
        "capital": "Algiers",
        "continent": "Africa",
        "short_description": "The largest country in Africa by area, located in North Africa.",
        "fact_1": "Algeria is the largest country in Africa and the 10th largest in the world.",
        "fact_2": "About 80% of the country is covered by the Sahara Desert.",
        "fact_3": "It has the longest coastline on the Mediterranean Sea among African countries.",
        "quiz_question": "What percentage of Algeria is covered by the Sahara Desert?",
        "quiz_options": ["50%", "60%", "80%", "90%"],
        "correct_answer": "80%",
        "map_coordinates": [28.0339, 1.6596]
    },
    {
        "country_name": "Angola",
        "flag_emoji": "🇦🇴",
        "capital": "Luanda",
        "continent": "Africa",
        "short_description": "A Southern African nation rich in oil and diamonds.",
        "fact_1": "Angola is Africa's second-largest oil producer after Nigeria.",
        "fact_2": "The Kalandula Falls are among the largest waterfalls in Africa.",
        "fact_3": "It was a Portuguese colony until gaining independence in 1975.",
        "quiz_question": "What is the capital of Angola?",
        "quiz_options": ["Luanda", "Benguela", "Huambo", "Lobito"],
        "correct_answer": "Luanda",
        "map_coordinates": [-11.2027, 17.8739]
    },
    {
        "country_name": "Benin",
        "flag_emoji": "🇧🇯",
        "capital": "Porto-Novo",
        "continent": "Africa",
        "short_description": "A West African nation known as the birthplace of Voodoo religion.",
        "fact_1": "Benin is considered the birthplace of the Voodoo religion.",
        "fact_2": "The former Kingdom of Dahomey was located in present-day Benin.",
        "fact_3": "Porto-Novo is the official capital, but Cotonou is the largest city.",
        "quiz_question": "Which religion is said to have originated in Benin?",
        "quiz_options": ["Christianity", "Islam", "Voodoo", "Hinduism"],
        "correct_answer": "Voodoo",
        "map_coordinates": [9.3077, 2.3158]
    },
    {
        "country_name": "Botswana",
        "flag_emoji": "🇧🇼",
        "capital": "Gaborone",
        "continent": "Africa",
        "short_description": "A landlocked country famous for the Okavango Delta and wildlife.",
        "fact_1": "The Okavango Delta is the world's largest inland delta.",
        "fact_2": "About 70% of Botswana is covered by the Kalahari Desert.",
        "fact_3": "Botswana is one of Africa's most stable democracies since 1966.",
        "quiz_question": "Which famous delta is located in Botswana?",
        "quiz_options": ["Nile Delta", "Okavango Delta", "Niger Delta", "Ganges Delta"],
        "correct_answer": "Okavango Delta",
        "map_coordinates": [-22.3285, 24.6849]
    },
    {
        "country_name": "Burkina Faso",
        "flag_emoji": "🇧🇫",
        "capital": "Ouagadougou",
        "continent": "Africa",
        "short_description": "A landlocked West African country whose name means 'Land of Honest People'.",
        "fact_1": "Burkina Faso means 'Land of Honest People' in local languages.",
        "fact_2": "It was formerly known as Upper Volta until 1984.",
        "fact_3": "Ouagadougou hosts Africa's largest film festival, FESPACO.",
        "quiz_question": "What was Burkina Faso formerly known as?",
        "quiz_options": ["Lower Volta", "Upper Volta", "Gold Coast", "Ivory Coast"],
        "correct_answer": "Upper Volta",
        "map_coordinates": [12.2383, -1.5616]
    },
    {
        "country_name": "Burundi",
        "flag_emoji": "🇧🇮",
        "capital": "Gitega",
        "continent": "Africa",
        "short_description": "A small landlocked country in the African Great Lakes region.",
        "fact_1": "Burundi is one of the most densely populated countries in Africa.",
        "fact_2": "Lake Tanganyika, the world's second-deepest lake, borders Burundi.",
        "fact_3": "The capital was moved from Bujumbura to Gitega in 2019.",
        "quiz_question": "Which lake borders Burundi?",
        "quiz_options": ["Lake Victoria", "Lake Malawi", "Lake Tanganyika", "Lake Chad"],
        "correct_answer": "Lake Tanganyika",
        "map_coordinates": [-3.3731, 29.9189]
    },
    {
        "country_name": "Cabo Verde",
        "flag_emoji": "🇨🇻",
        "capital": "Praia",
        "continent": "Africa",
        "short_description": "An island nation off the west coast of Africa in the Atlantic Ocean.",
        "fact_1": "Cabo Verde consists of 10 volcanic islands.",
        "fact_2": "It was uninhabited until Portuguese colonizers arrived in 1456.",
        "fact_3": "The country has no natural freshwater sources.",
        "quiz_question": "How many islands make up Cabo Verde?",
        "quiz_options": ["5", "7", "10", "15"],
        "correct_answer": "10",
        "map_coordinates": [16.5388, -23.0418]
    },
    {
        "country_name": "Cameroon",
        "flag_emoji": "🇨🇲",
        "capital": "Yaoundé",
        "continent": "Africa",
        "short_description": "A Central African nation known as 'Africa in Miniature' for its diversity.",
        "fact_1": "Cameroon is called 'Africa in Miniature' due to its diverse landscapes.",
        "fact_2": "Mount Cameroon is the highest peak in West and Central Africa.",
        "fact_3": "It has both English and French as official languages.",
        "quiz_question": "Why is Cameroon called 'Africa in Miniature'?",
        "quiz_options": ["Small size", "Diverse landscapes", "Many languages", "Ancient history"],
        "correct_answer": "Diverse landscapes",
        "map_coordinates": [7.3697, 12.3547]
    },
    {
        "country_name": "Central African Republic",
        "flag_emoji": "🇨🇫",
        "capital": "Bangui",
        "continent": "Africa",
        "short_description": "A landlocked country in Central Africa with dense rainforests.",
        "fact_1": "The country is home to one of Africa's largest remaining rainforests.",
        "fact_2": "Diamonds and timber are the main export resources.",
        "fact_3": "The Ubangi River forms part of its southern border with DR Congo.",
        "quiz_question": "What is the capital of the Central African Republic?",
        "quiz_options": ["Kinshasa", "Bangui", "Libreville", "Brazzaville"],
        "correct_answer": "Bangui",
        "map_coordinates": [6.6111, 20.9394]
    },
    {
        "country_name": "Chad",
        "flag_emoji": "🇹🇩",
        "capital": "N'Djamena",
        "continent": "Africa",
        "short_description": "A landlocked country with the Sahara Desert in the north.",
        "fact_1": "Lake Chad, once one of Africa's largest lakes, has shrunk by 90%.",
        "fact_2": "The Tibesti Mountains in northern Chad reach over 3,400 meters.",
        "fact_3": "Chad is sometimes called the 'Dead Heart of Africa'.",
        "quiz_question": "By how much has Lake Chad shrunk since the 1960s?",
        "quiz_options": ["50%", "70%", "90%", "30%"],
        "correct_answer": "90%",
        "map_coordinates": [15.4542, 18.7322]
    },
    {
        "country_name": "Comoros",
        "flag_emoji": "🇰🇲",
        "capital": "Moroni",
        "continent": "Africa",
        "short_description": "An island nation in the Indian Ocean between Madagascar and Mozambique.",
        "fact_1": "Comoros is one of the world's largest producers of ylang-ylang perfume essence.",
        "fact_2": "Mount Karthala is one of the world's largest active volcanoes.",
        "fact_3": "The country consists of three major islands and several smaller ones.",
        "quiz_question": "What fragrant essence is Comoros famous for producing?",
        "quiz_options": ["Lavender", "Rose", "Ylang-ylang", "Jasmine"],
        "correct_answer": "Ylang-ylang",
        "map_coordinates": [-11.6455, 43.3333]
    },
    {
        "country_name": "Democratic Republic of the Congo",
        "flag_emoji": "🇨🇩",
        "capital": "Kinshasa",
        "continent": "Africa",
        "short_description": "The largest country in Sub-Saharan Africa with vast rainforests.",
        "fact_1": "DRC has the second-largest rainforest in the world after the Amazon.",
        "fact_2": "The Congo River is the deepest river in the world, reaching 220 meters.",
        "fact_3": "It contains about 70% of the world's coltan, used in electronics.",
        "quiz_question": "Which river in DRC is the world's deepest?",
        "quiz_options": ["Nile", "Amazon", "Congo", "Zambezi"],
        "correct_answer": "Congo",
        "map_coordinates": [-4.0383, 21.7587]
    },
    {
        "country_name": "Republic of the Congo",
        "flag_emoji": "🇨🇬",
        "capital": "Brazzaville",
        "continent": "Africa",
        "short_description": "A Central African country sharing a border with the Congo River.",
        "fact_1": "Brazzaville and Kinshasa are the world's closest national capitals.",
        "fact_2": "About 70% of the country is covered by rainforest.",
        "fact_3": "Oil accounts for about 90% of the country's exports.",
        "quiz_question": "Which two capitals are located directly across the Congo River from each other?",
        "quiz_options": ["Brazzaville and Kinshasa", "Libreville and Malabo", "Bangui and Kinshasa", "Luanda and Brazzaville"],
        "correct_answer": "Brazzaville and Kinshasa",
        "map_coordinates": [-0.2280, 15.8277]
    },
    {
        "country_name": "Côte d'Ivoire",
        "flag_emoji": "🇨🇮",
        "capital": "Yamoussoukro",
        "continent": "Africa",
        "short_description": "The world's largest cocoa producer in West Africa.",
        "fact_1": "Côte d'Ivoire produces about 40% of the world's cocoa.",
        "fact_2": "The Basilica of Our Lady of Peace is the world's largest church.",
        "fact_3": "Yamoussoukro is the official capital, but Abidjan is the largest city.",
        "quiz_question": "What crop is Côte d'Ivoire the world's largest producer of?",
        "quiz_options": ["Coffee", "Cocoa", "Cotton", "Rubber"],
        "correct_answer": "Cocoa",
        "map_coordinates": [7.5400, -5.5471]
    },
    {
        "country_name": "Djibouti",
        "flag_emoji": "🇩🇯",
        "capital": "Djibouti",
        "continent": "Africa",
        "short_description": "A small nation at the Horn of Africa with strategic importance.",
        "fact_1": "Lake Assal is the lowest point in Africa and the saltiest lake outside Antarctica.",
        "fact_2": "Djibouti hosts military bases for several countries including the US and China.",
        "fact_3": "The country is located at the strategic Bab-el-Mandeb strait.",
        "quiz_question": "What is the lowest point in Africa?",
        "quiz_options": ["Lake Tanganyika", "Lake Assal", "Dead Sea", "Qattara Depression"],
        "correct_answer": "Lake Assal",
        "map_coordinates": [11.8251, 42.5903]
    },
    {
        "country_name": "Egypt",
        "flag_emoji": "🇪🇬",
        "capital": "Cairo",
        "continent": "Africa",
        "short_description": "Home to ancient pyramids and the world's longest river, the Nile.",
        "fact_1": "The Nile River, the world's longest, flows through Egypt for 1,500 km.",
        "fact_2": "The Great Pyramid of Giza is the only surviving ancient wonder.",
        "fact_3": "The Suez Canal connects the Mediterranean Sea to the Red Sea.",
        "quiz_question": "Which canal connects the Mediterranean to the Red Sea?",
        "quiz_options": ["Panama Canal", "Suez Canal", "Kiel Canal", "Erie Canal"],
        "correct_answer": "Suez Canal",
        "map_coordinates": [26.8206, 30.8025]
    },
    {
        "country_name": "Equatorial Guinea",
        "flag_emoji": "🇬🇶",
        "capital": "Malabo",
        "continent": "Africa",
        "short_description": "Africa's only Spanish-speaking country, rich in oil.",
        "fact_1": "Equatorial Guinea is the only African country with Spanish as an official language.",
        "fact_2": "It is one of the richest countries in Africa per capita due to oil.",
        "fact_3": "The capital Malabo is located on an island, not the mainland.",
        "quiz_question": "Which European language is official in Equatorial Guinea?",
        "quiz_options": ["French", "Portuguese", "Spanish", "English"],
        "correct_answer": "Spanish",
        "map_coordinates": [1.6508, 10.2679]
    },
    {
        "country_name": "Eritrea",
        "flag_emoji": "🇪🇷",
        "capital": "Asmara",
        "continent": "Africa",
        "short_description": "A country on the Red Sea coast that gained independence in 1993.",
        "fact_1": "Eritrea has one of the world's longest coastlines on the Red Sea.",
        "fact_2": "Asmara is called 'Little Rome' for its Italian colonial architecture.",
        "fact_3": "The Dahlak Archipelago has over 200 islands in the Red Sea.",
        "quiz_question": "What architectural style is Asmara famous for?",
        "quiz_options": ["British Victorian", "Italian Art Deco", "French Gothic", "Spanish Colonial"],
        "correct_answer": "Italian Art Deco",
        "map_coordinates": [15.1794, 39.7823]
    },
    {
        "country_name": "Eswatini",
        "flag_emoji": "🇸🇿",
        "capital": "Mbabane",
        "continent": "Africa",
        "short_description": "A small landlocked kingdom, formerly known as Swaziland.",
        "fact_1": "Eswatini is one of the world's last absolute monarchies.",
        "fact_2": "The country changed its name from Swaziland in 2018.",
        "fact_3": "It is one of the smallest countries in Africa by area.",
        "quiz_question": "What was Eswatini formerly known as?",
        "quiz_options": ["Lesotho", "Swaziland", "Basutoland", "Bechuanaland"],
        "correct_answer": "Swaziland",
        "map_coordinates": [-26.5225, 31.4659]
    },
    {
        "country_name": "Ethiopia",
        "flag_emoji": "🇪🇹",
        "capital": "Addis Ababa",
        "continent": "Africa",
        "short_description": "Africa's oldest independent nation and birthplace of coffee.",
        "fact_1": "Ethiopia is the birthplace of coffee, discovered in the Kaffa region.",
        "fact_2": "It follows its own calendar that is 7-8 years behind the Gregorian calendar.",
        "fact_3": "Ethiopia was never colonized, except for a brief Italian occupation.",
        "quiz_question": "Which beverage is said to have originated in Ethiopia?",
        "quiz_options": ["Tea", "Coffee", "Cocoa", "Wine"],
        "correct_answer": "Coffee",
        "map_coordinates": [9.1450, 40.4897]
    },
    {
        "country_name": "Gabon",
        "flag_emoji": "🇬🇦",
        "capital": "Libreville",
        "continent": "Africa",
        "short_description": "A Central African nation with 80% of its land covered by rainforest.",
        "fact_1": "About 80% of Gabon is covered by tropical rainforest.",
        "fact_2": "Gabon is home to the largest population of forest elephants in Africa.",
        "fact_3": "Oil exports make up about 80% of the country's revenue.",
        "quiz_question": "What percentage of Gabon is covered by rainforest?",
        "quiz_options": ["50%", "60%", "80%", "95%"],
        "correct_answer": "80%",
        "map_coordinates": [-0.8037, 11.6094]
    },
    {
        "country_name": "Gambia",
        "flag_emoji": "🇬🇲",
        "capital": "Banjul",
        "continent": "Africa",
        "short_description": "The smallest country in mainland Africa, surrounded by Senegal.",
        "fact_1": "Gambia is the smallest country on mainland Africa.",
        "fact_2": "The country is essentially a narrow strip along the Gambia River.",
        "fact_3": "Gambia is almost entirely surrounded by Senegal.",
        "quiz_question": "Which country almost completely surrounds Gambia?",
        "quiz_options": ["Guinea", "Mauritania", "Senegal", "Mali"],
        "correct_answer": "Senegal",
        "map_coordinates": [13.4432, -15.3101]
    },
    {
        "country_name": "Ghana",
        "flag_emoji": "🇬🇭",
        "capital": "Accra",
        "continent": "Africa",
        "short_description": "West African nation formerly known as Gold Coast, rich in gold and cocoa.",
        "fact_1": "Ghana was the first Sub-Saharan African country to gain independence in 1957.",
        "fact_2": "It was formerly called the Gold Coast due to its gold resources.",
        "fact_3": "Lake Volta is one of the world's largest artificial lakes.",
        "quiz_question": "In what year did Ghana gain independence?",
        "quiz_options": ["1947", "1957", "1960", "1963"],
        "correct_answer": "1957",
        "map_coordinates": [7.9465, -1.0232]
    },
    {
        "country_name": "Guinea",
        "flag_emoji": "🇬🇳",
        "capital": "Conakry",
        "continent": "Africa",
        "short_description": "A West African country with the world's largest bauxite reserves.",
        "fact_1": "Guinea has the world's largest reserves of bauxite (aluminum ore).",
        "fact_2": "The Niger, Senegal, and Gambia rivers all originate in Guinea.",
        "fact_3": "Mount Nimba on the border reaches 1,752 meters.",
        "quiz_question": "Which mineral is Guinea the world's largest reserve holder of?",
        "quiz_options": ["Gold", "Diamond", "Bauxite", "Iron"],
        "correct_answer": "Bauxite",
        "map_coordinates": [9.9456, -9.6966]
    },
    {
        "country_name": "Guinea-Bissau",
        "flag_emoji": "🇬🇼",
        "capital": "Bissau",
        "continent": "Africa",
        "short_description": "A small West African nation with a coast on the Atlantic Ocean.",
        "fact_1": "Guinea-Bissau has the Bijagós Archipelago with 88 islands.",
        "fact_2": "Cashew nuts are the country's main export product.",
        "fact_3": "Portuguese is the official language from colonial times.",
        "quiz_question": "What is Guinea-Bissau's main export crop?",
        "quiz_options": ["Coffee", "Cocoa", "Cashew nuts", "Palm oil"],
        "correct_answer": "Cashew nuts",
        "map_coordinates": [11.8037, -15.1804]
    },
    {
        "country_name": "Kenya",
        "flag_emoji": "🇰🇪",
        "capital": "Nairobi",
        "continent": "Africa",
        "short_description": "East African nation famous for wildlife safaris and the Great Rift Valley.",
        "fact_1": "Kenya is named after Mount Kenya, the second-highest peak in Africa.",
        "fact_2": "The Great Wildebeest Migration passes through Kenya's Masai Mara.",
        "fact_3": "Kenya is the world's third-largest tea exporter.",
        "quiz_question": "Which famous animal migration passes through Kenya's Masai Mara?",
        "quiz_options": ["Elephant Migration", "Wildebeest Migration", "Zebra Migration", "Lion Migration"],
        "correct_answer": "Wildebeest Migration",
        "map_coordinates": [-0.0236, 37.9062]
    },
    {
        "country_name": "Lesotho",
        "flag_emoji": "🇱🇸",
        "capital": "Maseru",
        "continent": "Africa",
        "short_description": "A mountainous kingdom completely surrounded by South Africa.",
        "fact_1": "Lesotho is the only country in the world entirely above 1,000 meters elevation.",
        "fact_2": "It is completely surrounded by South Africa, making it an enclave.",
        "fact_3": "Lesotho is sometimes called 'The Kingdom in the Sky'.",
        "quiz_question": "What unique geographical feature does Lesotho have?",
        "quiz_options": ["Lowest point in Africa", "Entirely above 1000m", "Largest lake", "Longest river"],
        "correct_answer": "Entirely above 1000m",
        "map_coordinates": [-29.6100, 28.2336]
    },
    {
        "country_name": "Liberia",
        "flag_emoji": "🇱🇷",
        "capital": "Monrovia",
        "continent": "Africa",
        "short_description": "Founded by freed American slaves, Africa's oldest republic.",
        "fact_1": "Liberia was founded by freed American slaves in 1822.",
        "fact_2": "The capital Monrovia is named after US President James Monroe.",
        "fact_3": "It is Africa's first and oldest republic, established in 1847.",
        "quiz_question": "After which US President is Monrovia named?",
        "quiz_options": ["Washington", "Jefferson", "Monroe", "Lincoln"],
        "correct_answer": "Monroe",
        "map_coordinates": [6.4281, -9.4295]
    },
    {
        "country_name": "Libya",
        "flag_emoji": "🇱🇾",
        "capital": "Tripoli",
        "continent": "Africa",
        "short_description": "A North African country with the largest proven oil reserves in Africa.",
        "fact_1": "Libya has the largest proven oil reserves in Africa.",
        "fact_2": "About 90% of the country is desert, mostly the Sahara.",
        "fact_3": "Libya has the longest Mediterranean coastline in Africa.",
        "quiz_question": "What percentage of Libya is desert?",
        "quiz_options": ["60%", "75%", "90%", "99%"],
        "correct_answer": "90%",
        "map_coordinates": [26.3351, 17.2283]
    },
    {
        "country_name": "Madagascar",
        "flag_emoji": "🇲🇬",
        "capital": "Antananarivo",
        "continent": "Africa",
        "short_description": "The world's fourth-largest island with unique wildlife found nowhere else.",
        "fact_1": "About 90% of Madagascar's wildlife is found nowhere else on Earth.",
        "fact_2": "It is the world's fourth-largest island after Greenland, New Guinea, and Borneo.",
        "fact_3": "Madagascar separated from India about 88 million years ago.",
        "quiz_question": "What percentage of Madagascar's wildlife is endemic (found only there)?",
        "quiz_options": ["50%", "70%", "90%", "100%"],
        "correct_answer": "90%",
        "map_coordinates": [-18.7669, 46.8691]
    },
    {
        "country_name": "Malawi",
        "flag_emoji": "🇲🇼",
        "capital": "Lilongwe",
        "continent": "Africa",
        "short_description": "A landlocked country known as 'The Warm Heart of Africa'.",
        "fact_1": "Lake Malawi contains more fish species than any other lake in the world.",
        "fact_2": "Malawi is known as 'The Warm Heart of Africa' for its friendly people.",
        "fact_3": "Lake Malawi covers about 20% of the country's total area.",
        "quiz_question": "What nickname is given to Malawi?",
        "quiz_options": ["Pearl of Africa", "Warm Heart of Africa", "Gift of the Nile", "Rainbow Nation"],
        "correct_answer": "Warm Heart of Africa",
        "map_coordinates": [-13.2543, 34.3015]
    },
    {
        "country_name": "Mali",
        "flag_emoji": "🇲🇱",
        "capital": "Bamako",
        "continent": "Africa",
        "short_description": "A landlocked West African country that was once part of powerful empires.",
        "fact_1": "Timbuktu was once one of the world's greatest centers of learning.",
        "fact_2": "The Mali Empire was one of the richest in history.",
        "fact_3": "The Niger River flows through Mali, providing a lifeline in the desert.",
        "quiz_question": "Which historic city in Mali was a great center of learning?",
        "quiz_options": ["Bamako", "Timbuktu", "Gao", "Mopti"],
        "correct_answer": "Timbuktu",
        "map_coordinates": [17.5707, -3.9962]
    },
    {
        "country_name": "Mauritania",
        "flag_emoji": "🇲🇷",
        "capital": "Nouakchott",
        "continent": "Africa",
        "short_description": "A Saharan country bridging Arab North Africa and Sub-Saharan Africa.",
        "fact_1": "Mauritania was the last country to abolish slavery in 1981.",
        "fact_2": "The Richat Structure, called the 'Eye of Africa', is a 50 km wide formation.",
        "fact_3": "About 90% of the country is in the Sahara Desert.",
        "quiz_question": "What is the 'Eye of Africa' also known as?",
        "quiz_options": ["Lake Chad", "Mount Kilimanjaro", "Richat Structure", "Victoria Falls"],
        "correct_answer": "Richat Structure",
        "map_coordinates": [21.0079, -10.9408]
    },
    {
        "country_name": "Mauritius",
        "flag_emoji": "🇲🇺",
        "capital": "Port Louis",
        "continent": "Africa",
        "short_description": "An island nation in the Indian Ocean known for its beaches and reefs.",
        "fact_1": "The dodo bird, now extinct, was endemic to Mauritius.",
        "fact_2": "Mauritius has one of Africa's highest GDPs per capita.",
        "fact_3": "The country has the world's third-largest coral reef system.",
        "quiz_question": "Which extinct bird was native only to Mauritius?",
        "quiz_options": ["Passenger Pigeon", "Dodo", "Great Auk", "Moa"],
        "correct_answer": "Dodo",
        "map_coordinates": [-20.3484, 57.5522]
    },
    {
        "country_name": "Morocco",
        "flag_emoji": "🇲🇦",
        "capital": "Rabat",
        "continent": "Africa",
        "short_description": "A North African kingdom with coastlines on both the Atlantic and Mediterranean.",
        "fact_1": "Morocco is the world's largest exporter of phosphates.",
        "fact_2": "The University of Al-Qarawiyyin, founded in 859 AD, is the world's oldest university.",
        "fact_3": "Morocco controls Western Sahara, though its sovereignty is disputed.",
        "quiz_question": "What is Morocco the world's largest exporter of?",
        "quiz_options": ["Oil", "Phosphates", "Gold", "Diamonds"],
        "correct_answer": "Phosphates",
        "map_coordinates": [31.7917, -7.0926]
    },
    {
        "country_name": "Mozambique",
        "flag_emoji": "🇲🇿",
        "capital": "Maputo",
        "continent": "Africa",
        "short_description": "A Southeast African country with a long Indian Ocean coastline.",
        "fact_1": "Mozambique has one of Africa's longest coastlines at 2,500 km.",
        "fact_2": "The country's flag features an AK-47, symbolizing the independence struggle.",
        "fact_3": "The Zambezi River forms part of its border with Zambia and Zimbabwe.",
        "quiz_question": "What unusual symbol appears on Mozambique's flag?",
        "quiz_options": ["A sword", "A spear", "An AK-47", "A shield"],
        "correct_answer": "An AK-47",
        "map_coordinates": [-18.6657, 35.5296]
    },
    {
        "country_name": "Namibia",
        "flag_emoji": "🇳🇦",
        "capital": "Windhoek",
        "continent": "Africa",
        "short_description": "Home to the world's oldest desert, the Namib Desert.",
        "fact_1": "The Namib Desert is considered the world's oldest desert at 55-80 million years.",
        "fact_2": "Namibia has the second-lowest population density in the world after Mongolia.",
        "fact_3": "Fish River Canyon is the largest canyon in Africa.",
        "quiz_question": "How old is the Namib Desert, the world's oldest?",
        "quiz_options": ["10 million years", "55-80 million years", "100 million years", "1 million years"],
        "correct_answer": "55-80 million years",
        "map_coordinates": [-22.9576, 18.4904]
    },
    {
        "country_name": "Niger",
        "flag_emoji": "🇳🇪",
        "capital": "Niamey",
        "continent": "Africa",
        "short_description": "A landlocked Saharan nation named after the Niger River.",
        "fact_1": "Niger is one of the hottest countries in the world, called 'The Frying Pan of the World'.",
        "fact_2": "About 80% of the country lies within the Sahara Desert.",
        "fact_3": "Niger has some of the world's largest uranium deposits.",
        "quiz_question": "What nickname is given to Niger due to its extreme heat?",
        "quiz_options": ["The Sun Country", "The Frying Pan of the World", "The Hot Zone", "The Burning Land"],
        "correct_answer": "The Frying Pan of the World",
        "map_coordinates": [17.6078, 8.0817]
    },
    {
        "country_name": "Nigeria",
        "flag_emoji": "🇳🇬",
        "capital": "Abuja",
        "continent": "Africa",
        "short_description": "Africa's most populous country and largest economy.",
        "fact_1": "Nigeria is Africa's most populous country with over 200 million people.",
        "fact_2": "It is Africa's largest oil producer and has the continent's largest economy.",
        "fact_3": "Nigeria has over 500 ethnic groups and 500 languages.",
        "quiz_question": "Approximately how many people live in Nigeria?",
        "quiz_options": ["100 million", "150 million", "200 million", "300 million"],
        "correct_answer": "200 million",
        "map_coordinates": [9.0820, 8.6753]
    },
    {
        "country_name": "Rwanda",
        "flag_emoji": "🇷🇼",
        "capital": "Kigali",
        "continent": "Africa",
        "short_description": "Known as 'Land of a Thousand Hills' in the African Great Lakes region.",
        "fact_1": "Rwanda is called 'Land of a Thousand Hills' due to its mountainous terrain.",
        "fact_2": "Rwanda has one of the cleanest cities in Africa, Kigali.",
        "fact_3": "The mountain gorillas of Rwanda are critically endangered.",
        "quiz_question": "What is Rwanda nicknamed due to its landscape?",
        "quiz_options": ["Land of Lakes", "Land of a Thousand Hills", "Pearl of Africa", "Heart of Africa"],
        "correct_answer": "Land of a Thousand Hills",
        "map_coordinates": [-1.9403, 29.8739]
    },
    {
        "country_name": "São Tomé and Príncipe",
        "flag_emoji": "🇸🇹",
        "capital": "São Tomé",
        "continent": "Africa",
        "short_description": "Africa's smallest country, an island nation in the Gulf of Guinea.",
        "fact_1": "São Tomé and Príncipe is Africa's smallest country by area.",
        "fact_2": "The country straddles the Equator.",
        "fact_3": "Cocoa is the main export, once called 'chocolate islands'.",
        "quiz_question": "What geographic line passes through São Tomé and Príncipe?",
        "quiz_options": ["Tropic of Cancer", "Tropic of Capricorn", "Equator", "Prime Meridian"],
        "correct_answer": "Equator",
        "map_coordinates": [0.1864, 6.6131]
    },
    {
        "country_name": "Senegal",
        "flag_emoji": "🇸🇳",
        "capital": "Dakar",
        "continent": "Africa",
        "short_description": "The westernmost country on the African mainland.",
        "fact_1": "Senegal is the westernmost country on the African mainland.",
        "fact_2": "The Dakar Rally, a famous off-road race, was named after its capital.",
        "fact_3": "Lake Retba (Pink Lake) is known for its rose-colored waters.",
        "quiz_question": "What is special about Senegal's geographic position in Africa?",
        "quiz_options": ["Northernmost", "Southernmost", "Easternmost", "Westernmost"],
        "correct_answer": "Westernmost",
        "map_coordinates": [14.4974, -14.4524]
    },
    {
        "country_name": "Seychelles",
        "flag_emoji": "🇸🇨",
        "capital": "Victoria",
        "continent": "Africa",
        "short_description": "An archipelago of 115 islands in the Indian Ocean.",
        "fact_1": "Seychelles has the smallest population of any African country.",
        "fact_2": "The coco de mer palm produces the world's largest seed.",
        "fact_3": "Victoria is the smallest capital city in the world by population.",
        "quiz_question": "What world record does the coco de mer hold?",
        "quiz_options": ["Tallest tree", "Largest seed", "Oldest plant", "Smallest flower"],
        "correct_answer": "Largest seed",
        "map_coordinates": [-4.6796, 55.4920]
    },
    {
        "country_name": "Sierra Leone",
        "flag_emoji": "🇸🇱",
        "capital": "Freetown",
        "continent": "Africa",
        "short_description": "A West African nation known for its diamonds and beaches.",
        "fact_1": "Freetown was founded as a home for freed slaves.",
        "fact_2": "Sierra Leone is one of the world's top diamond-producing countries.",
        "fact_3": "The name means 'Lion Mountains' in Portuguese.",
        "quiz_question": "What does 'Sierra Leone' mean?",
        "quiz_options": ["Golden Coast", "Lion Mountains", "Free Land", "Diamond Country"],
        "correct_answer": "Lion Mountains",
        "map_coordinates": [8.4606, -11.7799]
    },
    {
        "country_name": "Somalia",
        "flag_emoji": "🇸🇴",
        "capital": "Mogadishu",
        "continent": "Africa",
        "short_description": "Located at the Horn of Africa with the longest coastline on the continent.",
        "fact_1": "Somalia has the longest coastline in Africa at over 3,000 km.",
        "fact_2": "It is often called the 'Land of Punt', an ancient Egyptian trading partner.",
        "fact_3": "Camel herding is a major part of the traditional economy.",
        "quiz_question": "How long is Somalia's coastline, Africa's longest?",
        "quiz_options": ["1,000 km", "2,000 km", "3,000 km", "4,000 km"],
        "correct_answer": "3,000 km",
        "map_coordinates": [5.1521, 46.1996]
    },
    {
        "country_name": "South Africa",
        "flag_emoji": "🇿🇦",
        "capital": "Pretoria",
        "continent": "Africa",
        "short_description": "The southernmost country in Africa with three capital cities.",
        "fact_1": "South Africa has three capital cities: Pretoria, Cape Town, and Bloemfontein.",
        "fact_2": "It is the only country to have voluntarily dismantled its nuclear weapons.",
        "fact_3": "The Kruger National Park is one of Africa's largest game reserves.",
        "quiz_question": "How many capital cities does South Africa have?",
        "quiz_options": ["1", "2", "3", "4"],
        "correct_answer": "3",
        "map_coordinates": [-30.5595, 22.9375]
    },
    {
        "country_name": "South Sudan",
        "flag_emoji": "🇸🇸",
        "capital": "Juba",
        "continent": "Africa",
        "short_description": "The world's newest country, gaining independence in 2011.",
        "fact_1": "South Sudan is the world's newest country, independent since 2011.",
        "fact_2": "The White Nile flows through the country.",
        "fact_3": "It has one of the largest swamp ecosystems in the world, the Sudd.",
        "quiz_question": "In what year did South Sudan gain independence?",
        "quiz_options": ["2005", "2008", "2011", "2015"],
        "correct_answer": "2011",
        "map_coordinates": [6.8770, 31.3070]
    },
    {
        "country_name": "Sudan",
        "flag_emoji": "🇸🇩",
        "capital": "Khartoum",
        "continent": "Africa",
        "short_description": "Located where the Blue and White Nile rivers merge.",
        "fact_1": "Khartoum is located where the Blue Nile and White Nile merge.",
        "fact_2": "Sudan has more pyramids than Egypt, with over 200 ancient pyramids.",
        "fact_3": "It was Africa's largest country until South Sudan's independence.",
        "quiz_question": "How many pyramids does Sudan have?",
        "quiz_options": ["50", "100", "200+", "20"],
        "correct_answer": "200+",
        "map_coordinates": [12.8628, 30.2176]
    },
    {
        "country_name": "Tanzania",
        "flag_emoji": "🇹🇿",
        "capital": "Dodoma",
        "continent": "Africa",
        "short_description": "Home to Mount Kilimanjaro, Africa's highest peak.",
        "fact_1": "Mount Kilimanjaro is Africa's highest peak at 5,895 meters.",
        "fact_2": "The Serengeti hosts the world's largest terrestrial animal migration.",
        "fact_3": "Zanzibar, part of Tanzania, was once a major spice trading center.",
        "quiz_question": "How tall is Mount Kilimanjaro?",
        "quiz_options": ["4,895m", "5,895m", "6,895m", "5,495m"],
        "correct_answer": "5,895m",
        "map_coordinates": [-6.3690, 34.8888]
    },
    {
        "country_name": "Togo",
        "flag_emoji": "🇹🇬",
        "capital": "Lomé",
        "continent": "Africa",
        "short_description": "One of the smallest countries in Africa, stretching north from the Gulf of Guinea.",
        "fact_1": "Togo is one of Africa's smallest countries at about 56,000 sq km.",
        "fact_2": "Lomé is one of the few African capitals located directly on the coast.",
        "fact_3": "Phosphate mining is a major industry.",
        "quiz_question": "What makes Lomé's location unusual among African capitals?",
        "quiz_options": ["In mountains", "On coast", "On island", "In desert"],
        "correct_answer": "On coast",
        "map_coordinates": [8.6195, 0.8248]
    },
    {
        "country_name": "Tunisia",
        "flag_emoji": "🇹🇳",
        "capital": "Tunis",
        "continent": "Africa",
        "short_description": "The northernmost country in Africa, home to ancient Carthage.",
        "fact_1": "Tunisia is the northernmost country in Africa.",
        "fact_2": "The ancient city of Carthage, Rome's great rival, was located here.",
        "fact_3": "Star Wars scenes were filmed in Tunisia's desert landscapes.",
        "quiz_question": "Which ancient civilization was based in Tunisia?",
        "quiz_options": ["Egypt", "Carthage", "Greece", "Babylon"],
        "correct_answer": "Carthage",
        "map_coordinates": [33.8869, 9.5375]
    },
    {
        "country_name": "Uganda",
        "flag_emoji": "🇺🇬",
        "capital": "Kampala",
        "continent": "Africa",
        "short_description": "Called 'The Pearl of Africa' for its natural beauty.",
        "fact_1": "Winston Churchill called Uganda 'The Pearl of Africa'.",
        "fact_2": "The source of the Nile River is at Lake Victoria in Uganda.",
        "fact_3": "Uganda is home to more than half of the world's mountain gorillas.",
        "quiz_question": "Who called Uganda 'The Pearl of Africa'?",
        "quiz_options": ["Queen Victoria", "Winston Churchill", "David Livingstone", "Henry Stanley"],
        "correct_answer": "Winston Churchill",
        "map_coordinates": [1.3733, 32.2903]
    },
    {
        "country_name": "Zambia",
        "flag_emoji": "🇿🇲",
        "capital": "Lusaka",
        "continent": "Africa",
        "short_description": "A landlocked country sharing Victoria Falls with Zimbabwe.",
        "fact_1": "Victoria Falls, one of the world's largest waterfalls, borders Zambia and Zimbabwe.",
        "fact_2": "Zambia was formerly known as Northern Rhodesia.",
        "fact_3": "The country has one of Africa's largest copper reserves.",
        "quiz_question": "What was Zambia's colonial name?",
        "quiz_options": ["Southern Rhodesia", "Northern Rhodesia", "Nyasaland", "Bechuanaland"],
        "correct_answer": "Northern Rhodesia",
        "map_coordinates": [-13.1339, 27.8493]
    },
    {
        "country_name": "Zimbabwe",
        "flag_emoji": "🇿🇼",
        "capital": "Harare",
        "continent": "Africa",
        "short_description": "Home to ancient stone ruins and shared Victoria Falls.",
        "fact_1": "The Great Zimbabwe ruins are one of Africa's most impressive ancient structures.",
        "fact_2": "Victoria Falls locally is called 'Mosi-oa-Tunya' (The Smoke That Thunders).",
        "fact_3": "Zimbabwe once experienced one of the worst hyperinflations in history.",
        "quiz_question": "What is the local name for Victoria Falls?",
        "quiz_options": ["Mosi-oa-Tunya", "Livingstone Falls", "Zimbabwe Falls", "Zambezi Falls"],
        "correct_answer": "Mosi-oa-Tunya",
        "map_coordinates": [-19.0154, 29.1549]
    },

    // ============ ASIA (48 Countries) ============
    {
        "country_name": "Afghanistan",
        "flag_emoji": "🇦🇫",
        "capital": "Kabul",
        "continent": "Asia",
        "short_description": "A landlocked country at the crossroads of Central and South Asia.",
        "fact_1": "Afghanistan is known as the 'Graveyard of Empires' due to failed invasions.",
        "fact_2": "The Hindu Kush mountain range crosses the country.",
        "fact_3": "Afghanistan is the world's largest producer of opium poppies.",
        "quiz_question": "What mountain range runs through Afghanistan?",
        "quiz_options": ["Himalayas", "Hindu Kush", "Karakoram", "Tian Shan"],
        "correct_answer": "Hindu Kush",
        "map_coordinates": [33.9391, 67.7100]
    },
    {
        "country_name": "Armenia",
        "flag_emoji": "🇦🇲",
        "capital": "Yerevan",
        "continent": "Asia",
        "short_description": "One of the oldest Christian nations in the world.",
        "fact_1": "Armenia was the first country to adopt Christianity as a state religion in 301 AD.",
        "fact_2": "Mount Ararat, where Noah's Ark allegedly landed, is visible from Armenia.",
        "fact_3": "The Armenian alphabet was created in 405 AD and has 39 letters.",
        "quiz_question": "In what year did Armenia become the first Christian nation?",
        "quiz_options": ["200 AD", "301 AD", "400 AD", "500 AD"],
        "correct_answer": "301 AD",
        "map_coordinates": [40.0691, 45.0382]
    },
    {
        "country_name": "Azerbaijan",
        "flag_emoji": "🇦🇿",
        "capital": "Baku",
        "continent": "Asia",
        "short_description": "Known as the 'Land of Fire' due to natural gas fires.",
        "fact_1": "Azerbaijan is called 'Land of Fire' for its natural gas fires.",
        "fact_2": "Baku is the lowest lying capital city in the world at 28m below sea level.",
        "fact_3": "The Caspian Sea, the world's largest lake, borders Azerbaijan.",
        "quiz_question": "Why is Azerbaijan called the 'Land of Fire'?",
        "quiz_options": ["Hot climate", "Natural gas fires", "Volcanoes", "Desert"],
        "correct_answer": "Natural gas fires",
        "map_coordinates": [40.1431, 47.5769]
    },
    {
        "country_name": "Bahrain",
        "flag_emoji": "🇧🇭",
        "capital": "Manama",
        "continent": "Asia",
        "short_description": "An island nation in the Persian Gulf connected to Saudi Arabia by causeway.",
        "fact_1": "Bahrain means 'Two Seas' in Arabic, referring to fresh and salt water.",
        "fact_2": "The King Fahd Causeway connects Bahrain to Saudi Arabia.",
        "fact_3": "Bahrain was the first Gulf state to discover oil in 1932.",
        "quiz_question": "What connects Bahrain to Saudi Arabia?",
        "quiz_options": ["Bridge", "Tunnel", "Causeway", "Ferry"],
        "correct_answer": "Causeway",
        "map_coordinates": [26.0667, 50.5577]
    },
    {
        "country_name": "Bangladesh",
        "flag_emoji": "🇧🇩",
        "capital": "Dhaka",
        "continent": "Asia",
        "short_description": "One of the world's most densely populated countries in South Asia.",
        "fact_1": "Bangladesh has the world's largest river delta, the Ganges-Brahmaputra Delta.",
        "fact_2": "The Sundarbans mangrove forest is the largest in the world.",
        "fact_3": "Cox's Bazar has the world's longest natural sea beach at 120 km.",
        "quiz_question": "What is special about Cox's Bazar beach?",
        "quiz_options": ["Oldest beach", "Most beautiful", "Longest natural beach", "Whitest sand"],
        "correct_answer": "Longest natural beach",
        "map_coordinates": [23.6850, 90.3563]
    },
    {
        "country_name": "Bhutan",
        "flag_emoji": "🇧🇹",
        "capital": "Thimphu",
        "continent": "Asia",
        "short_description": "The only carbon-negative country in the world, in the Himalayas.",
        "fact_1": "Bhutan is the world's only carbon-negative country.",
        "fact_2": "It measures success by Gross National Happiness instead of GDP.",
        "fact_3": "Television was introduced in Bhutan only in 1999.",
        "quiz_question": "What unique metric does Bhutan use instead of GDP?",
        "quiz_options": ["Gross National Happiness", "Life Satisfaction Index", "Wellness Score", "Peace Index"],
        "correct_answer": "Gross National Happiness",
        "map_coordinates": [27.5142, 90.4336]
    },
    {
        "country_name": "Brunei",
        "flag_emoji": "🇧🇳",
        "capital": "Bandar Seri Begawan",
        "continent": "Asia",
        "short_description": "A small, oil-rich sultanate on the island of Borneo.",
        "fact_1": "Brunei is one of the richest countries in the world per capita.",
        "fact_2": "Education and healthcare are completely free for all citizens.",
        "fact_3": "The Sultan's palace has 1,788 rooms, the world's largest residential palace.",
        "quiz_question": "How many rooms does the Sultan's palace have?",
        "quiz_options": ["500", "1,000", "1,788", "2,500"],
        "correct_answer": "1,788",
        "map_coordinates": [4.5353, 114.7277]
    },
    {
        "country_name": "Cambodia",
        "flag_emoji": "🇰🇭",
        "capital": "Phnom Penh",
        "continent": "Asia",
        "short_description": "Home to the ancient temple complex of Angkor Wat.",
        "fact_1": "Angkor Wat is the largest religious monument in the world.",
        "fact_2": "Cambodia's flag is the only one featuring a building (Angkor Wat).",
        "fact_3": "The Mekong River flows through Cambodia, vital for fishing and farming.",
        "quiz_question": "What is the largest religious monument in the world?",
        "quiz_options": ["Vatican", "Angkor Wat", "Taj Mahal", "Golden Temple"],
        "correct_answer": "Angkor Wat",
        "map_coordinates": [12.5657, 104.9910]
    },
    {
        "country_name": "China",
        "flag_emoji": "🇨🇳",
        "capital": "Beijing",
        "continent": "Asia",
        "short_description": "The world's most populous country with over 1.4 billion people.",
        "fact_1": "The Great Wall of China is over 21,000 km long.",
        "fact_2": "China has more high-speed rail than the rest of the world combined.",
        "fact_3": "The Yangtze is the longest river in Asia at 6,300 km.",
        "quiz_question": "How long is the Great Wall of China?",
        "quiz_options": ["5,000 km", "10,000 km", "21,000 km", "15,000 km"],
        "correct_answer": "21,000 km",
        "map_coordinates": [35.8617, 104.1954]
    },
    {
        "country_name": "Cyprus",
        "flag_emoji": "🇨🇾",
        "capital": "Nicosia",
        "continent": "Asia",
        "short_description": "An island nation in the Eastern Mediterranean, divided since 1974.",
        "fact_1": "Nicosia is the world's last divided capital city.",
        "fact_2": "Cyprus is the third-largest island in the Mediterranean.",
        "fact_3": "According to legend, Aphrodite was born on Cyprus.",
        "quiz_question": "What is unique about Nicosia among world capitals?",
        "quiz_options": ["Oldest", "Smallest", "Last divided capital", "Highest"],
        "correct_answer": "Last divided capital",
        "map_coordinates": [35.1264, 33.4299]
    },
    {
        "country_name": "Georgia",
        "flag_emoji": "🇬🇪",
        "capital": "Tbilisi",
        "continent": "Asia",
        "short_description": "A Caucasus nation considered the birthplace of wine.",
        "fact_1": "Georgia is believed to be where wine was first made 8,000 years ago.",
        "fact_2": "The Georgian alphabet is one of the world's 14 unique scripts.",
        "fact_3": "Georgia has diverse climates from subtropical to alpine.",
        "quiz_question": "How long ago was wine first made in Georgia?",
        "quiz_options": ["2,000 years", "4,000 years", "8,000 years", "1,000 years"],
        "correct_answer": "8,000 years",
        "map_coordinates": [42.3154, 43.3569]
    },
    {
        "country_name": "India",
        "flag_emoji": "🇮🇳",
        "capital": "New Delhi",
        "continent": "Asia",
        "short_description": "The world's largest democracy with over 1.4 billion people.",
        "fact_1": "India has 22 official languages and over 1,600 spoken languages.",
        "fact_2": "The Himalayas, world's highest mountains, form India's northern border.",
        "fact_3": "India is the birthplace of four major religions: Hinduism, Buddhism, Jainism, and Sikhism.",
        "quiz_question": "How many official languages does India have?",
        "quiz_options": ["10", "15", "22", "30"],
        "correct_answer": "22",
        "map_coordinates": [20.5937, 78.9629]
    },
    {
        "country_name": "Indonesia",
        "flag_emoji": "🇮🇩",
        "capital": "Jakarta",
        "continent": "Asia",
        "short_description": "The world's largest archipelago with over 17,000 islands.",
        "fact_1": "Indonesia has over 17,000 islands, with about 6,000 inhabited.",
        "fact_2": "It is the world's most populous Muslim-majority country.",
        "fact_3": "Krakatoa, one of the most famous volcanoes, is in Indonesia.",
        "quiz_question": "How many islands does Indonesia have?",
        "quiz_options": ["5,000", "10,000", "17,000+", "25,000"],
        "correct_answer": "17,000+",
        "map_coordinates": [-0.7893, 113.9213]
    },
    {
        "country_name": "Iran",
        "flag_emoji": "🇮🇷",
        "capital": "Tehran",
        "continent": "Asia",
        "short_description": "Ancient Persia, one of the world's oldest continuous civilizations.",
        "fact_1": "Iran was known as Persia until 1935.",
        "fact_2": "It has one of the world's largest natural gas reserves.",
        "fact_3": "The Persian Empire was once the largest empire in ancient history.",
        "quiz_question": "What was Iran known as until 1935?",
        "quiz_options": ["Mesopotamia", "Persia", "Babylon", "Arabia"],
        "correct_answer": "Persia",
        "map_coordinates": [32.4279, 53.6880]
    },
    {
        "country_name": "Iraq",
        "flag_emoji": "🇮🇶",
        "capital": "Baghdad",
        "continent": "Asia",
        "short_description": "Ancient Mesopotamia, the 'Cradle of Civilization'.",
        "fact_1": "Iraq is home to ancient Mesopotamia, where writing was invented.",
        "fact_2": "The Tigris and Euphrates rivers flow through Iraq.",
        "fact_3": "The ancient city of Babylon was located in present-day Iraq.",
        "quiz_question": "What was Iraq's region called in ancient times?",
        "quiz_options": ["Persia", "Mesopotamia", "Levant", "Arabia"],
        "correct_answer": "Mesopotamia",
        "map_coordinates": [33.2232, 43.6793]
    },
    {
        "country_name": "Israel",
        "flag_emoji": "🇮🇱",
        "capital": "Jerusalem",
        "continent": "Asia",
        "short_description": "A small Middle Eastern country holy to three major religions.",
        "fact_1": "The Dead Sea, the lowest point on Earth, borders Israel.",
        "fact_2": "Israel has more museums per capita than any other country.",
        "fact_3": "Hebrew was revived as a spoken language after being dormant for 2,000 years.",
        "quiz_question": "What is the lowest point on Earth's surface?",
        "quiz_options": ["Mariana Trench", "Dead Sea", "Death Valley", "Caspian Sea"],
        "correct_answer": "Dead Sea",
        "map_coordinates": [31.0461, 34.8516]
    },
    {
        "country_name": "Japan",
        "flag_emoji": "🇯🇵",
        "capital": "Tokyo",
        "continent": "Asia",
        "short_description": "An island nation known for technology, tradition, and Mount Fuji.",
        "fact_1": "Japan consists of 6,852 islands but four make up 97% of the area.",
        "fact_2": "Japan has the world's oldest company, founded in 578 AD.",
        "fact_3": "There are more vending machines in Japan than in almost any other country.",
        "quiz_question": "How many islands make up Japan?",
        "quiz_options": ["1,000", "3,000", "6,852", "10,000"],
        "correct_answer": "6,852",
        "map_coordinates": [36.2048, 138.2529]
    },
    {
        "country_name": "Jordan",
        "flag_emoji": "🇯🇴",
        "capital": "Amman",
        "continent": "Asia",
        "short_description": "Home to the ancient city of Petra, carved into rose-red cliffs.",
        "fact_1": "Petra, a UNESCO World Heritage Site, was carved from rock over 2,000 years ago.",
        "fact_2": "The Dead Sea's shore is the lowest land point on Earth at 430m below sea level.",
        "fact_3": "Jordan is one of the most water-scarce countries in the world.",
        "quiz_question": "What ancient city was carved from rock in Jordan?",
        "quiz_options": ["Jerash", "Petra", "Amman", "Aqaba"],
        "correct_answer": "Petra",
        "map_coordinates": [30.5852, 36.2384]
    },
    {
        "country_name": "Kazakhstan",
        "flag_emoji": "🇰🇿",
        "capital": "Astana",
        "continent": "Asia",
        "short_description": "The world's largest landlocked country located in Central Asia.",
        "fact_1": "Kazakhstan is the largest landlocked country in the world.",
        "fact_2": "The Baikonur Cosmodrome, world's first spaceport, is located here.",
        "fact_3": "It shares borders with Russia, China, Kyrgyzstan, Uzbekistan, and Turkmenistan.",
        "quiz_question": "Which country shares the longest border with Kazakhstan?",
        "quiz_options": ["China", "Russia", "Uzbekistan", "Kyrgyzstan"],
        "correct_answer": "Russia",
        "map_coordinates": [48.0196, 66.9237]
    },
    {
        "country_name": "Kuwait",
        "flag_emoji": "🇰🇼",
        "capital": "Kuwait City",
        "continent": "Asia",
        "short_description": "A small but oil-rich nation on the Persian Gulf.",
        "fact_1": "Kuwait has about 6% of the world's oil reserves.",
        "fact_2": "Kuwait has no natural permanent rivers or lakes.",
        "fact_3": "The Kuwaiti dinar is the world's highest-valued currency unit.",
        "quiz_question": "What currency holds the highest value per unit?",
        "quiz_options": ["US Dollar", "Euro", "British Pound", "Kuwaiti Dinar"],
        "correct_answer": "Kuwaiti Dinar",
        "map_coordinates": [29.3117, 47.4818]
    },
    {
        "country_name": "Kyrgyzstan",
        "flag_emoji": "🇰🇬",
        "capital": "Bishkek",
        "continent": "Asia",
        "short_description": "A mountainous Central Asian country with nomadic traditions.",
        "fact_1": "About 94% of Kyrgyzstan is mountainous.",
        "fact_2": "Issyk-Kul is the world's second-largest alpine lake.",
        "fact_3": "The traditional sport of kok-boru involves horseback players and a goat carcass.",
        "quiz_question": "What percentage of Kyrgyzstan is mountainous?",
        "quiz_options": ["50%", "70%", "94%", "80%"],
        "correct_answer": "94%",
        "map_coordinates": [41.2044, 74.7661]
    },
    {
        "country_name": "Laos",
        "flag_emoji": "🇱🇦",
        "capital": "Vientiane",
        "continent": "Asia",
        "short_description": "A landlocked Southeast Asian country known for Buddhist monasteries.",
        "fact_1": "Laos is the most heavily bombed country in history per capita.",
        "fact_2": "The Plain of Jars contains thousands of mysterious stone jars.",
        "fact_3": "Laos is the only landlocked country in Southeast Asia.",
        "quiz_question": "What is Laos's geographical distinction in Southeast Asia?",
        "quiz_options": ["Largest", "Smallest", "Only landlocked", "Most islands"],
        "correct_answer": "Only landlocked",
        "map_coordinates": [19.8563, 102.4955]
    },
    {
        "country_name": "Lebanon",
        "flag_emoji": "🇱🇧",
        "capital": "Beirut",
        "continent": "Asia",
        "short_description": "A small Mediterranean country with ancient Phoenician history.",
        "fact_1": "Lebanon is home to the world's oldest continuously inhabited city, Byblos.",
        "fact_2": "The Cedar of Lebanon is the national symbol and appears on the flag.",
        "fact_3": "Lebanon has 18 recognized religious communities.",
        "quiz_question": "Which city in Lebanon is considered the oldest continuously inhabited city?",
        "quiz_options": ["Beirut", "Tripoli", "Byblos", "Sidon"],
        "correct_answer": "Byblos",
        "map_coordinates": [33.8547, 35.8623]
    },
    {
        "country_name": "Malaysia",
        "flag_emoji": "🇲🇾",
        "capital": "Kuala Lumpur",
        "continent": "Asia",
        "short_description": "A Southeast Asian nation split between a peninsula and Borneo.",
        "fact_1": "Malaysia is divided into two regions separated by the South China Sea.",
        "fact_2": "The Petronas Twin Towers were the world's tallest buildings from 1998-2004.",
        "fact_3": "Malaysia is one of the 17 megadiverse countries in the world.",
        "quiz_question": "What sea separates Peninsular Malaysia from East Malaysia?",
        "quiz_options": ["Andaman Sea", "Java Sea", "South China Sea", "Sulu Sea"],
        "correct_answer": "South China Sea",
        "map_coordinates": [4.2105, 101.9758]
    },
    {
        "country_name": "Maldives",
        "flag_emoji": "🇲🇻",
        "capital": "Malé",
        "continent": "Asia",
        "short_description": "The world's lowest-lying country, an island paradise in the Indian Ocean.",
        "fact_1": "The Maldives is the world's lowest country with an average elevation of 1.5 meters.",
        "fact_2": "It consists of about 1,200 coral islands grouped into 26 atolls.",
        "fact_3": "The Maldives could be underwater by 2100 due to rising sea levels.",
        "quiz_question": "What is the average elevation of the Maldives?",
        "quiz_options": ["5 meters", "3 meters", "1.5 meters", "10 meters"],
        "correct_answer": "1.5 meters",
        "map_coordinates": [3.2028, 73.2207]
    },
    {
        "country_name": "Mongolia",
        "flag_emoji": "🇲🇳",
        "capital": "Ulaanbaatar",
        "continent": "Asia",
        "short_description": "The world's least densely populated country, land of Genghis Khan.",
        "fact_1": "Mongolia has the lowest population density in the world.",
        "fact_2": "Genghis Khan founded the largest contiguous land empire in history.",
        "fact_3": "About 30% of Mongolians are still nomadic or semi-nomadic.",
        "quiz_question": "What distinction does Mongolia hold regarding population?",
        "quiz_options": ["Most populous", "Fastest growing", "Least densely populated", "Oldest population"],
        "correct_answer": "Least densely populated",
        "map_coordinates": [46.8625, 103.8467]
    },
    {
        "country_name": "Myanmar",
        "flag_emoji": "🇲🇲",
        "capital": "Naypyidaw",
        "continent": "Asia",
        "short_description": "A Southeast Asian country formerly known as Burma.",
        "fact_1": "Myanmar was called Burma until 1989.",
        "fact_2": "Bagan has over 2,000 ancient Buddhist temples and pagodas.",
        "fact_3": "Myanmar is the world's second-largest producer of opium.",
        "quiz_question": "What was Myanmar's former name?",
        "quiz_options": ["Siam", "Burma", "Ceylon", "Indochina"],
        "correct_answer": "Burma",
        "map_coordinates": [21.9162, 95.9560]
    },
    {
        "country_name": "Nepal",
        "flag_emoji": "🇳🇵",
        "capital": "Kathmandu",
        "continent": "Asia",
        "short_description": "Home to Mount Everest, the world's highest peak.",
        "fact_1": "Nepal is home to 8 of the world's 14 highest peaks.",
        "fact_2": "Nepal's flag is the only non-quadrilateral national flag.",
        "fact_3": "Lumbini in Nepal is the birthplace of Buddha.",
        "quiz_question": "What is unique about Nepal's national flag?",
        "quiz_options": ["Oldest flag", "Largest flag", "Only non-rectangular", "Only circular"],
        "correct_answer": "Only non-rectangular",
        "map_coordinates": [28.3949, 84.1240]
    },
    {
        "country_name": "North Korea",
        "flag_emoji": "🇰🇵",
        "capital": "Pyongyang",
        "continent": "Asia",
        "short_description": "One of the world's most isolated countries on the Korean Peninsula.",
        "fact_1": "North Korea is one of the most isolated countries in the world.",
        "fact_2": "Mount Paektu is considered sacred in Korean culture.",
        "fact_3": "The DMZ between North and South Korea is one of the most fortified borders.",
        "quiz_question": "What is the DMZ?",
        "quiz_options": ["River", "Mountain", "Demilitarized Zone", "City"],
        "correct_answer": "Demilitarized Zone",
        "map_coordinates": [40.3399, 127.5101]
    },
    {
        "country_name": "Oman",
        "flag_emoji": "🇴🇲",
        "capital": "Muscat",
        "continent": "Asia",
        "short_description": "An Arab country on the southeastern coast of the Arabian Peninsula.",
        "fact_1": "Oman was a major maritime power and controlled Zanzibar until 1856.",
        "fact_2": "Frankincense has been harvested in Oman for over 5,000 years.",
        "fact_3": "The Rub' al Khali (Empty Quarter), the world's largest sand desert, extends into Oman.",
        "quiz_question": "What precious resin has been harvested in Oman for 5,000 years?",
        "quiz_options": ["Myrrh", "Amber", "Frankincense", "Copal"],
        "correct_answer": "Frankincense",
        "map_coordinates": [21.4735, 55.9754]
    },
    {
        "country_name": "Pakistan",
        "flag_emoji": "🇵🇰",
        "capital": "Islamabad",
        "continent": "Asia",
        "short_description": "Home to K2, the world's second-highest mountain.",
        "fact_1": "K2 is the world's second-highest mountain and more dangerous than Everest.",
        "fact_2": "The Indus Valley Civilization, one of the oldest, was in Pakistan.",
        "fact_3": "Pakistan has the world's largest irrigation system.",
        "quiz_question": "What is the world's second-highest mountain located in Pakistan?",
        "quiz_options": ["Nanga Parbat", "K2", "Broad Peak", "Gasherbrum"],
        "correct_answer": "K2",
        "map_coordinates": [30.3753, 69.3451]
    },
    {
        "country_name": "Palestine",
        "flag_emoji": "🇵🇸",
        "capital": "Ramallah",
        "continent": "Asia",
        "short_description": "A territory in the Middle East with disputed sovereignty.",
        "fact_1": "Palestine includes the West Bank and Gaza Strip.",
        "fact_2": "Bethlehem, the birthplace of Jesus, is in Palestine.",
        "fact_3": "The Dead Sea borders Palestinian territory.",
        "quiz_question": "Which significant religious site is located in Palestine?",
        "quiz_options": ["Mecca", "Bethlehem", "Vatican", "Bodh Gaya"],
        "correct_answer": "Bethlehem",
        "map_coordinates": [31.9522, 35.2332]
    },
    {
        "country_name": "Philippines",
        "flag_emoji": "🇵🇭",
        "capital": "Manila",
        "continent": "Asia",
        "short_description": "An archipelago of over 7,000 islands in Southeast Asia.",
        "fact_1": "The Philippines has over 7,641 islands.",
        "fact_2": "It is the only Christian-majority nation in Asia.",
        "fact_3": "The Philippine Eagle is one of the world's largest and rarest eagles.",
        "quiz_question": "How many islands does the Philippines have?",
        "quiz_options": ["1,000", "5,000", "7,641", "10,000"],
        "correct_answer": "7,641",
        "map_coordinates": [12.8797, 121.7740]
    },
    {
        "country_name": "Qatar",
        "flag_emoji": "🇶🇦",
        "capital": "Doha",
        "continent": "Asia",
        "short_description": "A wealthy peninsula nation with the world's highest GDP per capita.",
        "fact_1": "Qatar has one of the world's highest GDP per capita.",
        "fact_2": "Qatar hosted the 2022 FIFA World Cup.",
        "fact_3": "Natural gas makes up about 70% of government revenue.",
        "quiz_question": "What major sporting event did Qatar host in 2022?",
        "quiz_options": ["Olympics", "FIFA World Cup", "Asian Games", "Cricket World Cup"],
        "correct_answer": "FIFA World Cup",
        "map_coordinates": [25.3548, 51.1839]
    },
    {
        "country_name": "Russia",
        "flag_emoji": "🇷🇺",
        "capital": "Moscow",
        "continent": "Europe",
        "short_description": "The world's largest country, spanning Europe and Asia.",
        "fact_1": "Russia spans 11 time zones, more than any other country.",
        "fact_2": "Lake Baikal contains about 20% of the world's unfrozen fresh water.",
        "fact_3": "Russia is home to the Trans-Siberian Railway, the longest railway in the world.",
        "quiz_question": "How many time zones does Russia span?",
        "quiz_options": ["5", "8", "11", "15"],
        "correct_answer": "11",
        "map_coordinates": [61.5240, 105.3188]
    },
    {
        "country_name": "Saudi Arabia",
        "flag_emoji": "🇸🇦",
        "capital": "Riyadh",
        "continent": "Asia",
        "short_description": "Home to Islam's two holiest cities, Mecca and Medina.",
        "fact_1": "Saudi Arabia has the world's largest continuous sand desert, the Rub' al Khali.",
        "fact_2": "Mecca is visited by millions of Muslims during Hajj pilgrimage.",
        "fact_3": "Saudi Arabia is the world's largest oil exporter.",
        "quiz_question": "What is the world's largest continuous sand desert?",
        "quiz_options": ["Sahara", "Gobi", "Rub' al Khali", "Kalahari"],
        "correct_answer": "Rub' al Khali",
        "map_coordinates": [23.8859, 45.0792]
    },
    {
        "country_name": "Singapore",
        "flag_emoji": "🇸🇬",
        "capital": "Singapore",
        "continent": "Asia",
        "short_description": "A city-state and one of the world's most prosperous countries.",
        "fact_1": "Singapore is one of only three city-states in the world.",
        "fact_2": "Singapore's Changi Airport has been named the world's best multiple times.",
        "fact_3": "Chewing gum is banned in Singapore to keep the city clean.",
        "quiz_question": "What is banned in Singapore to maintain cleanliness?",
        "quiz_options": ["Plastic bags", "Chewing gum", "Cigarettes", "Candy"],
        "correct_answer": "Chewing gum",
        "map_coordinates": [1.3521, 103.8198]
    },
    {
        "country_name": "South Korea",
        "flag_emoji": "🇰🇷",
        "capital": "Seoul",
        "continent": "Asia",
        "short_description": "A high-tech nation on the southern half of the Korean Peninsula.",
        "fact_1": "South Korea has the world's fastest average internet speed.",
        "fact_2": "K-pop and Korean dramas have become global cultural phenomena.",
        "fact_3": "Seoul is one of the world's largest metropolitan areas.",
        "quiz_question": "What is South Korea famous for having the fastest of in the world?",
        "quiz_options": ["Trains", "Internet", "Cars", "Planes"],
        "correct_answer": "Internet",
        "map_coordinates": [35.9078, 127.7669]
    },
    {
        "country_name": "Sri Lanka",
        "flag_emoji": "🇱🇰",
        "capital": "Sri Jayawardenepura Kotte",
        "continent": "Asia",
        "short_description": "An island nation known as the 'Pearl of the Indian Ocean'.",
        "fact_1": "Sri Lanka is the world's fourth-largest tea producer.",
        "fact_2": "It is called the 'Pearl of the Indian Ocean' for its natural beauty.",
        "fact_3": "Sri Lanka has one of the highest literacy rates in South Asia.",
        "quiz_question": "What is Sri Lanka's nickname?",
        "quiz_options": ["Spice Island", "Pearl of the Indian Ocean", "Garden of Eden", "Emerald Isle"],
        "correct_answer": "Pearl of the Indian Ocean",
        "map_coordinates": [7.8731, 80.7718]
    },
    {
        "country_name": "Syria",
        "flag_emoji": "🇸🇾",
        "capital": "Damascus",
        "continent": "Asia",
        "short_description": "Home to Damascus, one of the oldest continuously inhabited cities.",
        "fact_1": "Damascus is often cited as the oldest continuously inhabited city.",
        "fact_2": "Syria was part of the ancient Fertile Crescent civilization.",
        "fact_3": "Aleppo's ancient souq was one of the longest covered markets in the world.",
        "quiz_question": "What is Damascus known as?",
        "quiz_options": ["Newest capital", "Oldest continuously inhabited city", "Largest city", "Highest capital"],
        "correct_answer": "Oldest continuously inhabited city",
        "map_coordinates": [34.8021, 38.9968]
    },
    {
        "country_name": "Tajikistan",
        "flag_emoji": "🇹🇯",
        "capital": "Dushanbe",
        "continent": "Asia",
        "short_description": "A mountainous Central Asian country with 93% mountain coverage.",
        "fact_1": "About 93% of Tajikistan is mountainous.",
        "fact_2": "Ismoil Somoni Peak at 7,495m is the highest in the former Soviet Union.",
        "fact_3": "The ancient Silk Road passed through Tajikistan.",
        "quiz_question": "What percentage of Tajikistan is mountainous?",
        "quiz_options": ["70%", "80%", "93%", "60%"],
        "correct_answer": "93%",
        "map_coordinates": [38.8610, 71.2761]
    },
    {
        "country_name": "Thailand",
        "flag_emoji": "🇹🇭",
        "capital": "Bangkok",
        "continent": "Asia",
        "short_description": "The only Southeast Asian country never colonized by Europeans.",
        "fact_1": "Thailand is the only Southeast Asian country never colonized by Europeans.",
        "fact_2": "Thailand means 'Land of the Free'.",
        "fact_3": "Bangkok's full ceremonial name is 168 characters long, the longest city name.",
        "quiz_question": "What does 'Thailand' mean?",
        "quiz_options": ["Land of Smiles", "Land of the Free", "Golden Land", "Land of Temples"],
        "correct_answer": "Land of the Free",
        "map_coordinates": [15.8700, 100.9925]
    },
    {
        "country_name": "Timor-Leste",
        "flag_emoji": "🇹🇱",
        "capital": "Dili",
        "continent": "Asia",
        "short_description": "One of the world's newest nations, independent since 2002.",
        "fact_1": "Timor-Leste (East Timor) gained independence in 2002.",
        "fact_2": "It is the only Asian country located entirely in the Southern Hemisphere.",
        "fact_3": "Portuguese and Tetum are the official languages.",
        "quiz_question": "When did Timor-Leste gain independence?",
        "quiz_options": ["1999", "2002", "2005", "2010"],
        "correct_answer": "2002",
        "map_coordinates": [-8.8742, 125.7275]
    },
    {
        "country_name": "Turkey",
        "flag_emoji": "🇹🇷",
        "capital": "Ankara",
        "continent": "Asia",
        "short_description": "A transcontinental country bridging Europe and Asia.",
        "fact_1": "Istanbul is the only city in the world on two continents.",
        "fact_2": "Turkey has the most UNESCO World Heritage Sites in Asia.",
        "fact_3": "Turkish coffee and tea culture are central to daily life.",
        "quiz_question": "What is unique about Istanbul's geographic position?",
        "quiz_options": ["Highest city", "Largest port", "On two continents", "Most ancient"],
        "correct_answer": "On two continents",
        "map_coordinates": [38.9637, 35.2433]
    },
    {
        "country_name": "Turkmenistan",
        "flag_emoji": "🇹🇲",
        "capital": "Ashgabat",
        "continent": "Asia",
        "short_description": "A Central Asian country with the world's fourth-largest natural gas reserves.",
        "fact_1": "The Darvaza gas crater has been burning since 1971, called 'Door to Hell'.",
        "fact_2": "Turkmenistan has the world's fourth-largest natural gas reserves.",
        "fact_3": "About 80% of the country is covered by the Karakum Desert.",
        "quiz_question": "What is the 'Door to Hell' in Turkmenistan?",
        "quiz_options": ["Volcano", "Gas crater", "Cave", "Mine"],
        "correct_answer": "Gas crater",
        "map_coordinates": [38.9697, 59.5563]
    },
    {
        "country_name": "United Arab Emirates",
        "flag_emoji": "🇦🇪",
        "capital": "Abu Dhabi",
        "continent": "Asia",
        "short_description": "A federation of seven emirates including Dubai and Abu Dhabi.",
        "fact_1": "The Burj Khalifa in Dubai is the world's tallest building at 828 meters.",
        "fact_2": "The UAE was formed from seven emirates in 1971.",
        "fact_3": "Dubai has the world's largest artificial islands.",
        "quiz_question": "How tall is the Burj Khalifa?",
        "quiz_options": ["600m", "728m", "828m", "900m"],
        "correct_answer": "828m",
        "map_coordinates": [23.4241, 53.8478]
    },
    {
        "country_name": "Uzbekistan",
        "flag_emoji": "🇺🇿",
        "capital": "Tashkent",
        "continent": "Asia",
        "short_description": "A doubly landlocked Central Asian country on the Silk Road.",
        "fact_1": "Uzbekistan is one of only two doubly landlocked countries in the world.",
        "fact_2": "Samarkand was a key city on the ancient Silk Road.",
        "fact_3": "The Aral Sea has shrunk by 90% due to Soviet irrigation projects.",
        "quiz_question": "What does 'doubly landlocked' mean?",
        "quiz_options": ["No rivers", "Surrounded only by landlocked countries", "Desert country", "Mountain country"],
        "correct_answer": "Surrounded only by landlocked countries",
        "map_coordinates": [41.3775, 64.5853]
    },
    {
        "country_name": "Vietnam",
        "flag_emoji": "🇻🇳",
        "capital": "Hanoi",
        "continent": "Asia",
        "short_description": "A Southeast Asian country known for Ha Long Bay and rich history.",
        "fact_1": "Ha Long Bay has about 1,600 limestone islands and islets.",
        "fact_2": "Vietnam is the world's second-largest coffee exporter.",
        "fact_3": "The Mekong Delta is called the 'Rice Bowl of Vietnam'.",
        "quiz_question": "What is Vietnam's rank in world coffee production?",
        "quiz_options": ["First", "Second", "Third", "Fifth"],
        "correct_answer": "Second",
        "map_coordinates": [14.0583, 108.2772]
    },
    {
        "country_name": "Yemen",
        "flag_emoji": "🇾🇪",
        "capital": "Sana'a",
        "continent": "Asia",
        "short_description": "An Arabian Peninsula country with ancient skyscrapers made of mud.",
        "fact_1": "Sana'a has been continuously inhabited for over 2,500 years.",
        "fact_2": "Shibam has mud-brick skyscrapers, called 'Manhattan of the Desert'.",
        "fact_3": "Socotra Island has plants found nowhere else on Earth.",
        "quiz_question": "What is Shibam nicknamed for its tall mud buildings?",
        "quiz_options": ["Tower Town", "Manhattan of the Desert", "Mud City", "Sky Village"],
        "correct_answer": "Manhattan of the Desert",
        "map_coordinates": [15.5527, 48.5164]
    },

    // ============ EUROPE (44 Countries) ============
    {
        "country_name": "Albania",
        "flag_emoji": "🇦🇱",
        "capital": "Tirana",
        "continent": "Europe",
        "short_description": "A Balkan country with a coastline on both the Adriatic and Ionian Seas.",
        "fact_1": "Albania has over 750,000 bunkers built during communist rule.",
        "fact_2": "Mother Teresa was of Albanian origin.",
        "fact_3": "Albanians call their country 'Shqipëria', meaning 'Land of Eagles'.",
        "quiz_question": "What does Albania's native name 'Shqipëria' mean?",
        "quiz_options": ["Land of Mountains", "Land of Eagles", "Land of Heroes", "Land of Sun"],
        "correct_answer": "Land of Eagles",
        "map_coordinates": [41.1533, 20.1683]
    },
    {
        "country_name": "Andorra",
        "flag_emoji": "🇦🇩",
        "capital": "Andorra la Vella",
        "continent": "Europe",
        "short_description": "A tiny principality in the Pyrenees mountains between France and Spain.",
        "fact_1": "Andorra la Vella is the highest capital city in Europe.",
        "fact_2": "Andorra has no airport; visitors arrive through Spain or France.",
        "fact_3": "Tourism, especially skiing, accounts for 80% of GDP.",
        "quiz_question": "What is special about Andorra la Vella among European capitals?",
        "quiz_options": ["Oldest", "Smallest", "Highest", "Coldest"],
        "correct_answer": "Highest",
        "map_coordinates": [42.5063, 1.5218]
    },
    {
        "country_name": "Austria",
        "flag_emoji": "🇦🇹",
        "capital": "Vienna",
        "continent": "Europe",
        "short_description": "A landlocked Alpine country known for classical music and skiing.",
        "fact_1": "Vienna has been voted the world's most livable city multiple times.",
        "fact_2": "Austria has produced famous composers like Mozart, Haydn, and Schubert.",
        "fact_3": "The Alps cover about 60% of Austria's territory.",
        "quiz_question": "What percentage of Austria is covered by the Alps?",
        "quiz_options": ["30%", "45%", "60%", "80%"],
        "correct_answer": "60%",
        "map_coordinates": [47.5162, 14.5501]
    },
    {
        "country_name": "Belarus",
        "flag_emoji": "🇧🇾",
        "capital": "Minsk",
        "continent": "Europe",
        "short_description": "A landlocked Eastern European country between Russia and Poland.",
        "fact_1": "Belarus has Europe's largest remaining primeval forest, Białowieża.",
        "fact_2": "Minsk was almost completely destroyed in World War II.",
        "fact_3": "European bison were saved from extinction in Belarusian forests.",
        "quiz_question": "What rare animal was saved from extinction in Belarus?",
        "quiz_options": ["Brown
