/**
 * Unity Atlas - Country Data
 * Complete database of 197 countries with metadata
 */

const COUNTRIES_DATA = [
    // ==================== ASIA (49 countries) ====================
    {
        code: "IND",
        name: "India",
        official_name: "Republic of India",
        flag: "🇮🇳",
        capital: "New Delhi",
        region: "asia",
        subregion: "South Asia",
        population: 1428627663,
        area_km2: 3287263,
        gdp_usd: 3732224000000,
        currency: "Indian Rupee (INR)",
        languages: ["Hindi", "English"],
        groupings: ["g20", "brics", "saarc", "quad", "nam", "commonwealth", "sco"],
        neighbors: ["PAK", "CHN", "NPL", "BTN", "BGD", "MMR"],
        un_member: true,
        data_available: true
    },
    {
        code: "CHN",
        name: "China",
        official_name: "People's Republic of China",
        flag: "🇨🇳",
        capital: "Beijing",
        region: "asia",
        subregion: "East Asia",
        population: 1425887337,
        area_km2: 9596961,
        gdp_usd: 18321000000000,
        currency: "Yuan Renminbi (CNY)",
        languages: ["Mandarin Chinese"],
        groupings: ["g20", "brics", "sco", "apec"],
        neighbors: ["RUS", "MNG", "PRK", "VNM", "LAO", "MMR", "IND", "BTN", "NPL", "PAK", "AFG", "TJK", "KGZ", "KAZ"],
        un_member: true,
        unsc_permanent: true,
        data_available: true
    },
    {
        code: "JPN",
        name: "Japan",
        official_name: "Japan",
        flag: "🇯🇵",
        capital: "Tokyo",
        region: "asia",
        subregion: "East Asia",
        population: 123753041,
        area_km2: 377975,
        gdp_usd: 4230862000000,
        currency: "Yen (JPY)",
        languages: ["Japanese"],
        groupings: ["g7", "g20", "quad", "apec", "oecd"],
        neighbors: [],
        un_member: true,
        data_available: true
    },
    {
        code: "KOR",
        name: "South Korea",
        official_name: "Republic of Korea",
        flag: "🇰🇷",
        capital: "Seoul",
        region: "asia",
        subregion: "East Asia",
        population: 51784059,
        area_km2: 100210,
        gdp_usd: 1673916000000,
        currency: "Won (KRW)",
        languages: ["Korean"],
        groupings: ["g20", "apec", "oecd"],
        neighbors: ["PRK"],
        un_member: true,
        data_available: true
    },
    {
        code: "PRK",
        name: "North Korea",
        official_name: "Democratic People's Republic of Korea",
        flag: "🇰🇵",
        capital: "Pyongyang",
        region: "asia",
        subregion: "East Asia",
        population: 26069416,
        area_km2: 120538,
        gdp_usd: 18000000000,
        currency: "Won (KPW)",
        languages: ["Korean"],
        groupings: [],
        neighbors: ["KOR", "CHN", "RUS"],
        un_member: true,
        data_available: false
    },
    {
        code: "PAK",
        name: "Pakistan",
        official_name: "Islamic Republic of Pakistan",
        flag: "🇵🇰",
        capital: "Islamabad",
        region: "asia",
        subregion: "South Asia",
        population: 240485658,
        area_km2: 881913,
        gdp_usd: 376493000000,
        currency: "Pakistani Rupee (PKR)",
        languages: ["Urdu", "English"],
        groupings: ["saarc", "sco", "oic", "d8"],
        neighbors: ["IND", "CHN", "AFG", "IRN"],
        un_member: true,
        data_available: true
    },
    {
        code: "BGD",
        name: "Bangladesh",
        official_name: "People's Republic of Bangladesh",
        flag: "🇧🇩",
        capital: "Dhaka",
        region: "asia",
        subregion: "South Asia",
        population: 172954319,
        area_km2: 147570,
        gdp_usd: 460201000000,
        currency: "Taka (BDT)",
        languages: ["Bengali"],
        groupings: ["saarc", "bimstec", "d8", "oic"],
        neighbors: ["IND", "MMR"],
        un_member: true,
        data_available: true
    },
    {
        code: "IDN",
        name: "Indonesia",
        official_name: "Republic of Indonesia",
        flag: "🇮🇩",
        capital: "Jakarta",
        region: "asia",
        subregion: "Southeast Asia",
        population: 277534122,
        area_km2: 1904569,
        gdp_usd: 1417387000000,
        currency: "Rupiah (IDR)",
        languages: ["Indonesian"],
        groupings: ["g20", "asean", "apec", "oic", "opec"],
        neighbors: ["MYS", "PNG", "TLS"],
        un_member: true,
        data_available: true
    },
    {
        code: "VNM",
        name: "Vietnam",
        official_name: "Socialist Republic of Vietnam",
        flag: "🇻🇳",
        capital: "Hanoi",
        region: "asia",
        subregion: "Southeast Asia",
        population: 98858950,
        area_km2: 331212,
        gdp_usd: 449094000000,
        currency: "Dong (VND)",
        languages: ["Vietnamese"],
        groupings: ["asean", "apec"],
        neighbors: ["CHN", "LAO", "KHM"],
        un_member: true,
        data_available: true
    },
    {
        code: "THA",
        name: "Thailand",
        official_name: "Kingdom of Thailand",
        flag: "🇹🇭",
        capital: "Bangkok",
        region: "asia",
        subregion: "Southeast Asia",
        population: 71801279,
        area_km2: 513120,
        gdp_usd: 534779000000,
        currency: "Baht (THB)",
        languages: ["Thai"],
        groupings: ["asean", "apec", "bimstec"],
        neighbors: ["MMR", "LAO", "KHM", "MYS"],
        un_member: true,
        data_available: true
    },
    {
        code: "MYS",
        name: "Malaysia",
        official_name: "Malaysia",
        flag: "🇲🇾",
        capital: "Kuala Lumpur",
        region: "asia",
        subregion: "Southeast Asia",
        population: 34308525,
        area_km2: 330803,
        gdp_usd: 407921000000,
        currency: "Ringgit (MYR)",
        languages: ["Malay", "English"],
        groupings: ["asean", "apec", "oic", "commonwealth", "d8"],
        neighbors: ["THA", "IDN", "BRN", "SGP"],
        un_member: true,
        data_available: true
    },
    {
        code: "SGP",
        name: "Singapore",
        official_name: "Republic of Singapore",
        flag: "🇸🇬",
        capital: "Singapore",
        region: "asia",
        subregion: "Southeast Asia",
        population: 5637022,
        area_km2: 733,
        gdp_usd: 515548000000,
        currency: "Singapore Dollar (SGD)",
        languages: ["English", "Mandarin", "Malay", "Tamil"],
        groupings: ["asean", "apec", "commonwealth"],
        neighbors: ["MYS"],
        un_member: true,
        data_available: true
    },
    {
        code: "PHL",
        name: "Philippines",
        official_name: "Republic of the Philippines",
        flag: "🇵🇭",
        capital: "Manila",
        region: "asia",
        subregion: "Southeast Asia",
        population: 117337368,
        area_km2: 300000,
        gdp_usd: 435675000000,
        currency: "Peso (PHP)",
        languages: ["Filipino", "English"],
        groupings: ["asean", "apec"],
        neighbors: [],
        un_member: true,
        data_available: true
    },
    {
        code: "MMR",
        name: "Myanmar",
        official_name: "Republic of the Union of Myanmar",
        flag: "🇲🇲",
        capital: "Naypyidaw",
        region: "asia",
        subregion: "Southeast Asia",
        population: 54577997,
        area_km2: 676578,
        gdp_usd: 59445000000,
        currency: "Kyat (MMK)",
        languages: ["Burmese"],
        groupings: ["asean", "bimstec"],
        neighbors: ["IND", "BGD", "CHN", "LAO", "THA"],
        un_member: true,
        data_available: true
    },
    {
        code: "NPL",
        name: "Nepal",
        official_name: "Federal Democratic Republic of Nepal",
        flag: "🇳🇵",
        capital: "Kathmandu",
        region: "asia",
        subregion: "South Asia",
        population: 30896590,
        area_km2: 147181,
        gdp_usd: 40828000000,
        currency: "Nepalese Rupee (NPR)",
        languages: ["Nepali"],
        groupings: ["saarc", "bimstec"],
        neighbors: ["IND", "CHN"],
        un_member: true,
        data_available: true
    },
    {
        code: "LKA",
        name: "Sri Lanka",
        official_name: "Democratic Socialist Republic of Sri Lanka",
        flag: "🇱🇰",
        capital: "Sri Jayawardenepura Kotte",
        region: "asia",
        subregion: "South Asia",
        population: 21893579,
        area_km2: 65610,
        gdp_usd: 74403000000,
        currency: "Sri Lankan Rupee (LKR)",
        languages: ["Sinhala", "Tamil"],
        groupings: ["saarc", "bimstec", "commonwealth"],
        neighbors: [],
        un_member: true,
        data_available: true
    },
    {
        code: "BTN",
        name: "Bhutan",
        official_name: "Kingdom of Bhutan",
        flag: "🇧🇹",
        capital: "Thimphu",
        region: "asia",
        subregion: "South Asia",
        population: 787424,
        area_km2: 38394,
        gdp_usd: 2707000000,
        currency: "Ngultrum (BTN)",
        languages: ["Dzongkha"],
        groupings: ["saarc", "bimstec"],
        neighbors: ["IND", "CHN"],
        un_member: true,
        data_available: true
    },
    {
        code: "MDV",
        name: "Maldives",
        official_name: "Republic of Maldives",
        flag: "🇲🇻",
        capital: "Malé",
        region: "asia",
        subregion: "South Asia",
        population: 521021,
        area_km2: 300,
        gdp_usd: 6217000000,
        currency: "Rufiyaa (MVR)",
        languages: ["Dhivehi"],
        groupings: ["saarc", "oic", "commonwealth"],
        neighbors: [],
        un_member: true,
        data_available: true
    },
    {
        code: "AFG",
        name: "Afghanistan",
        official_name: "Islamic Emirate of Afghanistan",
        flag: "🇦🇫",
        capital: "Kabul",
        region: "asia",
        subregion: "South Asia",
        population: 42239854,
        area_km2: 652230,
        gdp_usd: 14266000000,
        currency: "Afghani (AFN)",
        languages: ["Pashto", "Dari"],
        groupings: ["saarc", "oic"],
        neighbors: ["PAK", "IRN", "TKM", "UZB", "TJK", "CHN"],
        un_member: true,
        data_available: true
    },
    {
        code: "IRN",
        name: "Iran",
        official_name: "Islamic Republic of Iran",
        flag: "🇮🇷",
        capital: "Tehran",
        region: "asia",
        subregion: "Western Asia",
        population: 89172767,
        area_km2: 1648195,
        gdp_usd: 413493000000,
        currency: "Rial (IRR)",
        languages: ["Persian"],
        groupings: ["opec", "oic", "sco", "brics"],
        neighbors: ["IRQ", "TUR", "ARM", "AZE", "TKM", "AFG", "PAK"],
        un_member: true,
        data_available: true
    },
    {
        code: "IRQ",
        name: "Iraq",
        official_name: "Republic of Iraq",
        flag: "🇮🇶",
        capital: "Baghdad",
        region: "asia",
        subregion: "Western Asia",
        population: 45504560,
        area_km2: 438317,
        gdp_usd: 270545000000,
        currency: "Dinar (IQD)",
        languages: ["Arabic", "Kurdish"],
        groupings: ["opec", "oic", "arab_league"],
        neighbors: ["TUR", "SYR", "JOR", "SAU", "KWT", "IRN"],
        un_member: true,
        data_available: true
    },
    {
        code: "SAU",
        name: "Saudi Arabia",
        official_name: "Kingdom of Saudi Arabia",
        flag: "🇸🇦",
        capital: "Riyadh",
        region: "asia",
        subregion: "Western Asia",
        population: 36947025,
        area_km2: 2149690,
        gdp_usd: 1108148000000,
        currency: "Riyal (SAR)",
        languages: ["Arabic"],
        groupings: ["g20", "opec", "oic", "gcc", "arab_league"],
        neighbors: ["JOR", "IRQ", "KWT", "QAT", "ARE", "OMN", "YEM"],
        un_member: true,
        data_available: true
    },
    {
        code: "ARE",
        name: "United Arab Emirates",
        official_name: "United Arab Emirates",
        flag: "🇦🇪",
        capital: "Abu Dhabi",
        region: "asia",
        subregion: "Western Asia",
        population: 9516871,
        area_km2: 83600,
        gdp_usd: 504172000000,
        currency: "Dirham (AED)",
        languages: ["Arabic"],
        groupings: ["opec", "oic", "gcc", "arab_league", "brics"],
        neighbors: ["SAU", "OMN"],
        un_member: true,
        data_available: true
    },
    {
        code: "ISR",
        name: "Israel",
        official_name: "State of Israel",
        flag: "🇮🇱",
        capital: "Jerusalem",
        region: "asia",
        subregion: "Western Asia",
        population: 9038309,
        area_km2: 20770,
        gdp_usd: 564739000000,
        currency: "Shekel (ILS)",
        languages: ["Hebrew", "Arabic"],
        groupings: ["oecd"],
        neighbors: ["LBN", "SYR", "JOR", "EGY", "PSE"],
        un_member: true,
        data_available: true
    },
    {
        code: "TUR",
        name: "Turkey",
        official_name: "Republic of Türkiye",
        flag: "🇹🇷",
        capital: "Ankara",
        region: "asia",
        subregion: "Western Asia",
        population: 85816199,
        area_km2: 783562,
        gdp_usd: 1154600000000,
        currency: "Lira (TRY)",
        languages: ["Turkish"],
        groupings: ["g20", "nato", "oecd", "oic", "d8"],
        neighbors: ["GRC", "BGR", "GEO", "ARM", "AZE", "IRN", "IRQ", "SYR"],
        un_member: true,
        data_available: true
    },
    
    // ==================== EUROPE (44 countries) ====================
    {
        code: "RUS",
        name: "Russia",
        official_name: "Russian Federation",
        flag: "🇷🇺",
        capital: "Moscow",
        region: "europe",
        subregion: "Eastern Europe",
        population: 144444359,
        area_km2: 17098242,
        gdp_usd: 2062649000000,
        currency: "Ruble (RUB)",
        languages: ["Russian"],
        groupings: ["g20", "brics", "sco", "apec"],
        neighbors: ["NOR", "FIN", "EST", "LVA", "LTU", "POL", "BLR", "UKR", "GEO", "AZE", "KAZ", "CHN", "MNG", "PRK"],
        un_member: true,
        unsc_permanent: true,
        data_available: true
    },
    {
        code: "DEU",
        name: "Germany",
        official_name: "Federal Republic of Germany",
        flag: "🇩🇪",
        capital: "Berlin",
        region: "europe",
        subregion: "Western Europe",
        population: 83294633,
        area_km2: 357114,
        gdp_usd: 4308854000000,
        currency: "Euro (EUR)",
        languages: ["German"],
        groupings: ["g7", "g20", "eu", "nato", "oecd", "schengen"],
        neighbors: ["DNK", "POL", "CZE", "AUT", "CHE", "FRA", "LUX", "BEL", "NLD"],
        un_member: true,
        data_available: true
    },
    {
        code: "GBR",
        name: "United Kingdom",
        official_name: "United Kingdom of Great Britain and Northern Ireland",
        flag: "🇬🇧",
        capital: "London",
        region: "europe",
        subregion: "Northern Europe",
        population: 67736802,
        area_km2: 242495,
        gdp_usd: 3332059000000,
        currency: "Pound Sterling (GBP)",
        languages: ["English"],
        groupings: ["g7", "g20", "nato", "oecd", "commonwealth", "five_eyes"],
        neighbors: ["IRL"],
        un_member: true,
        unsc_permanent: true,
        data_available: true
    },
    {
        code: "FRA",
        name: "France",
        official_name: "French Republic",
        flag: "🇫🇷",
        capital: "Paris",
        region: "europe",
        subregion: "Western Europe",
        population: 64756584,
        area_km2: 643801,
        gdp_usd: 2936702000000,
        currency: "Euro (EUR)",
        languages: ["French"],
        groupings: ["g7", "g20", "eu", "nato", "oecd", "schengen"],
        neighbors: ["BEL", "LUX", "DEU", "CHE", "ITA", "MCO", "ESP", "AND"],
        un_member: true,
        unsc_permanent: true,
        data_available: true
    },
    {
        code: "ITA",
        name: "Italy",
        official_name: "Italian Republic",
        flag: "🇮🇹",
        capital: "Rome",
        region: "europe",
        subregion: "Southern Europe",
        population: 58870762,
        area_km2: 301340,
        gdp_usd: 2186082000000,
        currency: "Euro (EUR)",
        languages: ["Italian"],
        groupings: ["g7", "g20", "eu", "nato", "oecd", "schengen"],
        neighbors: ["FRA", "CHE", "AUT", "SVN", "SMR", "VAT"],
        un_member: true,
        data_available: true
    },
    {
        code: "ESP",
        name: "Spain",
        official_name: "Kingdom of Spain",
        flag: "🇪🇸",
        capital: "Madrid",
        region: "europe",
        subregion: "Southern Europe",
        population: 47519628,
        area_km2: 505992,
        gdp_usd: 1492432000000,
        currency: "Euro (EUR)",
        languages: ["Spanish"],
        groupings: ["eu", "nato", "oecd", "schengen"],
        neighbors: ["FRA", "PRT", "AND", "GIB", "MAR"],
        un_member: true,
        data_available: true
    },
    {
        code: "POL",
        name: "Poland",
        official_name: "Republic of Poland",
        flag: "🇵🇱",
        capital: "Warsaw",
        region: "europe",
        subregion: "Eastern Europe",
        population: 41026067,
        area_km2: 312696,
        gdp_usd: 842172000000,
        currency: "Zloty (PLN)",
        languages: ["Polish"],
        groupings: ["eu", "nato", "oecd", "schengen"],
        neighbors: ["DEU", "CZE", "SVK", "UKR", "BLR", "LTU", "RUS"],
        un_member: true,
        data_available: true
    },
    {
        code: "UKR",
        name: "Ukraine",
        official_name: "Ukraine",
        flag: "🇺🇦",
        capital: "Kyiv",
        region: "europe",
        subregion: "Eastern Europe",
        population: 37000000,
        area_km2: 603550,
        gdp_usd: 160502000000,
        currency: "Hryvnia (UAH)",
        languages: ["Ukrainian"],
        groupings: [],
        neighbors: ["RUS", "BLR", "POL", "SVK", "HUN", "ROU", "MDA"],
        un_member: true,
        data_available: true
    },
    {
        code: "NLD",
        name: "Netherlands",
        official_name: "Kingdom of the Netherlands",
        flag: "🇳🇱",
        capital: "Amsterdam",
        region: "europe",
        subregion: "Western Europe",
        population: 17618299,
        area_km2: 41850,
        gdp_usd: 1092748000000,
        currency: "Euro (EUR)",
        languages: ["Dutch"],
        groupings: ["eu", "nato", "oecd", "schengen"],
        neighbors: ["BEL", "DEU"],
        un_member: true,
        data_available: true
    },
    {
        code: "BEL",
        name: "Belgium",
        official_name: "Kingdom of Belgium",
        flag: "🇧🇪",
        capital: "Brussels",
        region: "europe",
        subregion: "Western Europe",
        population: 11686140,
        area_km2: 30528,
        gdp_usd: 624247000000,
        currency: "Euro (EUR)",
        languages: ["Dutch", "French", "German"],
        groupings: ["eu", "nato", "oecd", "schengen"],
        neighbors: ["NLD", "DEU", "LUX", "FRA"],
        un_member: true,
        data_available: true
    },
    {
        code: "SWE",
        name: "Sweden",
        official_name: "Kingdom of Sweden",
        flag: "🇸🇪",
        capital: "Stockholm",
        region: "europe",
        subregion: "Northern Europe",
        population: 10551707,
        area_km2: 450295,
        gdp_usd: 593268000000,
        currency: "Krona (SEK)",
        languages: ["Swedish"],
        groupings: ["eu", "nato", "oecd", "schengen"],
        neighbors: ["NOR", "FIN"],
        un_member: true,
        data_available: true
    },
    {
        code: "CHE",
        name: "Switzerland",
        official_name: "Swiss Confederation",
        flag: "🇨🇭",
        capital: "Bern",
        region: "europe",
        subregion: "Western Europe",
        population: 8796669,
        area_km2: 41284,
        gdp_usd: 884940000000,
        currency: "Franc (CHF)",
        languages: ["German", "French", "Italian", "Romansh"],
        groupings: ["oecd", "schengen"],
        neighbors: ["DEU", "FRA", "ITA", "AUT", "LIE"],
        un_member: true,
        data_available: true
    },
    {
        code: "AUT",
        name: "Austria",
        official_name: "Republic of Austria",
        flag: "🇦🇹",
        capital: "Vienna",
        region: "europe",
        subregion: "Western Europe",
        population: 9027999,
        area_km2: 83871,
        gdp_usd: 515199000000,
        currency: "Euro (EUR)",
        languages: ["German"],
        groupings: ["eu", "oecd", "schengen"],
        neighbors: ["DEU", "CZE", "SVK", "HUN", "SVN", "ITA", "CHE", "LIE"],
        un_member: true,
        data_available: true
    },
    {
        code: "NOR",
        name: "Norway",
        official_name: "Kingdom of Norway",
        flag: "🇳🇴",
        capital: "Oslo",
        region: "europe",
        subregion: "Northern Europe",
        population: 5474360,
        area_km2: 323802,
        gdp_usd: 579267000000,
        currency: "Krone (NOK)",
        languages: ["Norwegian"],
        groupings: ["nato", "oecd", "schengen"],
        neighbors: ["SWE", "FIN", "RUS"],
        un_member: true,
        data_available: true
    },
    {
        code: "DNK",
        name: "Denmark",
        official_name: "Kingdom of Denmark",
        flag: "🇩🇰",
        capital: "Copenhagen",
        region: "europe",
        subregion: "Northern Europe",
        population: 5910913,
        area_km2: 43094,
        gdp_usd: 404198000000,
        currency: "Krone (DKK)",
        languages: ["Danish"],
        groupings: ["eu", "nato", "oecd", "schengen"],
        neighbors: ["DEU"],
        un_member: true,
        data_available: true
    },
    {
        code: "FIN",
        name: "Finland",
        official_name: "Republic of Finland",
        flag: "🇫🇮",
        capital: "Helsinki",
        region: "europe",
        subregion: "Northern Europe",
        population: 5545475,
        area_km2: 338424,
        gdp_usd: 301670000000,
        currency: "Euro (EUR)",
        languages: ["Finnish", "Swedish"],
        groupings: ["eu", "nato", "oecd", "schengen"],
        neighbors: ["SWE", "NOR", "RUS"],
        un_member: true,
        data_available: true
    },
    {
        code: "PRT",
        name: "Portugal",
        official_name: "Portuguese Republic",
        flag: "🇵🇹",
        capital: "Lisbon",
        region: "europe",
        subregion: "Southern Europe",
        population: 10467366,
        area_km2: 92090,
        gdp_usd: 287080000000,
        currency: "Euro (EUR)",
        languages: ["Portuguese"],
        groupings: ["eu", "nato", "oecd", "schengen"],
        neighbors: ["ESP"],
        un_member: true,
        data_available: true
    },
    {
        code: "GRC",
        name: "Greece",
        official_name: "Hellenic Republic",
        flag: "🇬🇷",
        capital: "Athens",
        region: "europe",
        subregion: "Southern Europe",
        population: 10341277,
        area_km2: 131957,
        gdp_usd: 239300000000,
        currency: "Euro (EUR)",
        languages: ["Greek"],
        groupings: ["eu", "nato", "oecd", "schengen"],
        neighbors: ["ALB", "MKD", "BGR", "TUR"],
        un_member: true,
        data_available: true
    },
    {
        code: "IRL",
        name: "Ireland",
        official_name: "Ireland",
        flag: "🇮🇪",
        capital: "Dublin",
        region: "europe",
        subregion: "Northern Europe",
        population: 5056935,
        area_km2: 70273,
        gdp_usd: 545629000000,
        currency: "Euro (EUR)",
        languages: ["Irish", "English"],
        groupings: ["eu", "oecd", "schengen"],
        neighbors: ["GBR"],
        un_member: true,
        data_available: true
    },
    {
        code: "CZE",
        name: "Czechia",
        official_name: "Czech Republic",
        flag: "🇨🇿",
        capital: "Prague",
        region: "europe",
        subregion: "Eastern Europe",
        population: 10827529,
        area_km2: 78865,
        gdp_usd: 330860000000,
        currency: "Koruna (CZK)",
        languages: ["Czech"],
        groupings: ["eu", "nato", "oecd", "schengen"],
        neighbors: ["DEU", "POL", "SVK", "AUT"],
        un_member: true,
        data_available: true
    },
    {
        code: "ROU",
        name: "Romania",
        official_name: "Romania",
        flag: "🇷🇴",
        capital: "Bucharest",
        region: "europe",
        subregion: "Eastern Europe",
        population: 19659267,
        area_km2: 238391,
        gdp_usd: 348902000000,
        currency: "Leu (RON)",
        languages: ["Romanian"],
        groupings: ["eu", "nato", "schengen"],
        neighbors: ["UKR", "MDA", "HUN", "SRB", "BGR"],
        un_member: true,
        data_available: true
    },
    {
        code: "HUN",
        name: "Hungary",
        official_name: "Hungary",
        flag: "🇭🇺",
        capital: "Budapest",
        region: "europe",
        subregion: "Eastern Europe",
        population: 9597085,
        area_km2: 93028,
        gdp_usd: 212381000000,
        currency: "Forint (HUF)",
        languages: ["Hungarian"],
        groupings: ["eu", "nato", "oecd", "schengen"],
        neighbors: ["SVK", "UKR", "ROU", "SRB", "HRV", "SVN", "AUT"],
        un_member: true,
        data_available: true
    },

    // ==================== NORTH AMERICA (23 countries) ====================
    {
        code: "USA",
        name: "United States",
        official_name: "United States of America",
        flag: "🇺🇸",
        capital: "Washington, D.C.",
        region: "north-america",
        subregion: "Northern America",
        population: 339996563,
        area_km2: 9833517,
        gdp_usd: 28781083000000,
        currency: "Dollar (USD)",
        languages: ["English"],
        groupings: ["g7", "g20", "nato", "oecd", "quad", "five_eyes", "apec", "usmca"],
        neighbors: ["CAN", "MEX"],
        un_member: true,
        unsc_permanent: true,
        data_available: true
    },
    {
        code: "CAN",
        name: "Canada",
        official_name: "Canada",
        flag: "🇨🇦",
        capital: "Ottawa",
        region: "north-america",
        subregion: "Northern America",
        population: 38781292,
        area_km2: 9984670,
        gdp_usd: 2221218000000,
        currency: "Dollar (CAD)",
        languages: ["English", "French"],
        groupings: ["g7", "g20", "nato", "oecd", "commonwealth", "five_eyes", "apec", "usmca"],
        neighbors: ["USA"],
        un_member: true,
        data_available: true
    },
    {
        code: "MEX",
        name: "Mexico",
        official_name: "United Mexican States",
        flag: "🇲🇽",
        capital: "Mexico City",
        region: "north-america",
        subregion: "Central America",
        population: 128455567,
        area_km2: 1964375,
        gdp_usd: 1811468000000,
        currency: "Peso (MXN)",
        languages: ["Spanish"],
        groupings: ["g20", "oecd", "apec", "usmca", "pacific_alliance"],
        neighbors: ["USA", "GTM", "BLZ"],
        un_member: true,
        data_available: true
    },
    {
        code: "CUB",
        name: "Cuba",
        official_name: "Republic of Cuba",
        flag: "🇨🇺",
        capital: "Havana",
        region: "north-america",
        subregion: "Caribbean",
        population: 11194449,
        area_km2: 109884,
        gdp_usd: 107352000000,
        currency: "Peso (CUP)",
        languages: ["Spanish"],
        groupings: ["nam"],
        neighbors: [],
        un_member: true,
        data_available: true
    },
    {
        code: "JAM",
        name: "Jamaica",
        official_name: "Jamaica",
        flag: "🇯🇲",
        capital: "Kingston",
        region: "north-america",
        subregion: "Caribbean",
        population: 2825544,
        area_km2: 10991,
        gdp_usd: 17097000000,
        currency: "Dollar (JMD)",
        languages: ["English"],
        groupings: ["commonwealth", "caricom"],
        neighbors: [],
        un_member: true,
        data_available: true
    },
    {
        code: "HTI",
        name: "Haiti",
        official_name: "Republic of Haiti",
        flag: "🇭🇹",
        capital: "Port-au-Prince",
        region: "north-america",
        subregion: "Caribbean",
        population: 11724763,
        area_km2: 27750,
        gdp_usd: 21917000000,
        currency: "Gourde (HTG)",
        languages: ["French", "Haitian Creole"],
        groupings: ["caricom"],
        neighbors: ["DOM"],
        un_member: true,
        data_available: true
    },
    {
        code: "DOM",
        name: "Dominican Republic",
        official_name: "Dominican Republic",
        flag: "🇩🇴",
        capital: "Santo Domingo",
        region: "north-america",
        subregion: "Caribbean",
        population: 11332972,
        area_km2: 48671,
        gdp_usd: 121289000000,
        currency: "Peso (DOP)",
        languages: ["Spanish"],
        groupings: [],
        neighbors: ["HTI"],
        un_member: true,
        data_available: true
    },
    {
        code: "PAN",
        name: "Panama",
        official_name: "Republic of Panama",
        flag: "🇵🇦",
        capital: "Panama City",
        region: "north-america",
        subregion: "Central America",
        population: 4408581,
        area_km2: 75417,
        gdp_usd: 76522000000,
        currency: "Balboa (PAB)",
        languages: ["Spanish"],
        groupings: [],
        neighbors: ["CRI", "COL"],
        un_member: true,
        data_available: true
    },
    {
        code: "CRI",
        name: "Costa Rica",
        official_name: "Republic of Costa Rica",
        flag: "🇨🇷",
        capital: "San José",
        region: "north-america",
        subregion: "Central America",
        population: 5212173,
        area_km2: 51100,
        gdp_usd: 68379000000,
        currency: "Colón (CRC)",
        languages: ["Spanish"],
        groupings: ["oecd"],
        neighbors: ["NIC", "PAN"],
        un_member: true,
        data_available: true
    },

    // ==================== SOUTH AMERICA (12 countries) ====================
    {
        code: "BRA",
        name: "Brazil",
        official_name: "Federative Republic of Brazil",
        flag: "🇧🇷",
        capital: "Brasília",
        region: "south-america",
        subregion: "South America",
        population: 216422446,
        area_km2: 8515767,
        gdp_usd: 2173698000000,
        currency: "Real (BRL)",
        languages: ["Portuguese"],
        groupings: ["g20", "brics", "mercosur"],
        neighbors: ["ARG", "URY", "PRY", "BOL", "PER", "COL", "VEN", "GUY", "SUR", "GUF"],
        un_member: true,
        data_available: true
    },
        {
        code: "ARG",
        name: "Argentina",
        official_name: "Argentine Republic",
        flag: "🇦🇷",
        capital: "Buenos Aires",
        region: "south-america",
        subregion: "South America",
        population: 45773884,
        area_km2: 2780400,
        gdp_usd: 641131000000,
        currency: "Peso (ARS)",
        languages: ["Spanish"],
        groupings: ["g20", "mercosur"],
        neighbors: ["CHL", "BOL", "PRY", "BRA", "URY"],
        un_member: true,
        data_available: true
    },
    {
        code: "COL",
        name: "Colombia",
        official_name: "Republic of Colombia",
        flag: "🇨🇴",
        capital: "Bogotá",
        region: "south-america",
        subregion: "South America",
        population: 52085168,
        area_km2: 1141748,
        gdp_usd: 363835000000,
        currency: "Peso (COP)",
        languages: ["Spanish"],
        groupings: ["oecd", "pacific_alliance"],
        neighbors: ["VEN", "BRA", "PER", "ECU", "PAN"],
        un_member: true,
        data_available: true
    },
    {
        code: "PER",
        name: "Peru",
        official_name: "Republic of Peru",
        flag: "🇵🇪",
        capital: "Lima",
        region: "south-america",
        subregion: "South America",
        population: 34049588,
        area_km2: 1285216,
        gdp_usd: 268235000000,
        currency: "Sol (PEN)",
        languages: ["Spanish", "Quechua", "Aymara"],
        groupings: ["apec", "pacific_alliance"],
        neighbors: ["ECU", "COL", "BRA", "BOL", "CHL"],
        un_member: true,
        data_available: true
    },
    {
        code: "VEN",
        name: "Venezuela",
        official_name: "Bolivarian Republic of Venezuela",
        flag: "🇻🇪",
        capital: "Caracas",
        region: "south-america",
        subregion: "South America",
        population: 28838499,
        area_km2: 916445,
        gdp_usd: 98140000000,
        currency: "Bolívar (VES)",
        languages: ["Spanish"],
        groupings: ["opec", "mercosur"],
        neighbors: ["COL", "BRA", "GUY"],
        un_member: true,
        data_available: true
    },
    {
        code: "CHL",
        name: "Chile",
        official_name: "Republic of Chile",
        flag: "🇨🇱",
        capital: "Santiago",
        region: "south-america",
        subregion: "South America",
        population: 19629590,
        area_km2: 756102,
        gdp_usd: 335533000000,
        currency: "Peso (CLP)",
        languages: ["Spanish"],
        groupings: ["oecd", "apec", "pacific_alliance"],
        neighbors: ["PER", "BOL", "ARG"],
        un_member: true,
        data_available: true
    },
    {
        code: "ECU",
        name: "Ecuador",
        official_name: "Republic of Ecuador",
        flag: "🇪🇨",
        capital: "Quito",
        region: "south-america",
        subregion: "South America",
        population: 18190484,
        area_km2: 283561,
        gdp_usd: 118845000000,
        currency: "Dollar (USD)",
        languages: ["Spanish"],
        groupings: ["opec"],
        neighbors: ["COL", "PER"],
        un_member: true,
        data_available: true
    },
    {
        code: "BOL",
        name: "Bolivia",
        official_name: "Plurinational State of Bolivia",
        flag: "🇧🇴",
        capital: "Sucre",
        region: "south-america",
        subregion: "South America",
        population: 12388571,
        area_km2: 1098581,
        gdp_usd: 44009000000,
        currency: "Boliviano (BOB)",
        languages: ["Spanish", "Quechua", "Aymara"],
        groupings: ["mercosur"],
        neighbors: ["BRA", "PRY", "ARG", "CHL", "PER"],
        un_member: true,
        data_available: true
    },
    {
        code: "PRY",
        name: "Paraguay",
        official_name: "Republic of Paraguay",
        flag: "🇵🇾",
        capital: "Asunción",
        region: "south-america",
        subregion: "South America",
        population: 6861524,
        area_km2: 406752,
        gdp_usd: 42956000000,
        currency: "Guaraní (PYG)",
        languages: ["Spanish", "Guaraní"],
        groupings: ["mercosur"],
        neighbors: ["ARG", "BOL", "BRA"],
        un_member: true,
        data_available: true
    },
    {
        code: "URY",
        name: "Uruguay",
        official_name: "Oriental Republic of Uruguay",
        flag: "🇺🇾",
        capital: "Montevideo",
        region: "south-america",
        subregion: "South America",
        population: 3423108,
        area_km2: 176215,
        gdp_usd: 71177000000,
        currency: "Peso (UYU)",
        languages: ["Spanish"],
        groupings: ["mercosur"],
        neighbors: ["ARG", "BRA"],
        un_member: true,
        data_available: true
    },
    {
        code: "GUY",
        name: "Guyana",
        official_name: "Co-operative Republic of Guyana",
        flag: "🇬🇾",
        capital: "Georgetown",
        region: "south-america",
        subregion: "South America",
        population: 813834,
        area_km2: 214969,
        gdp_usd: 14718000000,
        currency: "Dollar (GYD)",
        languages: ["English"],
        groupings: ["caricom", "commonwealth"],
        neighbors: ["VEN", "BRA", "SUR"],
        un_member: true,
        data_available: true
    },
    {
        code: "SUR",
        name: "Suriname",
        official_name: "Republic of Suriname",
        flag: "🇸🇷",
        capital: "Paramaribo",
        region: "south-america",
        subregion: "South America",
        population: 618040,
        area_km2: 163820,
        gdp_usd: 3621000000,
        currency: "Dollar (SRD)",
        languages: ["Dutch"],
        groupings: ["caricom"],
        neighbors: ["GUY", "BRA", "GUF"],
        un_member: true,
        data_available: true
    },

    // ==================== AFRICA (54 countries) ====================
    {
        code: "ZAF",
        name: "South Africa",
        official_name: "Republic of South Africa",
        flag: "🇿🇦",
        capital: "Pretoria",
        region: "africa",
        subregion: "Southern Africa",
        population: 60414495,
        area_km2: 1221037,
        gdp_usd: 405870000000,
        currency: "Rand (ZAR)",
        languages: ["Zulu", "Xhosa", "Afrikaans", "English"],
        groupings: ["g20", "brics", "au", "commonwealth", "sadc"],
        neighbors: ["NAM", "BWA", "ZWE", "MOZ", "SWZ", "LSO"],
        un_member: true,
        data_available: true
    },
    {
        code: "NGA",
        name: "Nigeria",
        official_name: "Federal Republic of Nigeria",
        flag: "🇳🇬",
        capital: "Abuja",
        region: "africa",
        subregion: "Western Africa",
        population: 223804632,
        area_km2: 923768,
        gdp_usd: 477386000000,
        currency: "Naira (NGN)",
        languages: ["English"],
        groupings: ["au", "opec", "commonwealth", "ecowas"],
        neighbors: ["BEN", "NER", "TCD", "CMR"],
        un_member: true,
        data_available: true
    },
    {
        code: "EGY",
        name: "Egypt",
        official_name: "Arab Republic of Egypt",
        flag: "🇪🇬",
        capital: "Cairo",
        region: "africa",
        subregion: "Northern Africa",
        population: 112716598,
        area_km2: 1002450,
        gdp_usd: 476748000000,
        currency: "Pound (EGP)",
        languages: ["Arabic"],
        groupings: ["au", "arab_league", "oic", "brics"],
        neighbors: ["LBY", "SDN", "ISR", "PSE"],
        un_member: true,
        data_available: true
    },
    {
        code: "ETH",
        name: "Ethiopia",
        official_name: "Federal Democratic Republic of Ethiopia",
        flag: "🇪🇹",
        capital: "Addis Ababa",
        region: "africa",
        subregion: "Eastern Africa",
        population: 126527060,
        area_km2: 1104300,
        gdp_usd: 163698000000,
        currency: "Birr (ETB)",
        languages: ["Amharic"],
        groupings: ["au", "brics"],
        neighbors: ["ERI", "DJI", "SOM", "KEN", "SSD", "SDN"],
        un_member: true,
        data_available: true
    },
    {
        code: "KEN",
        name: "Kenya",
        official_name: "Republic of Kenya",
        flag: "🇰🇪",
        capital: "Nairobi",
        region: "africa",
        subregion: "Eastern Africa",
        population: 55100586,
        area_km2: 580367,
        gdp_usd: 113420000000,
        currency: "Shilling (KES)",
        languages: ["Swahili", "English"],
        groupings: ["au", "commonwealth", "eac"],
        neighbors: ["ETH", "SOM", "TZA", "UGA", "SSD"],
        un_member: true,
        data_available: true
    },
    {
        code: "DZA",
        name: "Algeria",
        official_name: "People's Democratic Republic of Algeria",
        flag: "🇩🇿",
        capital: "Algiers",
        region: "africa",
        subregion: "Northern Africa",
        population: 45606480,
        area_km2: 2381741,
        gdp_usd: 195062000000,
        currency: "Dinar (DZD)",
        languages: ["Arabic", "Berber"],
        groupings: ["au", "opec", "arab_league", "oic"],
        neighbors: ["MAR", "TUN", "LBY", "NER", "MLI", "MRT", "ESH"],
        un_member: true,
        data_available: true
    },
    {
        code: "MAR",
        name: "Morocco",
        official_name: "Kingdom of Morocco",
        flag: "🇲🇦",
        capital: "Rabat",
        region: "africa",
        subregion: "Northern Africa",
        population: 37840044,
        area_km2: 446550,
        gdp_usd: 152379000000,
        currency: "Dirham (MAD)",
        languages: ["Arabic", "Berber"],
        groupings: ["arab_league", "oic"],
        neighbors: ["DZA", "ESH", "ESP"],
        un_member: true,
        data_available: true
    },
    {
        code: "GHA",
        name: "Ghana",
        official_name: "Republic of Ghana",
        flag: "🇬🇭",
        capital: "Accra",
        region: "africa",
        subregion: "Western Africa",
        population: 34121985,
        area_km2: 238533,
        gdp_usd: 76374000000,
        currency: "Cedi (GHS)",
        languages: ["English"],
        groupings: ["au", "commonwealth", "ecowas"],
        neighbors: ["CIV", "TGO", "BFA"],
        un_member: true,
        data_available: true
    },
    {
        code: "TZA",
        name: "Tanzania",
        official_name: "United Republic of Tanzania",
        flag: "🇹🇿",
        capital: "Dodoma",
        region: "africa",
        subregion: "Eastern Africa",
        population: 67438106,
        area_km2: 947303,
        gdp_usd: 79158000000,
        currency: "Shilling (TZS)",
        languages: ["Swahili", "English"],
        groupings: ["au", "commonwealth", "eac", "sadc"],
        neighbors: ["KEN", "UGA", "RWA", "BDI", "COD", "ZMB", "MWI", "MOZ"],
        un_member: true,
        data_available: true
    },
    {
        code: "COD",
        name: "DR Congo",
        official_name: "Democratic Republic of the Congo",
        flag: "🇨🇩",
        capital: "Kinshasa",
        region: "africa",
        subregion: "Central Africa",
        population: 102262808,
        area_km2: 2344858,
        gdp_usd: 66380000000,
        currency: "Franc (CDF)",
        languages: ["French"],
        groupings: ["au", "sadc"],
        neighbors: ["COG", "CAF", "SSD", "UGA", "RWA", "BDI", "TZA", "ZMB", "AGO"],
        un_member: true,
        data_available: true
    },
    {
        code: "SDN",
        name: "Sudan",
        official_name: "Republic of the Sudan",
        flag: "🇸🇩",
        capital: "Khartoum",
        region: "africa",
        subregion: "Northern Africa",
        population: 48109006,
        area_km2: 1886068,
        gdp_usd: 51693000000,
        currency: "Pound (SDG)",
        languages: ["Arabic", "English"],
        groupings: ["au", "arab_league", "oic"],
        neighbors: ["EGY", "LBY", "TCD", "CAF", "SSD", "ETH", "ERI"],
        un_member: true,
        data_available: true
    },
    {
        code: "UGA",
        name: "Uganda",
        official_name: "Republic of Uganda",
        flag: "🇺🇬",
        capital: "Kampala",
        region: "africa",
        subregion: "Eastern Africa",
        population: 48582334,
        area_km2: 241550,
        gdp_usd: 49272000000,
        currency: "Shilling (UGX)",
        languages: ["English", "Swahili"],
        groupings: ["au", "commonwealth", "eac"],
        neighbors: ["SSD", "KEN", "TZA", "RWA", "COD"],
        un_member: true,
        data_available: true
    },
    {
        code: "AGO",
        name: "Angola",
        official_name: "Republic of Angola",
        flag: "🇦🇴",
        capital: "Luanda",
        region: "africa",
        subregion: "Central Africa",
        population: 36684202,
        area_km2: 1246700,
        gdp_usd: 124859000000,
        currency: "Kwanza (AOA)",
        languages: ["Portuguese"],
        groupings: ["au", "opec", "sadc"],
        neighbors: ["COD", "COG", "ZMB", "NAM"],
        un_member: true,
        data_available: true
    },
    {
        code: "SEN",
        name: "Senegal",
        official_name: "Republic of Senegal",
        flag: "🇸🇳",
        capital: "Dakar",
        region: "africa",
        subregion: "Western Africa",
        population: 17763163,
        area_km2: 196722,
        gdp_usd: 27625000000,
        currency: "CFA Franc (XOF)",
        languages: ["French"],
        groupings: ["au", "ecowas", "oic"],
        neighbors: ["MRT", "MLI", "GMB", "GIN", "GNB"],
        un_member: true,
        data_available: true
    },
    {
        code: "ZWE",
        name: "Zimbabwe",
        official_name: "Republic of Zimbabwe",
        flag: "🇿🇼",
        capital: "Harare",
        region: "africa",
        subregion: "Eastern Africa",
        population: 16665409,
        area_km2: 390757,
        gdp_usd: 28539000000,
        currency: "Dollar (ZWL)",
        languages: ["English", "Shona", "Ndebele"],
        groupings: ["au", "sadc"],
        neighbors: ["ZAF", "BWA", "ZMB", "MOZ"],
        un_member: true,
        data_available: true
    },
    {
        code: "ZMB",
        name: "Zambia",
        official_name: "Republic of Zambia",
        flag: "🇿🇲",
        capital: "Lusaka",
        region: "africa",
        subregion: "Eastern Africa",
        population: 20569737,
        area_km2: 752612,
        gdp_usd: 29872000000,
        currency: "Kwacha (ZMW)",
        languages: ["English"],
        groupings: ["au", "commonwealth", "sadc"],
        neighbors: ["COD", "TZA", "MWI", "MOZ", "ZWE", "BWA", "NAM", "AGO"],
        un_member: true,
        data_available: true
    },
    {
        code: "TUN",
        name: "Tunisia",
        official_name: "Republic of Tunisia",
        flag: "🇹🇳",
        capital: "Tunis",
        region: "africa",
        subregion: "Northern Africa",
        population: 12458223,
        area_km2: 163610,
        gdp_usd: 46841000000,
        currency: "Dinar (TND)",
        languages: ["Arabic"],
        groupings: ["au", "arab_league", "oic"],
        neighbors: ["DZA", "LBY"],
        un_member: true,
        data_available: true
    },
    {
        code: "LBY",
        name: "Libya",
        official_name: "State of Libya",
        flag: "🇱🇾",
        capital: "Tripoli",
        region: "africa",
        subregion: "Northern Africa",
        population: 6888388,
        area_km2: 1759540,
        gdp_usd: 50492000000,
        currency: "Dinar (LYD)",
        languages: ["Arabic"],
        groupings: ["au", "opec", "arab_league", "oic"],
        neighbors: ["TUN", "DZA", "NER", "TCD", "SDN", "EGY"],
        un_member: true,
        data_available: true
    },
    {
        code: "CIV",
        name: "Côte d'Ivoire",
        official_name: "Republic of Côte d'Ivoire",
        flag: "🇨🇮",
        capital: "Yamoussoukro",
        region: "africa",
        subregion: "Western Africa",
        population: 28873034,
        area_km2: 322463,
        gdp_usd: 79984000000,
        currency: "CFA Franc (XOF)",
        languages: ["French"],
        groupings: ["au", "ecowas"],
        neighbors: ["LBR", "GIN", "MLI", "BFA", "GHA"],
        un_member: true,
        data_available: true
    },
    {
        code: "CMR",
        name: "Cameroon",
        official_name: "Republic of Cameroon",
        flag: "🇨🇲",
        capital: "Yaoundé",
        region: "africa",
        subregion: "Central Africa",
        population: 28647293,
        area_km2: 475442,
        gdp_usd: 46584000000,
        currency: "CFA Franc (XAF)",
        languages: ["French", "English"],
        groupings: ["au", "commonwealth"],
        neighbors: ["NGA", "TCD", "CAF", "COG", "GAB", "GNQ"],
        un_member: true,
        data_available: true
    },

    // ==================== OCEANIA (14 countries) ====================
    {
        code: "AUS",
        name: "Australia",
        official_name: "Commonwealth of Australia",
        flag: "🇦🇺",
        capital: "Canberra",
        region: "oceania",
        subregion: "Oceania",
        population: 26439111,
        area_km2: 7692024,
        gdp_usd: 1724787000000,
        currency: "Dollar (AUD)",
        languages: ["English"],
        groupings: ["g20", "quad", "aukus", "five_eyes", "commonwealth", "apec", "oecd"],
        neighbors: [],
        un_member: true,
        data_available: true
    },
    {
        code: "NZL",
        name: "New Zealand",
        official_name: "New Zealand",
        flag: "🇳🇿",
        capital: "Wellington",
        region: "oceania",
        subregion: "Oceania",
        population: 5185288,
        area_km2: 270467,
        gdp_usd: 252221000000,
        currency: "Dollar (NZD)",
        languages: ["English", "Māori"],
        groupings: ["five_eyes", "commonwealth", "apec", "oecd"],
        neighbors: [],
        un_member: true,
        data_available: true
    },
    {
        code: "PNG",
        name: "Papua New Guinea",
        official_name: "Independent State of Papua New Guinea",
        flag: "🇵🇬",
        capital: "Port Moresby",
        region: "oceania",
        subregion: "Oceania",
        population: 10329931,
        area_km2: 462840,
        gdp_usd: 30933000000,
        currency: "Kina (PGK)",
        languages: ["English", "Tok Pisin", "Hiri Motu"],
        groupings: ["commonwealth", "apec"],
        neighbors: ["IDN"],
        un_member: true,
        data_available: true
    },
    {
        code: "FJI",
        name: "Fiji",
        official_name: "Republic of Fiji",
        flag: "🇫🇯",
        capital: "Suva",
        region: "oceania",
        subregion: "Oceania",
        population: 936375,
        area_km2: 18274,
        gdp_usd: 5317000000,
        currency: "Dollar (FJD)",
        languages: ["English", "Fijian", "Hindi"],
        groupings: ["commonwealth"],
        neighbors: [],
        un_member: true,
        data_available: true
    },
    {
        code: "SLB",
        name: "Solomon Islands",
        official_name: "Solomon Islands",
        flag: "🇸🇧",
        capital: "Honiara",
        region: "oceania",
        subregion: "Oceania",
        population: 740424,
        area_km2: 28896,
        gdp_usd: 1695000000,
        currency: "Dollar (SBD)",
        languages: ["English"],
        groupings: ["commonwealth"],
        neighbors: [],
        un_member: true,
        data_available: true
    },
    {
        code: "VUT",
        name: "Vanuatu",
        official_name: "Republic of Vanuatu",
        flag: "🇻🇺",
        capital: "Port Vila",
        region: "oceania",
        subregion: "Oceania",
        population: 334506,
        area_km2: 12189,
        gdp_usd: 1038000000,
        currency: "Vatu (VUV)",
        languages: ["Bislama", "English", "French"],
        groupings: ["commonwealth"],
        neighbors: [],
        un_member: true,
        data_available: true
    },
    {
        code: "WSM",
        name: "Samoa",
        official_name: "Independent State of Samoa",
        flag: "🇼🇸",
        capital: "Apia",
        region: "oceania",
        subregion: "Oceania",
        population: 225681,
        area_km2: 2842,
        gdp_usd: 858000000,
        currency: "Tala (WST)",
        languages: ["Samoan", "English"],
        groupings: ["commonwealth"],
        neighbors: [],
        un_member: true,
        data_available: true
    },
    {
        code: "TON",
        name: "Tonga",
        official_name: "Kingdom of Tonga",
        flag: "🇹🇴",
        capital: "Nukuʻalofa",
        region: "oceania",
        subregion: "Oceania",
        population: 107773,
        area_km2: 747,
        gdp_usd: 512000000,
        currency: "Paʻanga (TOP)",
        languages: ["Tongan", "English"],
        groupings: ["commonwealth"],
        neighbors: [],
        un_member: true,
        data_available: true
    },
    {
        code: "KIR",
        name: "Kiribati",
        official_name: "Republic of Kiribati",
        flag: "🇰🇮",
        capital: "Tarawa",
        region: "oceania",
        subregion: "Oceania",
        population: 133515,
        area_km2: 811,
        gdp_usd: 227000000,
        currency: "Dollar (AUD)",
        languages: ["English", "Gilbertese"],
        groupings: ["commonwealth"],
        neighbors: [],
        un_member: true,
        data_available: true
    },
    {
        code: "FSM",
        name: "Micronesia",
        official_name: "Federated States of Micronesia",
        flag: "🇫🇲",
        capital: "Palikir",
        region: "oceania",
        subregion: "Oceania",
        population: 115224,
        area_km2: 702,
        gdp_usd: 427000000,
        currency: "Dollar (USD)",
        languages: ["English"],
        groupings: [],
        neighbors: [],
        un_member: true,
        data_available: true
    },
    {
        code: "MHL",
        name: "Marshall Islands",
        official_name: "Republic of the Marshall Islands",
        flag: "🇲🇭",
        capital: "Majuro",
        region: "oceania",
        subregion: "Oceania",
        population: 41996,
        area_km2: 181,
        gdp_usd: 280000000,
        currency: "Dollar (USD)",
        languages: ["Marshallese", "English"],
        groupings: [],
        neighbors: [],
        un_member: true,
        data_available: true
    },
    {
        code: "PLW",
        name: "Palau",
        official_name: "Republic of Palau",
        flag: "🇵🇼",
        capital: "Ngerulmud",
        region: "oceania",
        subregion: "Oceania",
        population: 18055,
        area_km2: 459,
        gdp_usd: 218000000,
        currency: "Dollar (USD)",
        languages: ["Palauan", "English"],
        groupings: [],
        neighbors: [],
        un_member: true,
        data_available: true
    },
    {
        code: "NRU",
        name: "Nauru",
        official_name: "Republic of Nauru",
        flag: "🇳🇷",
        capital: "Yaren",
        region: "oceania",
        subregion: "Oceania",
        population: 12780,
        area_km2: 21,
        gdp_usd: 151000000,
        currency: "Dollar (AUD)",
        languages: ["Nauruan", "English"],
        groupings: ["commonwealth"],
        neighbors: [],
        un_member: true,
        data_available: true
    },
    {
        code: "TUV",
        name: "Tuvalu",
        official_name: "Tuvalu",
        flag: "🇹🇻",
        capital: "Funafuti",
        region: "oceania",
        subregion: "Oceania",
        population: 11396,
        area_km2: 26,
        gdp_usd: 60000000,
        currency: "Dollar (AUD)",
        languages: ["Tuvaluan", "English"],
        groupings: ["commonwealth"],
        neighbors: [],
        un_member: true,
        data_available: true
    },

    // ==================== ADDITIONAL ASIAN COUNTRIES ====================
    {
        code: "KAZ",
        name: "Kazakhstan",
        official_name: "Republic of Kazakhstan",
        flag: "🇰🇿",
        capital: "Astana",
        region: "asia",
        subregion: "Central Asia",
        population: 19900000,
        area_km2: 2724900,
        gdp_usd: 259292000000,
        currency: "Tenge (KZT)",
        languages: ["Kazakh", "Russian"],
        groupings: ["sco", "csto", "eaeu"],
        neighbors: ["RUS", "CHN", "KGZ", "UZB", "TKM"],
        un_member: true,
        data_available: true
    },
    {
        code: "UZB",
        name: "Uzbekistan",
        official_name: "Republic of Uzbekistan",
        flag: "🇺🇿",
        capital: "Tashkent",
        region: "asia",
        subregion: "Central Asia",
        population: 35300000,
        area_km2: 448978,
        gdp_usd: 92316000000,
        currency: "Sum (UZS)",
        languages: ["Uzbek"],
        groupings: ["sco", "oic"],
        neighbors: ["KAZ", "KGZ", "TJK", "AFG", "TKM"],
        un_member: true,
        data_available: true
    },
    {
        code: "TKM",
        name: "Turkmenistan",
        official_name: "Turkmenistan",
        flag: "🇹🇲",
        capital: "Ashgabat",
        region: "asia",
        subregion: "Central Asia",
        population: 6516100,
        area_km2: 488100,
        gdp_usd: 59887000000,
        currency: "Manat (TMT)",
        languages: ["Turkmen"],
        groupings: [],
        neighbors: ["KAZ", "UZB", "AFG", "IRN"],
        un_member: true,
        data_available: true
    },
    {
        code: "TJK",
        name: "Tajikistan",
        official_name: "Republic of Tajikistan",
        flag: "🇹🇯",
        capital: "Dushanbe",
        region: "asia",
        subregion: "Central Asia",
        population: 10143543,
        area_km2: 143100,
        gdp_usd: 11788000000,
        currency: "Somoni (TJS)",
        languages: ["Tajik"],
        groupings: ["sco", "csto"],
        neighbors: ["KGZ", "UZB", "AFG", "CHN"],
        un_member: true,
        data_available: true
    },
    {
        code: "KGZ",
        name: "Kyrgyzstan",
        official_name: "Kyrgyz Republic",
        flag: "🇰🇬",
        capital: "Bishkek",
        region: "asia",
        subregion: "Central Asia",
        population: 7100000,
        area_km2: 199951,
        gdp_usd: 14049000000,
        currency: "Som (KGS)",
        languages: ["Kyrgyz", "Russian"],
        groupings: ["sco", "csto", "eaeu"],
        neighbors: ["KAZ", "UZB", "TJK", "CHN"],
        un_member: true,
        data_available: true
    },
    {
        code: "MNG",
        name: "Mongolia",
        official_name: "Mongolia",
        flag: "🇲🇳",
        capital: "Ulaanbaatar",
        region: "asia",
        subregion: "East Asia",
        population: 3447157,
        area_km2: 1564116,
        gdp_usd: 20776000000,
        currency: "Tugrik (MNT)",
        languages: ["Mongolian"],
        groupings: [],
        neighbors: ["RUS", "CHN"],
        un_member: true,
        data_available: true
    },
    {
        code: "KHM",
        name: "Cambodia",
        official_name: "Kingdom of Cambodia",
        flag: "🇰🇭",
        capital: "Phnom Penh",
        region: "asia",
        subregion: "Southeast Asia",
        population: 16767842,
        area_km2: 181035,
        gdp_usd: 32146000000,
        currency: "Riel (KHR)",
        languages: ["Khmer"],
        groupings: ["asean"],
        neighbors: ["THA", "LAO", "VNM"],
        un_member: true,
        data_available: true
    },
    {
        code: "LAO",
        name: "Laos",
        official_name: "Lao People's Democratic Republic",
        flag: "🇱🇦",
        capital: "Vientiane",
        region: "asia",
        subregion: "Southeast Asia",
        population: 7633779,
        area_km2: 236800,
        gdp_usd: 15843000000,
        currency: "Kip (LAK)",
        languages: ["Lao"],
        groupings: ["asean"],
        neighbors: ["CHN", "MMR", "THA", "KHM", "VNM"],
        un_member: true,
        data_available: true
    },
    {
        code: "BRN",
        name: "Brunei",
        official_name: "Brunei Darussalam",
        flag: "🇧🇳",
        capital: "Bandar Seri Begawan",
        region: "asia",
        subregion: "Southeast Asia",
        population: 449002,
        area_km2: 5765,
        gdp_usd: 14007000000,
        currency: "Dollar (BND)",
        languages: ["Malay", "English"],
        groupings: ["asean", "commonwealth", "oic"],
        neighbors: ["MYS"],
        un_member: true,
        data_available: true
    },
    {
        code: "TLS",
        name: "Timor-Leste",
        official_name: "Democratic Republic of Timor-Leste",
        flag: "🇹🇱",
        capital: "Dili",
        region: "asia",
        subregion: "Southeast Asia",
        population: 1360596,
        area_km2: 14874,
        gdp_usd: 3620000000,
        currency: "Dollar (USD)",
        languages: ["Tetum", "Portuguese"],
        groupings: [],
        neighbors: ["IDN"],
        un_member: true,
        data_available: true
    },
    {
        code: "QAT",
        name: "Qatar",
        official_name: "State of Qatar",
        flag: "🇶🇦",
        capital: "Doha",
        region: "asia",
        subregion: "Western Asia",
        population: 2716391,
        area_km2: 11586,
        gdp_usd: 235500000000,
        currency: "Riyal (QAR)",
        languages: ["Arabic"],
        groupings: ["opec", "oic", "gcc", "arab_league"],
        neighbors: ["SAU"],
        un_member: true,
        data_available: true
    },
    {
        code: "KWT",
        name: "Kuwait",
        official_name: "State of Kuwait",
        flag: "🇰🇼",
        capital: "Kuwait City",
        region: "asia",
        subregion: "Western Asia",
        population: 4310108,
        area_km2: 17818,
        gdp_usd: 175363000000,
        currency: "Dinar (KWD)",
        languages: ["Arabic"],
        groupings: ["opec", "oic", "gcc", "arab_league"],
        neighbors: ["SAU", "IRQ"],
        un_member: true,
        data_available: true
    },
    {
        code: "BHR",
        name: "Bahrain",
        official_name: "Kingdom of Bahrain",
        flag: "🇧🇭",
        capital: "Manama",
        region: "asia",
        subregion: "Western Asia",
        population: 1472233,
        area_km2: 786,
        gdp_usd: 44169000000,
        currency: "Dinar (BHD)",
        languages: ["Arabic"],
        groupings: ["oic", "gcc", "arab_league"],
        neighbors: [],
        un_member: true,
        data_available: true
    },
    {
        code: "OMN",
        name: "Oman",
        official_name: "Sultanate of Oman",
        flag: "🇴🇲",
        capital: "Muscat",
        region: "asia",
        subregion: "Western Asia",
        population: 4644384,
        area_km2: 309500,
        gdp_usd: 108192000000,
        currency: "Rial (OMR)",
        languages: ["Arabic"],
        groupings: ["oic", "gcc", "arab_league"],
        neighbors: ["SAU", "ARE", "YEM"],
        un_member: true,
        data_available: true
    },
    {
        code: "YEM",
        name: "Yemen",
        official_name: "Republic of Yemen",
        flag: "🇾🇪",
        capital: "Sana'a",
        region: "asia",
        subregion: "Western Asia",
        population: 34449825,
        area_km2: 527968,
        gdp_usd: 21606000000,
        currency: "Rial (YER)",
        languages: ["Arabic"],
        groupings: ["arab_league", "oic"],
        neighbors: ["SAU", "OMN"],
        un_member: true,
        data_available: true
    },
    {
        code: "JOR",
        name: "Jordan",
        official_name: "Hashemite Kingdom of Jordan",
        flag: "🇯🇴",
        capital: "Amman",
        region: "asia",
        subregion: "Western Asia",
        population: 11337052,
        area_km2: 89342,
        gdp_usd: 50814000000,
        currency: "Dinar (JOD)",
        languages: ["Arabic"],
        groupings: ["arab_league", "oic"],
        neighbors: ["SYR", "IRQ", "SAU", "ISR", "PSE"],
        un_member: true,
        data_available: true
    },
    {
        code: "LBN",
        name: "Lebanon",
        official_name: "Lebanese Republic",
        flag: "🇱🇧",
        capital: "Beirut",
        region: "asia",
        subregion: "Western Asia",
        population: 5489739,
        area_km2: 10452,
        gdp_usd: 23132000000,
        currency: "Pound (LBP)",
        languages: ["Arabic"],
        groupings: ["arab_league", "oic"],
        neighbors: ["SYR", "ISR"],
        un_member: true,
        data_available: true
    },
    {
        code: "SYR",
        name: "Syria",
        official_name: "Syrian Arab Republic",
        flag: "🇸🇾",
        capital: "Damascus",
        region: "asia",
        subregion: "Western Asia",
        population: 23227014,
        area_km2: 185180,
        gdp_usd: 11000000000,
        currency: "Pound (SYP)",
        languages: ["Arabic"],
        groupings: [],
        neighbors: ["TUR", "IRQ", "JOR", "ISR", "LBN"],
        un_member: true,
        data_available: true
    },
    {
        code: "AZE",
        name: "Azerbaijan",
        official_name: "Republic of Azerbaijan",
        flag: "🇦🇿",
        capital: "Baku",
        region: "asia",
        subregion: "Western Asia",
        population: 10353296,
        area_km2: 86600,
        gdp_usd: 78721000000,
        currency: "Manat (AZN)",
        languages: ["Azerbaijani"],
        groupings: ["oic"],
        neighbors: ["RUS", "GEO", "ARM", "IRN", "TUR"],
        un_member: true,
        data_available: true
    },
    {
        code: "ARM",
        name: "Armenia",
        official_name: "Republic of Armenia",
        flag: "🇦🇲",
        capital: "Yerevan",
        region: "asia",
        subregion: "Western Asia",
        population: 2777970,
        area_km2: 29743,
        gdp_usd: 24212000000,
        currency: "Dram (AMD)",
        languages: ["Armenian"],
        groupings: ["eaeu", "csto"],
        neighbors: ["GEO", "AZE", "IRN", "TUR"],
        un_member: true,
        data_available: true
    },
    {
        code: "GEO",
        name: "Georgia",
        official_name: "Georgia",
        flag: "🇬🇪",
        capital: "Tbilisi",
        region: "asia",
        subregion: "Western Asia",
        population: 3688647,
        area_km2: 69700,
        gdp_usd: 27947000000,
        currency: "Lari (GEL)",
        languages: ["Georgian"],
        groupings: [],
        neighbors: ["RUS", "AZE", "ARM", "TUR"],
        un_member: true,
        data_available: true
    }
];

// ==================== HELPER FUNCTIONS ====================

/**
 * Get country by code
 */
function getCountryByCode(code) {
    return COUNTRIES_DATA.find(c => c.code === code);
}

/**
 * Get countries by region
 */
function getCountriesByRegion(region) {
    if (region === 'all') return COUNTRIES_DATA;
    return COUNTRIES_DATA.filter(c => c.region === region);
}

/**
 * Get countries by grouping
 */
function getCountriesByGrouping(grouping) {
    if (grouping === 'all') return COUNTRIES_DATA;
    return COUNTRIES_DATA.filter(c => c.groupings && c.groupings.includes(grouping));
}

/**
 * Search countries by name
 */
function searchCountries(query) {
    const lowerQuery = query.toLowerCase();
    return COUNTRIES_DATA.filter(c => 
        c.name.toLowerCase().includes(lowerQuery) ||
        c.official_name.toLowerCase().includes(lowerQuery) ||
        c.code.toLowerCase().includes(lowerQuery) ||
        c.capital.toLowerCase().includes(lowerQuery)
    );
}

/**
 * Sort countries
 */
function sortCountries(countries, sortBy) {
    const sorted = [...countries];
    switch(sortBy) {
        case 'name-asc':
            return sorted.sort((a, b) => a.name.localeCompare(b.name));
        case 'name-desc':
            return sorted.sort((a, b) => b.name.localeCompare(a.name));
        case 'population':
            return sorted.sort((a, b) => b.population - a.population);
        case 'gdp':
            return sorted.sort((a, b) => b.gdp_usd - a.gdp_usd);
        case 'area':
            return sorted.sort((a, b) => b.area_km2 - a.area_km2);
        default:
            return sorted;
    }
}

/**
 * Format number with commas
 */
function formatNumber(num) {
    if (num >= 1e12) return (num / 1e12).toFixed(2) + 'T';
    if (num >= 1e9) return (num / 1e9).toFixed(2) + 'B';
    if (num >= 1e6) return (num / 1e6).toFixed(2) + 'M';
    if (num >= 1e3) return (num / 1e3).toFixed(2) + 'K';
    return num.toString();
}

/**
 * Get region display name
 */
function getRegionDisplayName(region) {
    const names = {
        'asia': 'Asia',
        'europe': 'Europe',
        'africa': 'Africa',
        'north-america': 'North America',
        'south-america': 'South America',
        'oceania': 'Oceania'
    };
    return names[region] || region;
}

/**
 * Get grouping display name
 */
function getGroupingDisplayName(grouping) {
    const names = {
        'g20': 'G20',
        'g7': 'G7',
        'brics': 'BRICS+',
        'nato': 'NATO',
        'eu': 'European Union',
        'asean': 'ASEAN',
        'saarc': 'SAARC',
        'sco': 'SCO',
        'quad': 'QUAD',
        'aukus': 'AUKUS',
        'opec': 'OPEC',
        'oic': 'OIC',
        'gcc': 'GCC',
        'au': 'African Union',
        'commonwealth': 'Commonwealth',
        'apec': 'APEC',
        'mercosur': 'MERCOSUR',
        'ecowas': 'ECOWAS',
        'sadc': 'SADC',
        'eac': 'EAC',
        'oecd': 'OECD',
        'nam': 'NAM',
        'five_eyes': 'Five Eyes',
        'arab_league': 'Arab League'
    };
    return names[grouping] || grouping.toUpperCase();
}

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
    module.exports = {
        COUNTRIES_DATA,
        getCountryByCode,
        getCountriesByRegion,
        getCountriesByGrouping,
        searchCountries,
        sortCountries,
        formatNumber,
        getRegionDisplayName,
        getGroupingDisplayName
    };
}

console.log(`✅ Country data loaded: ${COUNTRIES_DATA.length} countries`);
