/* =====================================================
   UNITY ATLAS - Countries Data Index & Registry
   Master file that indexes all country data
   ===================================================== */

const COUNTRIES_INDEX = {
    // ==================== AFRICA (54 countries) ====================
    DZA: { name: "Algeria", region: "africa", file: "DZA.json", loaded: false },
    AGO: { name: "Angola", region: "africa", file: "AGO.json", loaded: false },
    BEN: { name: "Benin", region: "africa", file: "BEN.json", loaded: false },
    BWA: { name: "Botswana", region: "africa", file: "BWA.json", loaded: false },
    BFA: { name: "Burkina Faso", region: "africa", file: "BFA.json", loaded: false },
    BDI: { name: "Burundi", region: "africa", file: "BDI.json", loaded: false },
    CPV: { name: "Cabo Verde", region: "africa", file: "CPV.json", loaded: false },
    CMR: { name: "Cameroon", region: "africa", file: "CMR.json", loaded: false },
    CAF: { name: "Central African Republic", region: "africa", file: "CAF.json", loaded: false },
    TCD: { name: "Chad", region: "africa", file: "TCD.json", loaded: false },
    COM: { name: "Comoros", region: "africa", file: "COM.json", loaded: false },
    COG: { name: "Congo", region: "africa", file: "COG.json", loaded: false },
    COD: { name: "DR Congo", region: "africa", file: "COD.json", loaded: false },
    CIV: { name: "Côte d'Ivoire", region: "africa", file: "CIV.json", loaded: false },
    DJI: { name: "Djibouti", region: "africa", file: "DJI.json", loaded: false },
    EGY: { name: "Egypt", region: "africa", file: "EGY.json", loaded: false },
    GNQ: { name: "Equatorial Guinea", region: "africa", file: "GNQ.json", loaded: false },
    ERI: { name: "Eritrea", region: "africa", file: "ERI.json", loaded: false },
    SWZ: { name: "Eswatini", region: "africa", file: "SWZ.json", loaded: false },
    ETH: { name: "Ethiopia", region: "africa", file: "ETH.json", loaded: false },
    GAB: { name: "Gabon", region: "africa", file: "GAB.json", loaded: false },
    GMB: { name: "Gambia", region: "africa", file: "GMB.json", loaded: false },
    GHA: { name: "Ghana", region: "africa", file: "GHA.json", loaded: false },
    GIN: { name: "Guinea", region: "africa", file: "GIN.json", loaded: false },
    GNB: { name: "Guinea-Bissau", region: "africa", file: "GNB.json", loaded: false },
    KEN: { name: "Kenya", region: "africa", file: "KEN.json", loaded: false },
    LSO: { name: "Lesotho", region: "africa", file: "LSO.json", loaded: false },
    LBR: { name: "Liberia", region: "africa", file: "LBR.json", loaded: false },
    LBY: { name: "Libya", region: "africa", file: "LBY.json", loaded: false },
    MDG: { name: "Madagascar", region: "africa", file: "MDG.json", loaded: false },
    MWI: { name: "Malawi", region: "africa", file: "MWI.json", loaded: false },
    MLI: { name: "Mali", region: "africa", file: "MLI.json", loaded: false },
    MRT: { name: "Mauritania", region: "africa", file: "MRT.json", loaded: false },
    MUS: { name: "Mauritius", region: "africa", file: "MUS.json", loaded: false },
    MAR: { name: "Morocco", region: "africa", file: "MAR.json", loaded: false },
    MOZ: { name: "Mozambique", region: "africa", file: "MOZ.json", loaded: false },
    NAM: { name: "Namibia", region: "africa", file: "NAM.json", loaded: false },
    NER: { name: "Niger", region: "africa", file: "NER.json", loaded: false },
    NGA: { name: "Nigeria", region: "africa", file: "NGA.json", loaded: false },
    RWA: { name: "Rwanda", region: "africa", file: "RWA.json", loaded: false },
    STP: { name: "São Tomé and Príncipe", region: "africa", file: "STP.json", loaded: false },
    SEN: { name: "Senegal", region: "africa", file: "SEN.json", loaded: false },
    SYC: { name: "Seychelles", region: "africa", file: "SYC.json", loaded: false },
    SLE: { name: "Sierra Leone", region: "africa", file: "SLE.json", loaded: false },
    SOM: { name: "Somalia", region: "africa", file: "SOM.json", loaded: false },
    ZAF: { name: "South Africa", region: "africa", file: "ZAF.json", loaded: false },
    SSD: { name: "South Sudan", region: "africa", file: "SSD.json", loaded: false },
    SDN: { name: "Sudan", region: "africa", file: "SDN.json", loaded: false },
    TZA: { name: "Tanzania", region: "africa", file: "TZA.json", loaded: false },
    TGO: { name: "Togo", region: "africa", file: "TGO.json", loaded: false },
    TUN: { name: "Tunisia", region: "africa", file: "TUN.json", loaded: false },
    UGA: { name: "Uganda", region: "africa", file: "UGA.json", loaded: false },
    ZMB: { name: "Zambia", region: "africa", file: "ZMB.json", loaded: false },
    ZWE: { name: "Zimbabwe", region: "africa", file: "ZWE.json", loaded: false },

    // ==================== ASIA (48 countries) ====================
    AFG: { name: "Afghanistan", region: "asia", file: "AFG.json", loaded: false },
    ARM: { name: "Armenia", region: "asia", file: "ARM.json", loaded: false },
    AZE: { name: "Azerbaijan", region: "asia", file: "AZE.json", loaded: false },
    BHR: { name: "Bahrain", region: "asia", file: "BHR.json", loaded: false },
    BGD: { name: "Bangladesh", region: "asia", file: "BGD.json", loaded: false },
    BTN: { name: "Bhutan", region: "asia", file: "BTN.json", loaded: false },
    BRN: { name: "Brunei", region: "asia", file: "BRN.json", loaded: false },
    KHM: { name: "Cambodia", region: "asia", file: "KHM.json", loaded: false },
    CHN: { name: "China", region: "asia", file: "CHN.json", loaded: false },
    CYP: { name: "Cyprus", region: "asia", file: "CYP.json", loaded: false },
    GEO: { name: "Georgia", region: "asia", file: "GEO.json", loaded: false },
    IND: { name: "India", region: "asia", file: "IND.json", loaded: false },
    IDN: { name: "Indonesia", region: "asia", file: "IDN.json", loaded: false },
    IRN: { name: "Iran", region: "asia", file: "IRN.json", loaded: false },
    IRQ: { name: "Iraq", region: "asia", file: "IRQ.json", loaded: false },
    ISR: { name: "Israel", region: "asia", file: "ISR.json", loaded: false },
    JPN: { name: "Japan", region: "asia", file: "JPN.json", loaded: false },
    JOR: { name: "Jordan", region: "asia", file: "JOR.json", loaded: false },
    KAZ: { name: "Kazakhstan", region: "asia", file: "KAZ.json", loaded: false },
    KWT: { name: "Kuwait", region: "asia", file: "KWT.json", loaded: false },
    KGZ: { name: "Kyrgyzstan", region: "asia", file: "KGZ.json", loaded: false },
    LAO: { name: "Laos", region: "asia", file: "LAO.json", loaded: false },
    LBN: { name: "Lebanon", region: "asia", file: "LBN.json", loaded: false },
    MYS: { name: "Malaysia", region: "asia", file: "MYS.json", loaded: false },
    MDV: { name: "Maldives", region: "asia", file: "MDV.json", loaded: false },
    MNG: { name: "Mongolia", region: "asia", file: "MNG.json", loaded: false },
    MMR: { name: "Myanmar", region: "asia", file: "MMR.json", loaded: false },
    NPL: { name: "Nepal", region: "asia", file: "NPL.json", loaded: false },
    PRK: { name: "North Korea", region: "asia", file: "PRK.json", loaded: false },
    OMN: { name: "Oman", region: "asia", file: "OMN.json", loaded: false },
    PAK: { name: "Pakistan", region: "asia", file: "PAK.json", loaded: false },
    PHL: { name: "Philippines", region: "asia", file: "PHL.json", loaded: false },
    QAT: { name: "Qatar", region: "asia", file: "QAT.json", loaded: false },
    SAU: { name: "Saudi Arabia", region: "asia", file: "SAU.json", loaded: false },
    SGP: { name: "Singapore", region: "asia", file: "SGP.json", loaded: false },
    KOR: { name: "South Korea", region: "asia", file: "KOR.json", loaded: false },
    LKA: { name: "Sri Lanka", region: "asia", file: "LKA.json", loaded: false },
    SYR: { name: "Syria", region: "asia", file: "SYR.json", loaded: false },
    TWN: { name: "Taiwan", region: "asia", file: "TWN.json", loaded: false },
    TJK: { name: "Tajikistan", region: "asia", file: "TJK.json", loaded: false },
    THA: { name: "Thailand", region: "asia", file: "THA.json", loaded: false },
    TLS: { name: "Timor-Leste", region: "asia", file: "TLS.json", loaded: false },
    TUR: { name: "Turkey", region: "asia", file: "TUR.json", loaded: false },
    TKM: { name: "Turkmenistan", region: "asia", file: "TKM.json", loaded: false },
    ARE: { name: "United Arab Emirates", region: "asia", file: "ARE.json", loaded: false },
    UZB: { name: "Uzbekistan", region: "asia", file: "UZB.json", loaded: false },
    VNM: { name: "Vietnam", region: "asia", file: "VNM.json", loaded: false },
    YEM: { name: "Yemen", region: "asia", file: "YEM.json", loaded: false },

    // ==================== EUROPE (44 countries) ====================
    ALB: { name: "Albania", region: "europe", file: "ALB.json", loaded: false },
    AND: { name: "Andorra", region: "europe", file: "AND.json", loaded: false },
    AUT: { name: "Austria", region: "europe", file: "AUT.json", loaded: false },
    BLR: { name: "Belarus", region: "europe", file: "BLR.json", loaded: false },
    BEL: { name: "Belgium", region: "europe", file: "BEL.json", loaded: false },
    BIH: { name: "Bosnia and Herzegovina", region: "europe", file: "BIH.json", loaded: false },
    BGR: { name: "Bulgaria", region: "europe", file: "BGR.json", loaded: false },
    HRV: { name: "Croatia", region: "europe", file: "HRV.json", loaded: false },
    CZE: { name: "Czechia", region: "europe", file: "CZE.json", loaded: false },
    DNK: { name: "Denmark", region: "europe", file: "DNK.json", loaded: false },
    EST: { name: "Estonia", region: "europe", file: "EST.json", loaded: false },
    FIN: { name: "Finland", region: "europe", file: "FIN.json", loaded: false },
    FRA: { name: "France", region: "europe", file: "FRA.json", loaded: false },
    DEU: { name: "Germany", region: "europe", file: "DEU.json", loaded: false },
    GRC: { name: "Greece", region: "europe", file: "GRC.json", loaded: false },
    HUN: { name: "Hungary", region: "europe", file: "HUN.json", loaded: false },
    ISL: { name: "Iceland", region: "europe", file: "ISL.json", loaded: false },
    IRL: { name: "Ireland", region: "europe", file: "IRL.json", loaded: false },
    ITA: { name: "Italy", region: "europe", file: "ITA.json", loaded: false },
    LVA: { name: "Latvia", region: "europe", file: "LVA.json", loaded: false },
    LIE: { name: "Liechtenstein", region: "europe", file: "LIE.json", loaded: false },
    LTU: { name: "Lithuania", region: "europe", file: "LTU.json", loaded: false },
    LUX: { name: "Luxembourg", region: "europe", file: "LUX.json", loaded: false },
    MLT: { name: "Malta", region: "europe", file: "MLT.json", loaded: false },
    MDA: { name: "Moldova", region: "europe", file: "MDA.json", loaded: false },
    MCO: { name: "Monaco", region: "europe", file: "MCO.json", loaded: false },
    MNE: { name: "Montenegro", region: "europe", file: "MNE.json", loaded: false },
    NLD: { name: "Netherlands", region: "europe", file: "NLD.json", loaded: false },
    MKD: { name: "North Macedonia", region: "europe", file: "MKD.json", loaded: false },
    NOR: { name: "Norway", region: "europe", file: "NOR.json", loaded: false },
    POL: { name: "Poland", region: "europe", file: "POL.json", loaded: false },
    PRT: { name: "Portugal", region: "europe", file: "PRT.json", loaded: false },
    ROU: { name: "Romania", region: "europe", file: "ROU.json", loaded: false },
    RUS: { name: "Russia", region: "europe", file: "RUS.json", loaded: false },
    SMR: { name: "San Marino", region: "europe", file: "SMR.json", loaded: false },
    SRB: { name: "Serbia", region: "europe", file: "SRB.json", loaded: false },
    SVK: { name: "Slovakia", region: "europe", file: "SVK.json", loaded: false },
    SVN: { name: "Slovenia", region: "europe", file: "SVN.json", loaded: false },
    ESP: { name: "Spain", region: "europe", file: "ESP.json", loaded: false },
    SWE: { name: "Sweden", region: "europe", file: "SWE.json", loaded: false },
    CHE: { name: "Switzerland", region: "europe", file: "CHE.json", loaded: false },
    UKR: { name: "Ukraine", region: "europe", file: "UKR.json", loaded: false },
    GBR: { name: "United Kingdom", region: "europe", file: "GBR.json", loaded: false },
    VAT: { name: "Vatican City", region: "europe", file: "VAT.json", loaded: false },

    // ==================== NORTH AMERICA (23 countries) ====================
    ATG: { name: "Antigua and Barbuda", region: "north-america", file: "ATG.json", loaded: false },
    BHS: { name: "Bahamas", region: "north-america", file: "BHS.json", loaded: false },
    BRB: { name: "Barbados", region: "north-america", file: "BRB.json", loaded: false },
    BLZ: { name: "Belize", region: "north-america", file: "BLZ.json", loaded: false },
    CAN: { name: "Canada", region: "north-america", file: "CAN.json", loaded: false },
    CRI: { name: "Costa Rica", region: "north-america", file: "CRI.json", loaded: false },
    CUB: { name: "Cuba", region: "north-america", file: "CUB.json", loaded: false },
    DMA: { name: "Dominica", region: "north-america", file: "DMA.json", loaded: false },
    DOM: { name: "Dominican Republic", region: "north-america", file: "DOM.json", loaded: false },
    SLV: { name: "El Salvador", region: "north-america", file: "SLV.json", loaded: false },
    GRD: { name: "Grenada", region: "north-america", file: "GRD.json", loaded: false },
    GTM: { name: "Guatemala", region: "north-america", file: "GTM.json", loaded: false },
    HTI: { name: "Haiti", region: "north-america", file: "HTI.json", loaded: false },
    HND: { name: "Honduras", region: "north-america", file: "HND.json", loaded: false },
    JAM: { name: "Jamaica", region: "north-america", file: "JAM.json", loaded: false },
    MEX: { name: "Mexico", region: "north-america", file: "MEX.json", loaded: false },
    NIC: { name: "Nicaragua", region: "north-america", file: "NIC.json", loaded: false },
    PAN: { name: "Panama", region: "north-america", file: "PAN.json", loaded: false },
    KNA: { name: "Saint Kitts and Nevis", region: "north-america", file: "KNA.json", loaded: false },
    LCA: { name: "Saint Lucia", region: "north-america", file: "LCA.json", loaded: false },
    VCT: { name: "Saint Vincent and the Grenadines", region: "north-america", file: "VCT.json", loaded: false },
    TTO: { name: "Trinidad and Tobago", region: "north-america", file: "TTO.json", loaded: false },
    USA: { name: "United States", region: "north-america", file: "USA.json", loaded: false },

    // ==================== SOUTH AMERICA (12 countries) ====================
    ARG: { name: "Argentina", region: "south-america", file: "ARG.json", loaded: false },
    BOL: { name: "Bolivia", region: "south-america", file: "BOL.json", loaded: false },
    BRA: { name: "Brazil", region: "south-america", file: "BRA.json", loaded: false },
    CHL: { name: "Chile", region: "south-america", file: "CHL.json", loaded: false },
    COL: { name: "Colombia", region: "south-america", file: "COL.json", loaded: false },
    ECU: { name: "Ecuador", region: "south-america", file: "ECU.json", loaded: false },
    GUY: { name: "Guyana", region: "south-america", file: "GUY.json", loaded: false },
    PRY: { name: "Paraguay", region: "south-america", file: "PRY.json", loaded: false },
    PER: { name: "Peru", region: "south-america", file: "PER.json", loaded: false },
    SUR: { name: "Suriname", region: "south-america", file: "SUR.json", loaded: false },
    URY: { name: "Uruguay", region: "south-america", file: "URY.json", loaded: false },
    VEN: { name: "Venezuela", region: "south-america", file: "VEN.json", loaded: false },

    // ==================== OCEANIA (14 countries) ====================
    AUS: { name: "Australia", region: "oceania", file: "AUS.json", loaded: false },
    FJI: { name: "Fiji", region: "oceania", file: "FJI.json", loaded: false },
    KIR: { name: "Kiribati", region: "oceania", file: "KIR.json", loaded: false },
    MHL: { name: "Marshall Islands", region: "oceania", file: "MHL.json", loaded: false },
    FSM: { name: "Micronesia", region: "oceania", file: "FSM.json", loaded: false },
    NRU: { name: "Nauru", region: "oceania", file: "NRU.json", loaded: false },
    NZL: { name: "New Zealand", region: "oceania", file: "NZL.json", loaded: false },
    PLW: { name: "Palau", region: "oceania", file: "PLW.json", loaded: false },
    PNG: { name: "Papua New Guinea", region: "oceania", file: "PNG.json", loaded: false },
    WSM: { name: "Samoa", region: "oceania", file: "WSM.json", loaded: false },
    SLB: { name: "Solomon Islands", region: "oceania", file: "SLB.json", loaded: false },
    TON: { name: "Tonga", region: "oceania", file: "TON.json", loaded: false },
    TUV: { name: "Tuvalu", region: "oceania", file: "TUV.json", loaded: false },
    VUT: { name: "Vanuatu", region: "oceania", file: "VUT.json", loaded: false }
};

// Organizations Data (kept in main file as it's smaller)
const ORGANIZATIONS_DATA = {
    UN: { code: "UN", name: "United Nations", abbr: "UN", type: "political", founded: 1945, headquarters: "New York, USA", members: 193, logo: "🇺🇳", color: "#009EDB" },
    EU: { code: "EU", name: "European Union", abbr: "EU", type: "political", founded: 1993, headquarters: "Brussels, Belgium", members: 27, logo: "🇪🇺", color: "#003399" },
    NATO: { code: "NATO", name: "North Atlantic Treaty Organization", abbr: "NATO", type: "military", founded: 1949, headquarters: "Brussels, Belgium", members: 32, logo: "🔵", color: "#004990" },
    BRICS: { code: "BRICS", name: "BRICS", abbr: "BRICS", type: "economic", founded: 2009, headquarters: "Rotating", members: 10, logo: "🌍", color: "#009639" },
    G20: { code: "G20", name: "Group of Twenty", abbr: "G20", type: "economic", founded: 1999, headquarters: "Rotating", members: 20, logo: "💹", color: "#1B4F72" },
    G7: { code: "G7", name: "Group of Seven", abbr: "G7", type: "economic", founded: 1975, headquarters: "Rotating", members: 7, logo: "🏛️", color: "#2E86AB" },
    ASEAN: { code: "ASEAN", name: "Association of Southeast Asian Nations", abbr: "ASEAN", type: "regional", founded: 1967, headquarters: "Jakarta, Indonesia", members: 10, logo: "🌏", color: "#003B71" },
    AU: { code: "AU", name: "African Union", abbr: "AU", type: "regional", founded: 2002, headquarters: "Addis Ababa, Ethiopia", members: 55, logo: "🌍", color: "#009A44" },
    OPEC: { code: "OPEC", name: "Organization of the Petroleum Exporting Countries", abbr: "OPEC", type: "economic", founded: 1960, headquarters: "Vienna, Austria", members: 13, logo: "🛢️", color: "#005DAA" },
    OECD: { code: "OECD", name: "Organisation for Economic Co-operation and Development", abbr: "OECD", type: "economic", founded: 1961, headquarters: "Paris, France", members: 38, logo: "📊", color: "#0066B3" },
    CW: { code: "CW", name: "Commonwealth of Nations", abbr: "CW", type: "political", founded: 1931, headquarters: "London, UK", members: 56, logo: "👑", color: "#00247D" },
    SCO: { code: "SCO", name: "Shanghai Cooperation Organisation", abbr: "SCO", type: "political", founded: 2001, headquarters: "Beijing, China", members: 10, logo: "🏛️", color: "#003366" },
    AL: { code: "AL", name: "Arab League", abbr: "AL", type: "regional", founded: 1945, headquarters: "Cairo, Egypt", members: 22, logo: "🌙", color: "#006233" },
    GCC: { code: "GCC", name: "Gulf Cooperation Council", abbr: "GCC", type: "regional", founded: 1981, headquarters: "Riyadh, Saudi Arabia", members: 6, logo: "🏛️", color: "#008751" },
    SAARC: { code: "SAARC", name: "South Asian Association for Regional Cooperation", abbr: "SAARC", type: "regional", founded: 1985, headquarters: "Kathmandu, Nepal", members: 8, logo: "🌏", color: "#FF9933" },
    EAC: { code: "EAC", name: "East African Community", abbr: "EAC", type: "regional", founded: 2000, headquarters: "Arusha, Tanzania", members: 8, logo: "🌍", color: "#006B3F" },
    SADC: { code: "SADC", name: "Southern African Development Community", abbr: "SADC", type: "regional", founded: 1992, headquarters: "Gaborone, Botswana", members: 16, logo: "🌍", color: "#0033A0" },
    ECOWAS: { code: "ECOWAS", name: "Economic Community of West African States", abbr: "ECOWAS", type: "regional", founded: 1975, headquarters: "Abuja, Nigeria", members: 15, logo: "🌍", color: "#008751" },
    MERCOSUR: { code: "MERCOSUR", name: "Southern Common Market", abbr: "MERCOSUR", type: "economic", founded: 1991, headquarters: "Montevideo, Uruguay", members: 4, logo: "🌎", color: "#0073CE" },
    OAS: { code: "OAS", name: "Organization of American States", abbr: "OAS", type: "regional", founded: 1948, headquarters: "Washington, D.C., USA", members: 35, logo: "🌎", color: "#003087" },
    APEC: { code: "APEC", name: "Asia-Pacific Economic Cooperation", abbr: "APEC", type: "economic", founded: 1989, headquarters: "Singapore", members: 21, logo: "🌏", color: "#003D7C" },
    CIS: { code: "CIS", name: "Commonwealth of Independent States", abbr: "CIS", type: "political", founded: 1991, headquarters: "Minsk, Belarus", members: 9, logo: "🏛️", color: "#4682B4" },
    EAEU: { code: "EAEU", name: "Eurasian Economic Union", abbr: "EAEU", type: "economic", founded: 2015, headquarters: "Moscow, Russia", members: 5, logo: "🌍", color: "#003580" },
    CARICOM: { code: "CARICOM", name: "Caribbean Community", abbr: "CARICOM", type: "regional", founded: 1973, headquarters: "Georgetown, Guyana", members: 15, logo: "🌴", color: "#00A550" },
    QUAD: { code: "QUAD", name: "Quadrilateral Security Dialogue", abbr: "QUAD", type: "military", founded: 2007, headquarters: "Rotating", members: 4, logo: "🛡️", color: "#1E3A5F" },
    EFTA: { code: "EFTA", name: "European Free Trade Association", abbr: "EFTA", type: "economic", founded: 1960, headquarters: "Geneva, Switzerland", members: 4, logo: "🇪🇺", color: "#003399" }
};

// Regions Data
const REGIONS_DATA = {
    africa: { name: "Africa", icon: "🌍", countries: 54, color: "#009639" },
    asia: { name: "Asia", icon: "🌏", countries: 48, color: "#D4AF37" },
    europe: { name: "Europe", icon: "🌍", countries: 44, color: "#003399" },
    "north-america": { name: "North America", icon: "🌎", countries: 23, color: "#B22234" },
    "south-america": { name: "South America", icon: "🌎", countries: 12, color: "#009B3A" },
    oceania: { name: "Oceania", icon: "🌏", countries: 14, color: "#00247D" }
};

// Data statistics
const DATA_STATS = {
    totalCountries: 195,
    totalOrganizations: 26,
    totalRegions: 6,
    lastUpdated: "2025-01-01",
    version: "2.0.0"
};

// Export for module usage
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { COUNTRIES_INDEX, ORGANIZATIONS_DATA, REGIONS_DATA, DATA_STATS };
}
