// ============================================
// LAKES DATA - FILE 4 (Lakes 31-40)
// ============================================

const lakesData4 = [
    {
        id: 'lake-onega',
        name: 'Lake Onega',
        countries: [{ name: 'Russia', code: 'RU' }],
        continent: 'Europe',
        waterType: 'freshwater',
        lakeType: 'Glacial/Tectonic',
        surfaceArea: 9700,
        maxDepth: 127,
        avgDepth: 30,
        volume: 295,
        elevation: 33,
        coordinates: [61.5, 35.5],
        defaultZoom: 7,
        image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400',
        backgroundImage: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1920',
        geoJSON: { type: 'Feature', properties: { name: 'Lake Onega' }, geometry: { type: 'Polygon', coordinates: [[[34.0, 62.5], [36.0, 62.0], [36.5, 61.0], [35.5, 60.5], [34.0, 61.0], [33.5, 62.0], [34.0, 62.5]]] } },
        inflowRivers: [{ name: 'Shuya River', length: 194, coordinates: [[34.0, 62.5], [34.5, 62.0], [35.0, 61.5]] }],
        outflowRivers: [{ name: 'Svir River', length: 224, coordinates: [[35.0, 60.8], [34.0, 60.5], [33.0, 60.2]] }],
        basinArea: 53000,
        islands: [{ name: 'Kizhi Island', coordinates: [62.07, 35.22], area: 5, description: 'UNESCO World Heritage wooden churches' }],
        cities: [{ name: 'Petrozavodsk', coordinates: [61.7849, 34.3469], country: 'Russia', population: 280000 }],
        biodiversity: [{ label: 'Fish Species', value: 'Salmon, Trout, Pike' }],
        economicImportance: [{ label: 'Tourism', value: 'Kizhi UNESCO site' }, { label: 'Shipping', value: 'Volga-Baltic Waterway' }],
        environmentalIssues: [{ label: 'Industrial Pollution', value: 'Pulp mills' }],
        waterDisputes: [],
        historicalImportance: [{ label: 'Kizhi Churches', value: '18th century wooden architecture' }]
    },
    {
        id: 'crater-lake',
        name: 'Crater Lake',
        countries: [{ name: 'United States', code: 'US' }],
        continent: 'North America',
        waterType: 'freshwater',
        lakeType: 'Volcanic (Caldera)',
        surfaceArea: 53,
        maxDepth: 594,
        avgDepth: 350,
        volume: 19,
        elevation: 1883,
        coordinates: [42.94, -122.1],
        defaultZoom: 11,
        image: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=400',
        backgroundImage: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=1920',
        geoJSON: { type: 'Feature', properties: { name: 'Crater Lake' }, geometry: { type: 'Polygon', coordinates: [[[-122.2, 43.0], [-122.05, 42.98], [-122.0, 42.9], [-122.1, 42.85], [-122.2, 42.88], [-122.25, 42.95], [-122.2, 43.0]]] } },
        inflowRivers: [],
        outflowRivers: [],
        basinArea: 67,
        islands: [{ name: 'Wizard Island', coordinates: [42.94, -122.16], area: 1.3, description: 'Volcanic cinder cone' }],
        cities: [],
        biodiversity: [{ label: 'Water Clarity', value: 'One of clearest in world' }, { label: 'Fish', value: 'Introduced Rainbow Trout, Kokanee' }],
        economicImportance: [{ label: 'Tourism', value: 'National Park - 700,000 visitors/year' }],
        environmentalIssues: [{ label: 'Introduced Species', value: 'Non-native fish' }],
        waterDisputes: [],
        historicalImportance: [{ label: 'Mount Mazama', value: 'Collapsed 7,700 years ago' }, { label: 'Deepest in US', value: 'Also clearest' }]
    },
    {
        id: 'lake-toba',
        name: 'Lake Toba',
        countries: [{ name: 'Indonesia', code: 'ID' }],
        continent: 'Asia',
        waterType: 'freshwater',
        lakeType: 'Volcanic (Caldera)',
        surfaceArea: 1130,
        maxDepth: 505,
        avgDepth: 200,
        volume: 240,
        elevation: 905,
        coordinates: [2.6, 98.8],
        defaultZoom: 9,
        image: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=400',
        backgroundImage: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1920',
        geoJSON: { type: 'Feature', properties: { name: 'Lake Toba' }, geometry: { type: 'Polygon', coordinates: [[[98.3, 2.9], [99.0, 2.8], [99.3, 2.5], [99.0, 2.3], [98.5, 2.4], [98.2, 2.7], [98.3, 2.9]]] } },
        inflowRivers: [{ name: 'Multiple streams', length: 50, coordinates: [[98.5, 3.0], [98.6, 2.8], [98.7, 2.6]] }],
        outflowRivers: [{ name: 'Asahan River', length: 147, coordinates: [[99.2, 2.5], [99.5, 2.3], [99.8, 2.0]] }],
        basinArea: 3658,
        islands: [{ name: 'Samosir Island', coordinates: [2.62, 98.73], area: 630, description: 'Island within an island' }],
        cities: [{ name: 'Parapat', coordinates: [2.66, 98.93], country: 'Indonesia', population: 15000 }],
        biodiversity: [{ label: 'Endemic Species', value: 'Toba carp' }, { label: 'Bird Species', value: 'Various migratory' }],
        economicImportance: [{ label: 'Tourism', value: 'Major tourist destination' }, { label: 'Fishing', value: 'Aquaculture' }],
        environmentalIssues: [{ label: 'Aquaculture Pollution', value: 'Fish farms impact' }],
        waterDisputes: [],
        historicalImportance: [{ label: 'Supervolcano', value: '74,000 years ago eruption' }, { label: 'Batak Culture', value: 'Traditional homeland' }]
    },
    {
        id: 'lake-kivu',
        name: 'Lake Kivu',
        countries: [{ name: 'Rwanda', code: 'RW' }, { name: 'Democratic Republic of Congo', code: 'CD' }],
        continent: 'Africa',
        waterType: 'freshwater',
        lakeType: 'Tectonic (Rift Valley)',
        surfaceArea: 2700,
        maxDepth: 480,
        avgDepth: 240,
        volume: 560,
        elevation: 1460,
        coordinates: [-2.0, 29.0],
        defaultZoom: 9,
        image: 'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=400',
        backgroundImage: 'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=1920',
        geoJSON: { type: 'Feature', properties: { name: 'Lake Kivu' }, geometry: { type: 'Polygon', coordinates: [[[28.8, -1.5], [29.3, -1.7], [29.4, -2.3], [29.1, -2.5], [28.8, -2.2], [28.7, -1.8], [28.8, -1.5]]] } },
        inflowRivers: [{ name: 'Multiple rivers', length: 100, coordinates: [[29.0, -1.5], [29.1, -1.7], [29.2, -1.9]] }],
        outflowRivers: [{ name: 'Ruzizi River', length: 117, coordinates: [[29.0, -2.5], [29.1, -2.8], [29.2, -3.0]] }],
        basinArea: 5097,
        islands: [{ name: 'Idjwi Island', coordinates: [-2.1, 29.05], area: 285, description: 'Second largest island in African lake' }],
        cities: [{ name: 'Goma', coordinates: [-1.68, 29.23], country: 'DR Congo', population: 1000000 }, { name: 'Bukavu', coordinates: [-2.5, 28.85], country: 'DR Congo', population: 870000 }, { name: 'Gisenyi', coordinates: [-1.7, 29.25], country: 'Rwanda', population: 85000 }],
        biodiversity: [{ label: 'Methane', value: 'Dissolved gas in deep water' }, { label: 'Fish', value: 'Sardine-like fish' }],
        economicImportance: [{ label: 'Methane Extraction', value: 'Power generation project' }, { label: 'Tourism', value: 'Gorilla trekking base' }],
        environmentalIssues: [{ label: 'Limnic Eruption Risk', value: 'Methane gas danger' }, { label: 'Volcanic Activity', value: 'Mount Nyiragongo nearby' }],
        waterDisputes: [{ label: 'Rwanda-DRC', value: 'Border tensions' }],
        historicalImportance: [{ label: 'Genocide Memorial', value: 'Regional history' }, { label: 'Volcanic Origin', value: 'Formed by lava blocking drainage' }]
    },
    {
        id: 'lake-edward',
        name: 'Lake Edward',
        countries: [{ name: 'Uganda', code: 'UG' }, { name: 'Democratic Republic of Congo', code: 'CD' }],
        continent: 'Africa',
        waterType: 'freshwater',
        lakeType: 'Tectonic (Rift Valley)',
        surfaceArea: 2325,
        maxDepth: 117,
        avgDepth: 40,
        volume: 78,
        elevation: 912,
        coordinates: [-0.4, 29.55],
        defaultZoom: 9,
        image: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=400',
        backgroundImage: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1920',
        geoJSON: { type: 'Feature', properties: { name: 'Lake Edward' }, geometry: { type: 'Polygon', coordinates: [[[29.2, 0.0], [29.8, -0.2], [30.0, -0.5], [29.7, -0.8], [29.3, -0.6], [29.1, -0.2], [29.2, 0.0]]] } },
        inflowRivers: [{ name: 'Ishasha River', length: 100, coordinates: [[29.5, -1.0], [29.6, -0.7], [29.7, -0.5]] }],
        outflowRivers: [{ name: 'Semliki River', length: 140, coordinates: [[29.5, 0.0], [29.8, 0.5], [30.0, 1.0]] }],
        basinArea: 12096,
        islands: [],
        cities: [],
        biodiversity: [{ label: 'Hippos', value: 'Large population' }, { label: 'Crocodiles', value: 'Nile crocodiles' }, { label: 'Fish Species', value: 'Tilapia, Nile Perch' }],
        economicImportance: [{ label: 'Fishing', value: 'Local communities' }, { label: 'Wildlife Tourism', value: 'Queen Elizabeth National Park' }],
        environmentalIssues: [{ label: 'Oil Exploration', value: 'Environmental concerns' }, { label: 'Overfishing', value: 'Declining stocks' }],
        waterDisputes: [],
        historicalImportance: [{ label: 'Named After', value: 'King Edward VII (1888)' }]
    },
    {
        id: 'lake-urmia',
        name: 'Lake Urmia',
        countries: [{ name: 'Iran', code: 'IR' }],
        continent: 'Asia',
        waterType: 'saltwater',
        lakeType: 'Endorheic',
        surfaceArea: 5200,
        maxDepth: 16,
        avgDepth: 6,
        volume: 30,
        elevation: 1274,
        coordinates: [37.7, 45.3],
        defaultZoom: 8,
        image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400',
        backgroundImage: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1920',
        geoJSON: { type: 'Feature', properties: { name: 'Lake Urmia' }, geometry: { type: 'Polygon', coordinates: [[[44.8, 38.2], [45.5, 38.0], [46.0, 37.5], [45.5, 37.0], [44.8, 37.3], [44.6, 37.8], [44.8, 38.2]]] } },
        inflowRivers: [{ name: 'Zarrineh River', length: 300, coordinates: [[46.5, 36.5], [46.0, 37.0], [45.5, 37.5]] }],
        outflowRivers: [],
        basinArea: 51876,
        islands: [{ name: 'Shahi Island', coordinates: [37.45, 45.5], area: 20 }],
        cities: [{ name: 'Urmia', coordinates: [37.5527, 45.0761], country: 'Iran', population: 750000 }, { name: 'Tabriz', coordinates: [38.08, 46.2919], country: 'Iran', population: 1560000 }],
        biodiversity: [{ label: 'Artemia', value: 'Brine shrimp population' }, { label: 'Flamingos', value: 'Major feeding ground' }],
        economicImportance: [{ label: 'Tourism', value: 'Historical significance' }, { label: 'Salt Production', value: 'Industrial use' }],
        environmentalIssues: [{ label: 'Dramatic Shrinkage', value: '90% loss since 1970s' }, { label: 'Dam Construction', value: 'Reduced inflow' }, { label: 'Dust Storms', value: 'Salt dust from dry bed' }],
        waterDisputes: [],
        historicalImportance: [{ label: 'Ancient', value: 'Known since antiquity' }, { label: 'UNESCO', value: 'Biosphere Reserve' }]
    },
    {
        id: 'lake-poyang',
        name: 'Lake Poyang',
        countries: [{ name: 'China', code: 'CN' }],
        continent: 'Asia',
        waterType: 'freshwater',
        lakeType: 'Floodplain',
        surfaceArea: 3500,
        maxDepth: 25,
        avgDepth: 8,
        volume: 27,
        elevation: 16,
        coordinates: [29.1, 116.3],
        defaultZoom: 8,
        image: 'https://images.unsplash.com/photo-1518495973542-4542c06a5843?w=400',
        backgroundImage: 'https://images.unsplash.com/photo-1518495973542-4542c06a5843?w=1920',
        geoJSON: { type: 'Feature', properties: { name: 'Lake Poyang' }, geometry: { type: 'Polygon', coordinates: [[[115.8, 29.5], [116.5, 29.3], [116.8, 28.8], [116.3, 28.5], [115.8, 28.8], [115.6, 29.2], [115.8, 29.5]]] } },
        inflowRivers: [{ name: 'Gan River', length: 751, coordinates: [[115.5, 28.0], [115.8, 28.5], [116.0, 29.0]] }],
        outflowRivers: [{ name: 'To Yangtze', length: 20, coordinates: [[116.5, 29.5], [116.8, 29.7], [117.0, 30.0]] }],
        basinArea: 162000,
        islands: [],
        cities: [{ name: 'Nanchang', coordinates: [28.6829, 115.8579], country: 'China', population: 5500000 }, { name: 'Jiujiang', coordinates: [29.7052, 116.0019], country: 'China', population: 520000 }],
        biodiversity: [{ label: 'Siberian Cranes', value: '95% of world population winters here' }, { label: 'Porpoise', value: 'Yangtze finless porpoise' }],
        economicImportance: [{ label: 'Fishing', value: 'Major freshwater fishery' }, { label: 'Flood Control', value: 'Yangtze buffer' }],
        environmentalIssues: [{ label: 'Three Gorges Dam', value: 'Changed water levels' }, { label: 'Sand Mining', value: 'Ecological damage' }],
        waterDisputes: [],
        historicalImportance: [{ label: 'Largest in China', value: 'During flood season' }, { label: 'Migratory Birds', value: 'Ramsar Wetland' }]
    },
    {
        id: 'lake-volta',
        name: 'Lake Volta',
        countries: [{ name: 'Ghana', code: 'GH' }],
        continent: 'Africa',
        waterType: 'freshwater',
        lakeType: 'Artificial (Reservoir)',
        surfaceArea: 8502,
        maxDepth: 75,
        avgDepth: 19,
        volume: 148,
        elevation: 84,
        coordinates: [7.0, -0.1],
        defaultZoom: 7,
        image: 'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=400',
        backgroundImage: 'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=1920',
        geoJSON: { type: 'Feature', properties: { name: 'Lake Volta' }, geometry: { type: 'Polygon', coordinates: [[[-0.5, 9.0], [0.3, 8.5], [0.5, 7.5], [0.2, 6.5], [-0.3, 6.3], [-0.8, 7.0], [-0.6, 8.0], [-0.5, 9.0]]] } },
        inflowRivers: [{ name: 'Volta River', length: 1600, coordinates: [[-1.0, 9.5], [-0.5, 9.0], [0.0, 8.5]] }],
        outflowRivers: [{ name: 'Volta River (below dam)', length: 100, coordinates: [[0.0, 6.3], [0.5, 6.0], [1.0, 5.7]] }],
        basinArea: 385000,
        islands: [{ name: 'Dodi Island', coordinates: [7.5, 0.3], area: 5 }],
        cities: [{ name: 'Akosombo', coordinates: [6.2917, 0.0500], country: 'Ghana', population: 25000 }],
        biodiversity: [{ label: 'Fish Species', value: 'Tilapia, Catfish' }, { label: 'Bird Species', value: 'Waterfowl, Herons' }],
        economicImportance: [{ label: 'Hydropower', value: 'Akosombo Dam - 1,020 MW' }, { label: 'Fishing', value: 'Major fishery' }, { label: 'Transport', value: 'Lake ferry services' }],
        environmentalIssues: [{ label: 'Resettlement', value: '80,000 people displaced' }, { label: 'Aquatic Weeds', value: 'Water hyacinth' }],
        waterDisputes: [],
        historicalImportance: [{ label: 'Created', value: '1965 - Akosombo Dam' }, { label: 'Largest by Surface', value: 'Largest artificial lake by area' }]
    },
    {
        id: 'lake-kariba',
        name: 'Lake Kariba',
        countries: [{ name: 'Zimbabwe', code: 'ZW' }, { name: 'Zambia', code: 'ZM' }],
        continent: 'Africa',
        waterType: 'freshwater',
        lakeType: 'Artificial (Reservoir)',
        surfaceArea: 5580,
        maxDepth: 97,
        avgDepth: 31,
        volume: 185,
        elevation: 485,
        coordinates: [-16.9, 28.0],
        defaultZoom: 7,
        image: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=400',
        backgroundImage: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1920',
        geoJSON: { type: 'Feature', properties: { name: 'Lake Kariba' }, geometry: { type: 'Polygon', coordinates: [[[26.5, -16.5], [28.0, -16.3], [29.5, -16.8], [29.5, -17.5], [28.0, -17.3], [26.5, -16.8], [26.5, -16.5]]] } },
        inflowRivers: [{ name: 'Zambezi River', length: 2574, coordinates: [[25.5, -16.0], [26.5, -16.3], [27.5, -16.5]] }],
        outflowRivers: [{ name: 'Zambezi River (below dam)', length: 500, coordinates: [[29.5, -17.0], [30.5, -17.5], [32.0, -18.0]] }],
        basinArea: 663000,
        islands: [],
        cities: [{ name: 'Kariba', coordinates: [-16.52, 28.79], country: 'Zimbabwe', population: 26000 }, { name: 'Siavonga', coordinates: [-16.53, 28.72], country: 'Zambia', population: 14000 }],
        biodiversity: [{ label: 'Fish Species', value: 'Kapenta (introduced), Tigerfish' }, { label: 'Crocodiles', value: 'Large population' }, { label: 'Operation Noah', value: '1959 animal rescue' }],
        economicImportance: [{ label: 'Hydropower', value: 'Kariba Dam - 1,626 MW' }, { label: 'Fishing', value: 'Kapenta industry' }, { label: 'Tourism', value: 'Houseboats, fishing trips' }],
        environmentalIssues: [{ label: 'Dam Structural', value: 'Needs rehabilitation' }, { label: 'Climate Change', value: 'Lower water levels' }],
        waterDisputes: [],
        historicalImportance: [{ label: 'Created', value: '1958 - Kariba Dam' }, { label: 'Largest by Volume', value: 'Largest artificial lake by volume' }]
    },
    {
        id: 'great-salt-lake',
        name: 'Great Salt Lake',
        countries: [{ name: 'United States', code: 'US' }],
        continent: 'North America',
        waterType: 'saltwater',
        lakeType: 'Endorheic',
        surfaceArea: 4400,
        maxDepth: 10,
        avgDepth: 5,
        volume: 19,
        elevation: 1280,
        coordinates: [41.1, -112.5],
        defaultZoom: 8,
        image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400',
        backgroundImage: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1920',
        geoJSON: { type: 'Feature', properties: { name: 'Great Salt Lake' }, geometry: { type: 'Polygon', coordinates: [[[-113.0, 41.5], [-112.2, 41.5], [-111.8, 41.0], [-112.2, 40.7], [-113.0, 40.8], [-113.2, 41.2], [-113.0, 41.5]]] } },
        inflowRivers: [{ name: 'Jordan River', length: 82, coordinates: [[-111.9, 40.5], [-112.0, 40.7], [-112.1, 41.0]] }, { name: 'Bear River', length: 563, coordinates: [[-112.0, 42.0], [-112.3, 41.5], [-112.5, 41.2]] }],
        outflowRivers: [],
        basinArea: 55000,
        islands: [{ name: 'Antelope Island', coordinates: [41.0, -112.25], area: 109 }, { name: 'Stansbury Island', coordinates: [40.85, -112.5], area: 57 }],
        cities: [{ name: 'Salt Lake City', coordinates: [40.7608, -111.8910], country: 'USA', population: 200000 }, { name: 'Ogden', coordinates: [41.223, -111.9738], country: 'USA', population: 87000 }],
        biodiversity: [{ label: 'Brine Shrimp', value: 'Major industry' }, { label: 'Birds', value: 'Millions of migratory birds' }],
        economicImportance: [{ label: 'Mineral Extraction', value: 'Salt, magnesium, potash' }, { label: 'Brine Shrimp', value: 'Fish food industry' }],
        environmentalIssues: [{ label: 'Shrinking', value: 'Record low levels 2022' }, { label: 'Toxic Dust', value: 'Heavy metals in lakebed' }],
        waterDisputes: [],
        historicalImportance: [{ label: 'Mormon Settlement', value: '1847 arrival' }, { label: 'Bonneville Salt Flats', value: 'Land speed records' }]
    }
];
