// ============================================
// LAKES DATA - FILE 5 (Lakes 41-50)
// ============================================

const lakesData5 = [
    {
        id: 'lake-maracaibo',
        name: 'Lake Maracaibo',
        countries: [{ name: 'Venezuela', code: 'VE' }],
        continent: 'South America',
        waterType: 'saltwater',
        lakeType: 'Estuarine/Tectonic',
        surfaceArea: 13210,
        maxDepth: 60,
        avgDepth: 20,
        volume: 280,
        elevation: 0,
        coordinates: [9.8, -71.5],
        defaultZoom: 7,
        image: 'https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?w=400',
        backgroundImage: 'https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?w=1920',
        geoJSON: { type: 'Feature', properties: { name: 'Lake Maracaibo' }, geometry: { type: 'Polygon', coordinates: [[[-72.5, 10.5], [-71.5, 11.0], [-70.8, 10.5], [-71.0, 9.5], [-71.8, 9.0], [-72.5, 9.5], [-72.5, 10.5]]] } },
        inflowRivers: [{ name: 'Catatumbo River', length: 500, coordinates: [[-72.5, 9.5], [-72.0, 9.8], [-71.5, 10.0]] }],
        outflowRivers: [{ name: 'Gulf of Venezuela', length: 50, coordinates: [[-71.5, 11.0], [-71.0, 11.5], [-70.5, 12.0]] }],
        basinArea: 89000,
        islands: [{ name: 'San Carlos Island', coordinates: [9.97, -71.6], area: 1 }],
        cities: [{ name: 'Maracaibo', coordinates: [10.6544, -71.6385], country: 'Venezuela', population: 1900000 }, { name: 'Cabimas', coordinates: [10.3956, -71.4525], country: 'Venezuela', population: 230000 }],
        biodiversity: [{ label: 'Catatumbo Lightning', value: 'Unique weather phenomenon' }, { label: 'Fish Species', value: 'Freshwater and marine species' }],
        economicImportance: [{ label: 'Oil Industry', value: 'Major oil production since 1914' }, { label: 'Fishing', value: 'Commercial fisheries' }],
        environmentalIssues: [{ label: 'Oil Pollution', value: 'Extensive contamination' }, { label: 'Duckweed', value: 'Lemna infestation' }],
        waterDisputes: [],
        historicalImportance: [{ label: 'Oil Discovery', value: '1914 - transformed Venezuela' }, { label: 'Pre-Columbian', value: 'Wayuu people territory' }]
    },
    {
        id: 'aral-sea',
        name: 'Aral Sea',
        countries: [{ name: 'Kazakhstan', code: 'KZ' }, { name: 'Uzbekistan', code: 'UZ' }],
        continent: 'Asia',
        waterType: 'saltwater',
        lakeType: 'Endorheic',
        surfaceArea: 8300,
        maxDepth: 42,
        avgDepth: 16,
        volume: 75,
        elevation: 42,
        coordinates: [45.0, 59.5],
        defaultZoom: 6,
        image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400',
        backgroundImage: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1920',
        geoJSON: { type: 'Feature', properties: { name: 'Aral Sea' }, geometry: { type: 'Polygon', coordinates: [[[58.0, 46.5], [60.5, 46.0], [61.0, 44.5], [60.0, 43.5], [58.5, 44.0], [58.0, 45.0], [58.0, 46.5]]] } },
        inflowRivers: [{ name: 'Amu Darya (reduced)', length: 2540, coordinates: [[60.0, 42.0], [60.5, 43.0], [61.0, 44.0]] }, { name: 'Syr Darya (reduced)', length: 2212, coordinates: [[60.0, 45.5], [59.5, 45.0], [59.0, 44.5]] }],
        outflowRivers: [],
        basinArea: 690000,
        islands: [{ name: 'Vozrozhdeniya', coordinates: [44.95, 59.32], area: 200, description: 'Former bioweapons site' }],
        cities: [{ name: 'Aralsk', coordinates: [46.7933, 61.66], country: 'Kazakhstan', population: 30000 }, { name: 'Muynak', coordinates: [43.7667, 59.0333], country: 'Uzbekistan', population: 12000 }],
        biodiversity: [{ label: 'Collapse', value: '90% of species lost' }, { label: 'Former', value: 'Once 24 fish species' }],
        economicImportance: [{ label: 'Former Fishing', value: 'Industry collapsed' }, { label: 'Cotton Irrigation', value: 'Cause of disaster' }],
        environmentalIssues: [{ label: 'Ecological Disaster', value: '90% water loss since 1960' }, { label: 'Dust Storms', value: 'Toxic salt and pesticides' }, { label: 'Health Crisis', value: 'Respiratory diseases' }],
        waterDisputes: [{ label: 'Central Asian', value: 'Water sharing conflicts' }],
        historicalImportance: [{ label: 'Soviet Project', value: 'Cotton production priority' }, { label: '4th Largest', value: 'Was 4th largest lake in 1960' }]
    },
    {
        id: 'lake-tonle-sap',
        name: 'Tonlé Sap',
        countries: [{ name: 'Cambodia', code: 'KH' }],
        continent: 'Asia',
        waterType: 'freshwater',
        lakeType: 'Floodplain',
        surfaceArea: 2700,
        maxDepth: 10,
        avgDepth: 2,
        volume: 40,
        elevation: 2,
        coordinates: [12.9, 104.0],
        defaultZoom: 8,
        image: 'https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?w=400',
        backgroundImage: 'https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?w=1920',
        geoJSON: { type: 'Feature', properties: { name: 'Tonle Sap' }, geometry: { type: 'Polygon', coordinates: [[[103.5, 13.2], [104.5, 13.0], [104.8, 12.6], [104.2, 12.4], [103.5, 12.6], [103.3, 12.9], [103.5, 13.2]]] } },
        inflowRivers: [{ name: 'Tonle Sap River (seasonal)', length: 100, coordinates: [[105.0, 11.5], [104.5, 12.0], [104.0, 12.5]] }],
        outflowRivers: [{ name: 'Tonle Sap River (seasonal)', length: 100, coordinates: [[104.0, 12.5], [104.5, 12.0], [105.0, 11.5]] }],
        basinArea: 85000,
        islands: [],
        cities: [{ name: 'Siem Reap', coordinates: [13.3671, 103.8448], country: 'Cambodia', population: 250000 }, { name: 'Battambang', coordinates: [13.0957, 103.2022], country: 'Cambodia', population: 200000 }],
        biodiversity: [{ label: 'Fish Species', value: '300+ species' }, { label: 'Unique', value: 'Mekong Giant Catfish' }, { label: 'Birds', value: 'Major bird sanctuary' }],
        economicImportance: [{ label: 'Fishing', value: '75% of Cambodia\'s fish' }, { label: 'Rice', value: 'Floodplain agriculture' }, { label: 'Tourism', value: 'Floating villages' }],
        environmentalIssues: [{ label: 'Overfishing', value: 'Declining catches' }, { label: 'Upstream Dams', value: 'Mekong dam impacts' }],
        waterDisputes: [{ label: 'Mekong', value: 'Upstream dam impacts' }],
        historicalImportance: [{ label: 'Angkor', value: 'Supported Khmer Empire' }, { label: 'Flow Reversal', value: 'Unique tidal phenomenon' }]
    },
    {
        id: 'lake-chad',
        name: 'Lake Chad',
        countries: [{ name: 'Chad', code: 'TD' }, { name: 'Cameroon', code: 'CM' }, { name: 'Niger', code: 'NE' }, { name: 'Nigeria', code: 'NG' }],
        continent: 'Africa',
        waterType: 'freshwater',
        lakeType: 'Endorheic',
        surfaceArea: 1350,
        maxDepth: 11,
        avgDepth: 4,
        volume: 72,
        elevation: 280,
        coordinates: [13.5, 14.0],
        defaultZoom: 7,
        image: 'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=400',
        backgroundImage: 'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=1920',
        geoJSON: { type: 'Feature', properties: { name: 'Lake Chad' }, geometry: { type: 'Polygon', coordinates: [[[13.0, 14.0], [14.5, 14.2], [15.0, 13.5], [14.5, 12.8], [13.5, 13.0], [13.0, 13.5], [13.0, 14.0]]] } },
        inflowRivers: [{ name: 'Chari River', length: 1400, coordinates: [[15.0, 12.0], [14.5, 12.5], [14.0, 13.0]] }],
        outflowRivers: [],
        basinArea: 2434000,
        islands: [],
        cities: [{ name: 'N\'Djamena', coordinates: [12.1348, 15.0557], country: 'Chad', population: 1200000 }, { name: 'Maiduguri', coordinates: [11.8333, 13.15], country: 'Nigeria', population: 1100000 }],
        biodiversity: [{ label: 'Fish Species', value: 'Declining diversity' }, { label: 'Crocodiles', value: 'Reduced population' }],
        economicImportance: [{ label: 'Fishing', value: 'Supports 30 million people' }, { label: 'Agriculture', value: 'Irrigation farming' }],
        environmentalIssues: [{ label: 'Shrinkage', value: '90% loss since 1963' }, { label: 'Climate Change', value: 'Reduced rainfall' }, { label: 'Irrigation', value: 'Excessive water extraction' }],
        waterDisputes: [{ label: 'Four Nations', value: 'Lake Chad Basin Commission' }],
        historicalImportance: [{ label: 'Ancient Lake', value: 'Once mega-lake in Sahara' }, { label: 'Trade Routes', value: 'Trans-Saharan trade' }]
    },
    {
        id: 'lake-okeechobee',
        name: 'Lake Okeechobee',
        countries: [{ name: 'United States', code: 'US' }],
        continent: 'North America',
        waterType: 'freshwater',
        lakeType: 'Natural/Modified',
        surfaceArea: 1900,
        maxDepth: 4,
        avgDepth: 3,
        volume: 5.2,
        elevation: 4,
        coordinates: [26.95, -80.8],
        defaultZoom: 9,
        image: 'https://images.unsplash.com/photo-1505765050516-f72dcac9c60e?w=400',
        backgroundImage: 'https://images.unsplash.com/photo-1505765050516-f72dcac9c60e?w=1920',
        geoJSON: { type: 'Feature', properties: { name: 'Lake Okeechobee' }, geometry: { type: 'Polygon', coordinates: [[[-81.2, 27.2], [-80.6, 27.1], [-80.4, 26.8], [-80.7, 26.7], [-81.1, 26.8], [-81.3, 27.0], [-81.2, 27.2]]] } },
        inflowRivers: [{ name: 'Kissimmee River', length: 222, coordinates: [[-81.0, 27.8], [-80.9, 27.5], [-80.8, 27.2]] }],
        outflowRivers: [{ name: 'St. Lucie Canal', length: 56, coordinates: [[-80.4, 27.0], [-80.2, 27.1], [-80.0, 27.2]] }],
        basinArea: 12000,
        islands: [],
        cities: [{ name: 'West Palm Beach', coordinates: [26.7153, -80.0534], country: 'USA', population: 110000 }],
        biodiversity: [{ label: 'Fish Species', value: 'Largemouth Bass, Crappie' }, { label: 'Birds', value: 'Wading birds, waterfowl' }],
        economicImportance: [{ label: 'Water Supply', value: 'South Florida supply' }, { label: 'Agriculture', value: 'Sugar cane irrigation' }, { label: 'Bass Fishing', value: 'Sport fishing destination' }],
        environmentalIssues: [{ label: 'Algae Blooms', value: 'Toxic blue-green algae' }, { label: 'Phosphorus', value: 'Agricultural runoff' }],
        waterDisputes: [],
        historicalImportance: [{ label: 'Name', value: 'Seminole "big water"' }, { label: 'Herbert Hoover Dike', value: '1930s flood control' }]
    },
    {
        id: 'lake-sevan',
        name: 'Lake Sevan',
        countries: [{ name: 'Armenia', code: 'AM' }],
        continent: 'Asia',
        waterType: 'freshwater',
        lakeType: 'Volcanic/Tectonic',
        surfaceArea: 1242,
        maxDepth: 80,
        avgDepth: 27,
        volume: 34,
        elevation: 1900,
        coordinates: [40.3, 45.3],
        defaultZoom: 9,
        image: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400',
        backgroundImage: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=1920',
        geoJSON: { type: 'Feature', properties: { name: 'Lake Sevan' }, geometry: { type: 'Polygon', coordinates: [[[44.9, 40.5], [45.5, 40.6], [45.8, 40.3], [45.5, 40.0], [44.9, 40.1], [44.7, 40.3], [44.9, 40.5]]] } },
        inflowRivers: [{ name: 'Gavaraget', length: 40, coordinates: [[45.3, 40.7], [45.3, 40.5], [45.3, 40.3]] }],
        outflowRivers: [{ name: 'Hrazdan River', length: 141, coordinates: [[44.8, 40.3], [44.5, 40.2], [44.2, 40.1]] }],
        basinArea: 4890,
        islands: [{ name: 'Sevan Island (peninsula)', coordinates: [40.37, 45.02], area: 0.28, description: '9th century monastery' }],
        cities: [{ name: 'Sevan', coordinates: [40.5481, 44.9469], country: 'Armenia', population: 19000 }],
        biodiversity: [{ label: 'Sevan Trout', value: 'Endemic species (endangered)' }, { label: 'Crayfish', value: 'Commercial species' }],
        economicImportance: [{ label: 'Hydropower', value: 'Sevan-Hrazdan cascade' }, { label: 'Tourism', value: 'Major resort area' }, { label: 'Fishing', value: 'Crayfish, whitefish' }],
        environmentalIssues: [{ label: 'Water Level Drop', value: '20m drop due to irrigation' }, { label: 'Eutrophication', value: 'Algae blooms' }],
        waterDisputes: [],
        historicalImportance: [{ label: 'Sevanavank', value: '874 AD monastery' }, { label: 'Armenian Culture', value: 'National symbol' }]
    },
    {
        id: 'lake-tana',
        name: 'Lake Tana',
        countries: [{ name: 'Ethiopia', code: 'ET' }],
        continent: 'Africa',
        waterType: 'freshwater',
        lakeType: 'Volcanic',
        surfaceArea: 3156,
        maxDepth: 15,
        avgDepth: 9,
        volume: 28,
        elevation: 1788,
        coordinates: [12.0, 37.3],
        defaultZoom: 8,
        image: 'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=400',
        backgroundImage: 'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=1920',
        geoJSON: { type: 'Feature', properties: { name: 'Lake Tana' }, geometry: { type: 'Polygon', coordinates: [[[36.9, 12.3], [37.5, 12.3], [37.7, 11.8], [37.3, 11.5], [36.9, 11.7], [36.7, 12.0], [36.9, 12.3]]] } },
        inflowRivers: [{ name: 'Gilgel Abay', length: 100, coordinates: [[36.5, 11.5], [37.0, 11.7], [37.3, 12.0]] }],
        outflowRivers: [{ name: 'Blue Nile', length: 1450, coordinates: [[37.5, 11.5], [38.0, 11.0], [38.5, 10.5]] }],
        basinArea: 16500,
        islands: [{ name: 'Daga Island', coordinates: [12.0, 37.35], area: 1 }, { name: 'Tana Qirqos', coordinates: [12.0, 37.2], area: 1 }],
        cities: [{ name: 'Bahir Dar', coordinates: [11.5936, 37.3908], country: 'Ethiopia', population: 350000 }, { name: 'Gondar', coordinates: [12.6, 37.4667], country: 'Ethiopia', population: 330000 }],
        biodiversity: [{ label: 'Hippos', value: 'Significant population' }, { label: 'Birds', value: 'Pelicans, herons, eagles' }],
        economicImportance: [{ label: 'Blue Nile Source', value: 'Origin of 80% of Nile water' }, { label: 'Fishing', value: 'Papyrus boat fishing' }, { label: 'Tourism', value: 'Island monasteries' }],
        environmentalIssues: [{ label: 'Water Hyacinth', value: 'Invasive species spread' }, { label: 'Deforestation', value: 'Watershed degradation' }],
        waterDisputes: [{ label: 'Nile Waters', value: 'GERD dam downstream' }],
        historicalImportance: [{ label: 'Blue Nile Source', value: 'Discovered by Europeans 1613' }, { label: 'Monasteries', value: '37 islands with ancient churches' }]
    },
    {
        id: 'lake-vattern',
        name: 'Lake Vättern',
        countries: [{ name: 'Sweden', code: 'SE' }],
        continent: 'Europe',
        waterType: 'freshwater',
        lakeType: 'Glacial/Tectonic',
        surfaceArea: 1912,
        maxDepth: 128,
        avgDepth: 40,
        volume: 77,
        elevation: 89,
        coordinates: [58.4, 14.6],
        defaultZoom: 8,
        image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
        backgroundImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=1920',
        geoJSON: { type: 'Feature', properties: { name: 'Lake Vattern' }, geometry: { type: 'Polygon', coordinates: [[[14.2, 58.9], [14.8, 58.8], [15.0, 58.2], [14.6, 57.8], [14.2, 58.0], [14.0, 58.5], [14.2, 58.9]]] } },
        inflowRivers: [{ name: 'Multiple small rivers', length: 50, coordinates: [[14.5, 58.5], [14.6, 58.4], [14.7, 58.3]] }],
        outflowRivers: [{ name: 'Motala ström', length: 100, coordinates: [[15.0, 58.5], [15.5, 58.4], [16.0, 58.3]] }],
        basinArea: 4503,
        islands: [{ name: 'Visingsö', coordinates: [58.02, 14.35], area: 25 }],
        cities: [{ name: 'Jönköping', coordinates: [57.7815, 14.1562], country: 'Sweden', population: 140000 }, { name: 'Motala', coordinates: [58.5372, 15.0364], country: 'Sweden', population: 43000 }],
        biodiversity: [{ label: 'Arctic Char', value: 'Unique population (röding)' }, { label: 'Clarity', value: 'Exceptional water clarity' }],
        economicImportance: [{ label: 'Water Supply', value: 'Drinking water source' }, { label: 'Tourism', value: 'Summer destination' }],
        environmentalIssues: [{ label: 'Protection', value: 'Well-protected ecosystem' }],
        waterDisputes: [],
        historicalImportance: [{ label: 'Göta Canal', value: 'Connected to Baltic' }, { label: '2nd Largest', value: 'In Sweden' }]
    },
    {
        id: 'lake-constance',
        name: 'Lake Constance (Bodensee)',
        countries: [{ name: 'Germany', code: 'DE' }, { name: 'Switzerland', code: 'CH' }, { name: 'Austria', code: 'AT' }],
        continent: 'Europe',
        waterType: 'freshwater',
        lakeType: 'Glacial',
        surfaceArea: 536,
        maxDepth: 254,
        avgDepth: 90,
        volume: 48,
        elevation: 395,
        coordinates: [47.6, 9.4],
        defaultZoom: 9,
        image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
        backgroundImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=1920',
        geoJSON: { type: 'Feature', properties: { name: 'Lake Constance' }, geometry: { type: 'Polygon', coordinates: [[[9.0, 47.7], [9.6, 47.7], [9.8, 47.5], [9.5, 47.45], [9.0, 47.5], [8.8, 47.6], [9.0, 47.7]]] } },
        inflowRivers: [{ name: 'Rhine River', length: 1230, coordinates: [[9.5, 47.0], [9.4, 47.3], [9.3, 47.5]] }],
        outflowRivers: [{ name: 'Rhine River', length: 1230, coordinates: [[8.8, 47.6], [8.5, 47.5], [8.2, 47.5]] }],
        basinArea: 11500,
        islands: [{ name: 'Mainau', coordinates: [47.7, 9.19], area: 0.45 }, { name: 'Reichenau', coordinates: [47.69, 9.06], area: 4.3 }],
        cities: [{ name: 'Konstanz', coordinates: [47.6633, 9.175], country: 'Germany', population: 85000 }, { name: 'Friedrichshafen', coordinates: [47.6544, 9.4793], country: 'Germany', population: 60000 }, { name: 'Bregenz', coordinates: [47.5025, 9.7494], country: 'Austria', population: 29000 }],
        biodiversity: [{ label: 'Fish Species', value: 'Whitefish, Pike, Perch' }, { label: 'Recovery', value: 'Improved from 1970s pollution' }],
        economicImportance: [{ label: 'Tourism', value: 'Major tourist region' }, { label: 'Water Supply', value: '4 million people' }, { label: 'Shipping', value: 'Ferry connections' }],
        environmentalIssues: [{ label: 'Microplastics', value: 'Research concern' }, { label: 'Climate Change', value: 'Temperature increase' }],
        waterDisputes: [{ label: 'Border Undefined', value: 'No agreed border between countries' }],
        historicalImportance: [{ label: 'Reichenau', value: 'UNESCO monastery island' }, { label: 'Zeppelin', value: 'Birthplace of airships' }]
    },
    {
        id: 'lake-geneva',
        name: 'Lake Geneva (Lac Léman)',
        countries: [{ name: 'Switzerland', code: 'CH' }, { name: 'France', code: 'FR' }],
        continent: 'Europe',
        waterType: 'freshwater',
        lakeType: 'Glacial',
        surfaceArea: 580,
        maxDepth: 310,
        avgDepth: 154,
        volume: 89,
        elevation: 372,
        coordinates: [46.45, 6.5],
        defaultZoom: 9,
        image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400',
        backgroundImage: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1920',
        geoJSON: { type: 'Feature', properties: { name: 'Lake Geneva' }, geometry: { type: 'Polygon', coordinates: [[[6.15, 46.5], [6.85, 46.45], [7.0, 46.35], [6.7, 46.25], [6.3, 46.3], [6.1, 46.4], [6.15, 46.5]]] } },
        inflowRivers: [{ name: 'Rhône River', length: 812, coordinates: [[7.0, 46.4], [6.8, 46.4], [6.6, 46.4]] }],
        outflowRivers: [{ name: 'Rhône River', length: 812, coordinates: [[6.15, 46.2], [5.9, 46.0], [5.5, 45.8]] }],
        basinArea: 7975,
        islands: [],
        cities: [{ name: 'Geneva', coordinates: [46.2044, 6.1432], country: 'Switzerland', population: 200000 }, { name: 'Lausanne', coordinates: [46.5197, 6.6323], country: 'Switzerland', population: 140000 }, { name: 'Evian', coordinates: [46.4003, 6.5893], country: 'France', population: 9000 }],
        biodiversity: [{ label: 'Fish Species', value: 'Perch, Arctic Char, Pike' }],
        economicImportance: [{ label: 'Tourism', value: 'Luxury tourism hub' }, { label: 'Water Supply', value: 'Major source' }, { label: 'Wine', value: 'Lavaux vineyards UNESCO' }],
        environmentalIssues: [{ label: 'Microplastics', value: 'Research findings' }, { label: 'Temperature Rise', value: 'Climate impacts' }],
        waterDisputes: [],
        historicalImportance: [{ label: 'Treaties', value: 'Geneva Convention birthplace' }, { label: 'Jet d\'Eau', value: 'Famous fountain' }]
    }
];
