// ============================================
// UNITY ATLAS - Complete Countries Database
// All 197 Recognized Nations
// ============================================

const COUNTRIES_DATABASE = {
    // Metadata
    version: "1.0.0",
    totalCountries: 197,
    lastUpdated: "2024-01-01",
    
    // Region Definitions
    regions: {
        asia: "Asia",
        africa: "Africa", 
        europe: "Europe",
        "north-america": "North America",
        "south-america": "South America",
        oceania: "Oceania"
    },
    
    // All 197 Countries with Complete Data
    countries: [
        // ===== ASIA (48 countries) =====
        { code: "AF", name: "Afghanistan", flag: "🇦🇫", region: "asia", capital: "Kabul", coords: [33.93, 67.71] },
        { code: "AM", name: "Armenia", flag: "🇦🇲", region: "asia", capital: "Yerevan", coords: [40.07, 45.04] },
        { code: "AZ", name: "Azerbaijan", flag: "🇦🇿", region: "asia", capital: "Baku", coords: [40.14, 47.58] },
        { code: "BH", name: "Bahrain", flag: "🇧🇭", region: "asia", capital: "Manama", coords: [26.07, 50.56] },
        { code: "BD", name: "Bangladesh", flag: "🇧🇩", region: "asia", capital: "Dhaka", coords: [23.68, 90.36] },
        { code: "BT", name: "Bhutan", flag: "🇧🇹", region: "asia", capital: "Thimphu", coords: [27.51, 90.43] },
        { code: "BN", name: "Brunei", flag: "🇧🇳", region: "asia", capital: "Bandar Seri Begawan", coords: [4.90, 114.94] },
        { code: "KH", name: "Cambodia", flag: "🇰🇭", region: "asia", capital: "Phnom Penh", coords: [12.57, 104.99] },
        { code: "CN", name: "China", flag: "🇨🇳", region: "asia", capital: "Beijing", coords: [35.86, 104.20] },
        { code: "CY", name: "Cyprus", flag: "🇨🇾", region: "asia", capital: "Nicosia", coords: [35.13, 33.43] },
        { code: "GE", name: "Georgia", flag: "🇬🇪", region: "asia", capital: "Tbilisi", coords: [42.32, 43.36] },
        { code: "IN", name: "India", flag: "🇮🇳", region: "asia", capital: "New Delhi", coords: [20.59, 78.96] },
        { code: "ID", name: "Indonesia", flag: "🇮🇩", region: "asia", capital: "Jakarta", coords: [-0.79, 113.92] },
        { code: "IR", name: "Iran", flag: "🇮🇷", region: "asia", capital: "Tehran", coords: [32.43, 53.69] },
        { code: "IQ", name: "Iraq", flag: "🇮🇶", region: "asia", capital: "Baghdad", coords: [33.22, 43.68] },
        { code: "IL", name: "Israel", flag: "🇮🇱", region: "asia", capital: "Jerusalem", coords: [31.05, 34.85] },
        { code: "JP", name: "Japan", flag: "🇯🇵", region: "asia", capital: "Tokyo", coords: [36.20, 138.25] },
        { code: "JO", name: "Jordan", flag: "🇯🇴", region: "asia", capital: "Amman", coords: [30.59, 36.24] },
        { code: "KZ", name: "Kazakhstan", flag: "🇰🇿", region: "asia", capital: "Nur-Sultan", coords: [48.02, 66.92] },
        { code: "KW", name: "Kuwait", flag: "🇰🇼", region: "asia", capital: "Kuwait City", coords: [29.31, 47.48] },
        { code: "KG", name: "Kyrgyzstan", flag: "🇰🇬", region: "asia", capital: "Bishkek", coords: [41.20, 74.77] },
        { code: "LA", name: "Laos", flag: "🇱🇦", region: "asia", capital: "Vientiane", coords: [19.86, 102.50] },
        { code: "LB", name: "Lebanon", flag: "🇱🇧", region: "asia", capital: "Beirut", coords: [33.85, 35.86] },
        { code: "MY", name: "Malaysia", flag: "🇲🇾", region: "asia", capital: "Kuala Lumpur", coords: [4.21, 101.98] },
        { code: "MV", name: "Maldives", flag: "🇲🇻", region: "asia", capital: "Malé", coords: [3.20, 73.22] },
        { code: "MN", name: "Mongolia", flag: "🇲🇳", region: "asia", capital: "Ulaanbaatar", coords: [46.86, 103.85] },
        { code: "MM", name: "Myanmar", flag: "🇲🇲", region: "asia", capital: "Naypyidaw", coords: [21.91, 95.96] },
        { code: "NP", name: "Nepal", flag: "🇳🇵", region: "asia", capital: "Kathmandu", coords: [28.39, 84.12] },
        { code: "KP", name: "North Korea", flag: "🇰🇵", region: "asia", capital: "Pyongyang", coords: [40.34, 127.51] },
        { code: "OM", name: "Oman", flag: "🇴🇲", region: "asia", capital: "Muscat", coords: [21.51, 55.92] },
        { code: "PK", name: "Pakistan", flag: "🇵🇰", region: "asia", capital: "Islamabad", coords: [30.38, 69.35] },
        { code: "PS", name: "Palestine", flag: "🇵🇸", region: "asia", capital: "Ramallah", coords: [31.95, 35.23] },
        { code: "PH", name: "Philippines", flag: "🇵🇭", region: "asia", capital: "Manila", coords: [12.88, 121.77] },
        { code: "QA", name: "Qatar", flag: "🇶🇦", region: "asia", capital: "Doha", coords: [25.35, 51.18] },
        { code: "SA", name: "Saudi Arabia", flag: "🇸🇦", region: "asia", capital: "Riyadh", coords: [23.89, 45.08] },
        { code: "SG", name: "Singapore", flag: "🇸🇬", region: "asia", capital: "Singapore", coords: [1.35, 103.82] },
        { code: "KR", name: "South Korea", flag: "🇰🇷", region: "asia", capital: "Seoul", coords: [35.91, 127.77] },
        { code: "LK", name: "Sri Lanka", flag: "🇱🇰", region: "asia", capital: "Sri Jayawardenepura Kotte", coords: [7.87, 80.77] },
        { code: "SY", name: "Syria", flag: "🇸🇾", region: "asia", capital: "Damascus", coords: [34.80, 39.00] },
        { code: "TW", name: "Taiwan", flag: "🇹🇼", region: "asia", capital: "Taipei", coords: [23.70, 121.00] },
        { code: "TJ", name: "Tajikistan", flag: "🇹🇯", region: "asia", capital: "Dushanbe", coords: [38.86, 71.28] },
        { code: "TH", name: "Thailand", flag: "🇹🇭", region: "asia", capital: "Bangkok", coords: [15.87, 100.99] },
        { code: "TL", name: "Timor-Leste", flag: "🇹🇱", region: "asia", capital: "Dili", coords: [-8.87, 125.73] },
        { code: "TR", name: "Turkey", flag: "🇹🇷", region: "asia", capital: "Ankara", coords: [38.96, 35.24] },
        { code: "TM", name: "Turkmenistan", flag: "🇹🇲", region: "asia", capital: "Ashgabat", coords: [38.97, 59.56] },
        { code: "AE", name: "United Arab Emirates", flag: "🇦🇪", region: "asia", capital: "Abu Dhabi", coords: [23.42, 53.85] },
        { code: "UZ", name: "Uzbekistan", flag: "🇺🇿", region: "asia", capital: "Tashkent", coords: [41.38, 64.59] },
        { code: "VN", name: "Vietnam", flag: "🇻🇳", region: "asia", capital: "Hanoi", coords: [14.06, 108.28] },
        { code: "YE", name: "Yemen", flag: "🇾🇪", region: "asia", capital: "Sana'a", coords: [15.55, 48.52] },

        // ===== AFRICA (54 countries) =====
        { code: "DZ", name: "Algeria", flag: "🇩🇿", region: "africa", capital: "Algiers", coords: [28.03, 1.66] },
        { code: "AO", name: "Angola", flag: "🇦🇴", region: "africa", capital: "Luanda", coords: [-11.20, 17.87] },
        { code: "BJ", name: "Benin", flag: "🇧🇯", region: "africa", capital: "Porto-Novo", coords: [9.31, 2.32] },
        { code: "BW", name: "Botswana", flag: "🇧🇼", region: "africa", capital: "Gaborone", coords: [-22.33, 24.68] },
        { code: "BF", name: "Burkina Faso", flag: "🇧🇫", region: "africa", capital: "Ouagadougou", coords: [12.24, -1.56] },
        { code: "BI", name: "Burundi", flag: "🇧🇮", region: "africa", capital: "Gitega", coords: [-3.37, 29.92] },
        { code: "CV", name: "Cabo Verde", flag: "🇨🇻", region: "africa", capital: "Praia", coords: [16.00, -24.01] },
        { code: "CM", name: "Cameroon", flag: "🇨🇲", region: "africa", capital: "Yaoundé", coords: [7.37, 12.35] },
        { code: "CF", name: "Central African Republic", flag: "🇨🇫", region: "africa", capital: "Bangui", coords: [6.61, 20.94] },
        { code: "TD", name: "Chad", flag: "🇹🇩", region: "africa", capital: "N'Djamena", coords: [15.45, 18.73] },
        { code: "KM", name: "Comoros", flag: "🇰🇲", region: "africa", capital: "Moroni", coords: [-11.88, 43.87] },
        { code: "CG", name: "Congo", flag: "🇨🇬", region: "africa", capital: "Brazzaville", coords: [-0.23, 15.83] },
        { code: "CD", name: "DR Congo", flag: "🇨🇩", region: "africa", capital: "Kinshasa", coords: [-4.04, 21.76] },
        { code: "CI", name: "Côte d'Ivoire", flag: "🇨🇮", region: "africa", capital: "Yamoussoukro", coords: [7.54, -5.55] },
        { code: "DJ", name: "Djibouti", flag: "🇩🇯", region: "africa", capital: "Djibouti", coords: [11.83, 42.59] },
        { code: "EG", name: "Egypt", flag: "🇪🇬", region: "africa", capital: "Cairo", coords: [26.82, 30.80] },
        { code: "GQ", name: "Equatorial Guinea", flag: "🇬🇶", region: "africa", capital: "Malabo", coords: [1.65, 10.27] },
        { code: "ER", name: "Eritrea", flag: "🇪🇷", region: "africa", capital: "Asmara", coords: [15.18, 39.78] },
        { code: "SZ", name: "Eswatini", flag: "🇸🇿", region: "africa", capital: "Mbabane", coords: [-26.52, 31.47] },
        { code: "ET", name: "Ethiopia", flag: "🇪🇹", region: "africa", capital: "Addis Ababa", coords: [9.15, 40.49] },
        { code: "GA", name: "Gabon", flag: "🇬🇦", region: "africa", capital: "Libreville", coords: [-0.80, 11.61] },
        { code: "GM", name: "Gambia", flag: "🇬🇲", region: "africa", capital: "Banjul", coords: [13.44, -15.31] },
        { code: "GH", name: "Ghana", flag: "🇬🇭", region: "africa", capital: "Accra", coords: [7.95, -1.02] },
        { code: "GN", name: "Guinea", flag: "🇬🇳", region: "africa", capital: "Conakry", coords: [9.95, -9.70] },
        { code: "GW", name: "Guinea-Bissau", flag: "🇬🇼", region: "africa", capital: "Bissau", coords: [11.80, -15.18] },
        { code: "KE", name: "Kenya", flag: "🇰🇪", region: "africa", capital: "Nairobi", coords: [-0.02, 37.91] },
        { code: "LS", name: "Lesotho", flag: "🇱🇸", region: "africa", capital: "Maseru", coords: [-29.61, 28.23] },
        { code: "LR", name: "Liberia", flag: "🇱🇷", region: "africa", capital: "Monrovia", coords: [6.43, -9.43] },
        { code: "LY", name: "Libya", flag: "🇱🇾", region: "africa", capital: "Tripoli", coords: [26.34, 17.23] },
        { code: "MG", name: "Madagascar", flag: "🇲🇬", region: "africa", capital: "Antananarivo", coords: [-18.77, 46.87] },
        { code: "MW", name: "Malawi", flag: "🇲🇼", region: "africa", capital: "Lilongwe", coords: [-13.25, 34.30] },
        { code: "ML", name: "Mali", flag: "🇲🇱", region: "africa", capital: "Bamako", coords: [17.57, -4.00] },
        { code: "MR", name: "Mauritania", flag: "🇲🇷", region: "africa", capital: "Nouakchott", coords: [21.01, -10.94] },
        { code: "MU", name: "Mauritius", flag: "🇲🇺", region: "africa", capital: "Port Louis", coords: [-20.35, 57.55] },
        { code: "MA", name: "Morocco", flag: "🇲🇦", region: "africa", capital: "Rabat", coords: [31.79, -7.09] },
        { code: "MZ", name: "Mozambique", flag: "🇲🇿", region: "africa", capital: "Maputo", coords: [-18.67, 35.53] },
        { code: "NA", name: "Namibia", flag: "🇳🇦", region: "africa", capital: "Windhoek", coords: [-22.96, 18.49] },
        { code: "NE", name: "Niger", flag: "🇳🇪", region: "africa", capital: "Niamey", coords: [17.61, 8.08] },
        { code: "NG", name: "Nigeria", flag: "🇳🇬", region: "africa", capital: "Abuja", coords: [9.08, 8.68] },
        { code: "RW", name: "Rwanda", flag: "🇷🇼", region: "africa", capital: "Kigali", coords: [-1.94, 29.87] },
        { code: "ST", name: "São Tomé and Príncipe", flag: "🇸🇹", region: "africa", capital: "São Tomé", coords: [0.19, 6.61] },
        { code: "SN", name: "Senegal", flag: "🇸🇳", region: "africa", capital: "Dakar", coords: [14.50, -14.45] },
        { code: "SC", name: "Seychelles", flag: "🇸🇨", region: "africa", capital: "Victoria", coords: [-4.68, 55.49] },
        { code: "SL", name: "Sierra Leone", flag: "🇸🇱", region: "africa", capital: "Freetown", coords: [8.46, -11.78] },
        { code: "SO", name: "Somalia", flag: "🇸🇴", region: "africa", capital: "Mogadishu", coords: [5.15, 46.20] },
        { code: "ZA", name: "South Africa", flag: "🇿🇦", region: "africa", capital: "Pretoria", coords: [-30.56, 22.94] },
        { code: "SS", name: "South Sudan", flag: "🇸🇸", region: "africa", capital: "Juba", coords: [6.88, 31.31] },
        { code: "SD", name: "Sudan", flag: "🇸🇩", region: "africa", capital: "Khartoum", coords: [12.86, 30.22] },
        { code: "TZ", name: "Tanzania", flag: "🇹🇿", region: "africa", capital: "Dodoma", coords: [-6.37, 34.89] },
        { code: "TG", name: "Togo", flag: "🇹🇬", region: "africa", capital: "Lomé", coords: [8.62, 0.82] },
        { code: "TN", name: "Tunisia", flag: "🇹🇳", region: "africa", capital: "Tunis", coords: [33.89, 9.54] },
        { code: "UG", name: "Uganda", flag: "🇺🇬", region: "africa", capital: "Kampala", coords: [1.37, 32.29] },
        { code: "ZM", name: "Zambia", flag: "🇿🇲", region: "africa", capital: "Lusaka", coords: [-13.13, 27.85] },
        { code: "ZW", name: "Zimbabwe", flag: "🇿🇼", region: "africa", capital: "Harare", coords: [-19.02, 29.15] },

        // ===== EUROPE (44 countries) =====
        { code: "AL", name: "Albania", flag: "🇦🇱", region: "europe", capital: "Tirana", coords: [41.15, 20.17] },
        { code: "AD", name: "Andorra", flag: "🇦🇩", region: "europe", capital: "Andorra la Vella", coords: [42.55, 1.60] },
        { code: "AT", name: "Austria", flag: "🇦🇹", region: "europe", capital: "Vienna", coords: [47.52, 14.55] },
        { code: "BY", name: "Belarus", flag: "🇧🇾", region: "europe", capital: "Minsk", coords: [53.71, 27.95] },
        { code: "BE", name: "Belgium", flag: "🇧🇪", region: "europe", capital: "Brussels", coords: [50.50, 4.47] },
        { code: "BA", name: "Bosnia and Herzegovina", flag: "🇧🇦", region: "europe", capital: "Sarajevo", coords: [43.92, 17.68] },
        { code: "BG", name: "Bulgaria", flag: "🇧🇬", region: "europe", capital: "Sofia", coords: [42.73, 25.49] },
        { code: "HR", name: "Croatia", flag: "🇭🇷", region: "europe", capital: "Zagreb", coords: [45.10, 15.20] },
        { code: "CZ", name: "Czech Republic", flag: "🇨🇿", region: "europe", capital: "Prague", coords: [49.82, 15.47] },
        { code: "DK", name: "Denmark", flag: "🇩🇰", region: "europe", capital: "Copenhagen", coords: [56.26, 9.50] },
        { code: "EE", name: "Estonia", flag: "🇪🇪", region: "europe", capital: "Tallinn", coords: [58.60, 25.01] },
        { code: "FI", name: "Finland", flag: "🇫🇮", region: "europe", capital: "Helsinki", coords: [61.92, 25.75] },
        { code: "FR", name: "France", flag: "🇫🇷", region: "europe", capital: "Paris", coords: [46.23, 2.21] },
        { code: "DE", name: "Germany", flag: "🇩🇪", region: "europe", capital: "Berlin", coords: [51.17, 10.45] },
        { code: "GR", name: "Greece", flag: "🇬🇷", region: "europe", capital: "Athens", coords: [39.07, 21.82] },
        { code: "HU", name: "Hungary", flag: "🇭🇺", region: "europe", capital: "Budapest", coords: [47.16, 19.50] },
        { code: "IS", name: "Iceland", flag: "🇮🇸", region: "europe", capital: "Reykjavik", coords: [64.96, -19.02] },
        { code: "IE", name: "Ireland", flag: "🇮🇪", region: "europe", capital: "Dublin", coords: [53.41, -8.24] },
        { code: "IT", name: "Italy", flag: "🇮🇹", region: "europe", capital: "Rome", coords: [41.87, 12.57] },
        { code: "XK", name: "Kosovo", flag: "🇽🇰", region: "europe", capital: "Pristina", coords: [42.60, 20.90] },
        { code: "LV", name: "Latvia", flag: "🇱🇻", region: "europe", capital: "Riga", coords: [56.88, 24.60] },
        { code: "LI", name: "Liechtenstein", flag: "🇱🇮", region: "europe", capital: "Vaduz", coords: [47.17, 9.56] },
        { code: "LT", name: "Lithuania", flag: "🇱🇹", region: "europe", capital: "Vilnius", coords: [55.17, 23.88] },
        { code: "LU", name: "Luxembourg", flag: "🇱🇺", region: "europe", capital: "Luxembourg", coords: [49.82, 6.13] },
        { code: "MT", name: "Malta", flag: "🇲🇹", region: "europe", capital: "Valletta", coords: [35.94, 14.38] },
        { code: "MD", name: "Moldova", flag: "🇲🇩", region: "europe", capital: "Chișinău", coords: [47.41, 28.37] },
        { code: "MC", name: "Monaco", flag: "🇲🇨", region: "europe", capital: "Monaco", coords: [43.75, 7.41] },
        { code: "ME", name: "Montenegro", flag: "🇲🇪", region: "europe", capital: "Podgorica", coords: [42.71, 19.37] },
        { code: "NL", name: "Netherlands", flag: "🇳🇱", region: "europe", capital: "Amsterdam", coords: [52.13, 5.29] },
        { code: "MK", name: "North Macedonia", flag: "🇲🇰", region: "europe", capital: "Skopje", coords: [41.51, 21.75] },
        { code: "NO", name: "Norway", flag: "🇳🇴", region: "europe", capital: "Oslo", coords: [60.47, 8.47] },
        { code: "PL", name: "Poland", flag: "🇵🇱", region: "europe", capital: "Warsaw", coords: [51.92, 19.15] },
        { code: "PT", name: "Portugal", flag: "🇵🇹", region: "europe", capital: "Lisbon", coords: [39.40, -8.22] },
        { code: "RO", name: "Romania", flag: "🇷🇴", region: "europe", capital: "Bucharest", coords: [45.94, 24.97] },
        { code: "RU", name: "Russia", flag: "🇷🇺", region: "europe", capital: "Moscow", coords: [61.52, 105.32] },
        { code: "SM", name: "San Marino", flag: "🇸🇲", region: "europe", capital: "San Marino", coords: [43.94, 12.46] },
        { code: "RS", name: "Serbia", flag: "🇷🇸", region: "europe", capital: "Belgrade", coords: [44.02, 21.01] },
        { code: "SK", name: "Slovakia", flag: "🇸🇰", region: "europe", capital: "Bratislava", coords: [48.67, 19.70] },
        { code: "SI", name: "Slovenia", flag: "🇸🇮", region: "europe", capital: "Ljubljana", coords: [46.15, 15.00] },
        { code: "ES", name: "Spain", flag: "🇪🇸", region: "europe", capital: "Madrid", coords: [40.46, -3.75] },
        { code: "SE", name: "Sweden", flag: "🇸🇪", region: "europe", capital: "Stockholm", coords: [60.13, 18.64] },
        { code: "CH", name: "Switzerland", flag: "🇨🇭", region: "europe", capital: "Bern", coords: [46.82, 8.23] },
        { code: "UA", name: "Ukraine", flag: "🇺🇦", region: "europe", capital: "Kyiv", coords: [48.38, 31.17] },
        { code: "GB", name: "United Kingdom", flag: "🇬🇧", region: "europe", capital: "London", coords: [55.38, -3.44] },
        { code: "VA", name: "Vatican City", flag: "🇻🇦", region: "europe", capital: "Vatican City", coords: [41.90, 12.45] },

        // ===== NORTH AMERICA (23 countries) =====
        { code: "AG", name: "Antigua and Barbuda", flag: "🇦🇬", region: "north-america", capital: "St. John's", coords: [17.06, -61.80] },
        { code: "BS", name: "Bahamas", flag: "🇧🇸", region: "north-america", capital: "Nassau", coords: [25.03, -77.40] },
        { code: "BB", name: "Barbados", flag: "🇧🇧", region: "north-america", capital: "Bridgetown", coords: [13.19, -59.54] },
        { code: "BZ", name: "Belize", flag: "🇧🇿", region: "north-america", capital: "Belmopan", coords: [17.19, -88.50] },
        { code: "CA", name: "Canada", flag: "🇨🇦", region: "north-america", capital: "Ottawa", coords: [56.13, -106.35] },
        { code: "CR", name: "Costa Rica", flag: "🇨🇷", region: "north-america", capital: "San José", coords: [9.75, -83.75] },
        { code: "CU", name: "Cuba", flag: "🇨🇺", region: "north-america", capital: "Havana", coords: [21.52, -77.78] },
        { code: "DM", name: "Dominica", flag: "🇩🇲", region: "north-america", capital: "Roseau", coords: [15.41, -61.37] },
        { code: "DO", name: "Dominican Republic", flag: "🇩🇴", region: "north-america", capital: "Santo Domingo", coords: [18.74, -70.16] },
        { code: "SV", name: "El Salvador", flag: "🇸🇻", region: "north-america", capital: "San Salvador", coords: [13.79, -88.90] },
        { code: "GD", name: "Grenada", flag: "🇬🇩", region: "north-america", capital: "St. George's", coords: [12.12, -61.68] },
        { code: "GT", name: "Guatemala", flag: "🇬🇹", region: "north-america", capital: "Guatemala City", coords: [15.78, -90.23] },
        { code: "HT", name: "Haiti", flag: "🇭🇹", region: "north-america", capital: "Port-au-Prince", coords: [18.97, -72.29] },
        { code: "HN", name: "Honduras", flag: "🇭🇳", region: "north-america", capital: "Tegucigalpa", coords: [15.20, -86.24] },
        { code: "JM", name: "Jamaica", flag: "🇯🇲", region: "north-america", capital: "Kingston", coords: [18.11, -77.30] },
        { code: "MX", name: "Mexico", flag: "🇲🇽", region: "north-america", capital: "Mexico City", coords: [23.63, -102.55] },
        { code: "NI", name: "Nicaragua", flag: "🇳🇮", region: "north-america", capital: "Managua", coords: [12.87, -85.21] },
        { code: "PA", name: "Panama", flag: "🇵🇦", region: "north-america", capital: "Panama City", coords: [8.54, -80.78] },
        { code: "KN", name: "Saint Kitts and Nevis", flag: "🇰🇳", region: "north-america", capital: "Basseterre", coords: [17.36, -62.78] },
        { code: "LC", name: "Saint Lucia", flag: "🇱🇨", region: "north-america", capital: "Castries", coords: [13.91, -60.98] },
        { code: "VC", name: "Saint Vincent and the Grenadines", flag: "🇻🇨", region: "north-america", capital: "Kingstown", coords: [12.98, -61.29] },
        { code: "TT", name: "Trinidad and Tobago", flag: "🇹🇹", region: "north-america", capital: "Port of Spain", coords: [10.69, -61.22] },
        { code: "US", name: "United States", flag: "🇺🇸", region: "north-america", capital: "Washington, D.C.", coords: [37.09, -95.71] },

        // ===== SOUTH AMERICA (12 countries) =====
        { code: "AR", name: "Argentina", flag: "🇦🇷", region: "south-america", capital: "Buenos Aires", coords: [-38.42, -63.62] },
        { code: "BO", name: "Bolivia", flag: "🇧🇴", region: "south-america", capital: "Sucre", coords: [-16.29, -63.59] },
        { code: "BR", name: "Brazil", flag: "🇧🇷", region: "south-america", capital: "Brasília", coords: [-14.24, -51.93] },
        { code: "CL", name: "Chile", flag: "🇨🇱", region: "south-america", capital: "Santiago", coords: [-35.68, -71.54] },
        { code: "CO", name: "Colombia", flag: "🇨🇴", region: "south-america", capital: "Bogotá", coords: [4.57, -74.30] },
        { code: "EC", name: "Ecuador", flag: "🇪🇨", region: "south-america", capital: "Quito", coords: [-1.83, -78.18] },
        { code: "GY", name: "Guyana", flag: "🇬🇾", region: "south-america", capital: "Georgetown", coords: [4.86, -58.93] },
        { code: "PY", name: "Paraguay", flag: "🇵🇾", region: "south-america", capital: "Asunción", coords: [-23.44, -58.44] },
        { code: "PE", name: "Peru", flag: "🇵🇪", region: "south-america", capital: "Lima", coords: [-9.19, -75.02] },
        { code: "SR", name: "Suriname", flag: "🇸🇷", region: "south-america", capital: "Paramaribo", coords: [3.92, -56.03] },
        { code: "UY", name: "Uruguay", flag: "🇺🇾", region: "south-america", capital: "Montevideo", coords: [-32.52, -55.77] },
        { code: "VE", name: "Venezuela", flag: "🇻🇪", region: "south-america", capital: "Caracas", coords: [6.42, -66.59] },

        // ===== OCEANIA (14 countries) =====
        { code: "AU", name: "Australia", flag: "🇦🇺", region: "oceania", capital: "Canberra", coords: [-25.27, 133.78] },
        { code: "FJ", name: "Fiji", flag: "🇫🇯", region: "oceania", capital: "Suva", coords: [-17.71, 178.07] },
        { code: "KI", name: "Kiribati", flag: "🇰🇮", region: "oceania", capital: "Tarawa", coords: [-3.37, -168.73] },
        { code: "MH", name: "Marshall Islands", flag: "🇲🇭", region: "oceania", capital: "Majuro", coords: [7.13, 171.18] },
        { code: "FM", name: "Micronesia", flag: "🇫🇲", region: "oceania", capital: "Palikir", coords: [7.43, 150.55] },
        { code: "NR", name: "Nauru", flag: "🇳🇷", region: "oceania", capital: "Yaren", coords: [-0.52, 166.93] },
        { code: "NZ", name: "New Zealand", flag: "🇳🇿", region: "oceania", capital: "Wellington", coords: [-40.90, 174.89] },
        { code: "PW", name: "Palau", flag: "🇵🇼", region: "oceania", capital: "Ngerulmud", coords: [7.51, 134.58] },
        { code: "PG", name: "Papua New Guinea", flag: "🇵🇬", region: "oceania", capital: "Port Moresby", coords: [-6.31, 143.96] },
        { code: "WS", name: "Samoa", flag: "🇼🇸", region: "oceania", capital: "Apia", coords: [-13.76, -172.10] },
        { code: "SB", name: "Solomon Islands", flag: "🇸🇧", region: "oceania", capital: "Honiara", coords: [-9.65, 160.16] },
        { code: "TO", name: "Tonga", flag: "🇹🇴", region: "oceania", capital: "Nuku'alofa", coords: [-21.18, -175.20] },
        { code: "TV", name: "Tuvalu", flag: "🇹🇻", region: "oceania", capital: "Funafuti", coords: [-7.11, 177.65] },
        { code: "VU", name: "Vanuatu", flag: "🇻🇺", region: "oceania", capital: "Port Vila", coords: [-15.38, 166.96] }
    ]
};

// Create lookup maps for quick access
const COUNTRY_BY_CODE = {};
const COUNTRY_BY_NAME = {};
COUNTRIES_DATABASE.countries.forEach(country => {
    COUNTRY_BY_CODE[country.code] = country;
    COUNTRY_BY_NAME[country.name.toLowerCase()] = country;
});

// Export for module usage
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { COUNTRIES_DATABASE, COUNTRY_BY_CODE, COUNTRY_BY_NAME };
}
